// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.10.0
//   protoc               v6.33.4
// source: activity.proto

/* eslint-disable */
import type { StandardizedActivity } from "./standardized_activity";

export const protobufPackage = "fitglue";

/** ActivitySource enum defines where the data originated. */
export enum ActivitySource {
  SOURCE_UNKNOWN = 0,
  SOURCE_HEVY = 1,
  SOURCE_FITBIT = 3,
  SOURCE_TEST = 99,
  UNRECOGNIZED = -1,
}

/** ActivityPayload is the unified message format published to Pub/Sub. */
export interface ActivityPayload {
  source: ActivitySource;
  /** Internal FitGlue User ID */
  userId: string;
  timestamp?:
    | Date
    | undefined;
  /** Raw JSON payload stringified (flexible but preserved) */
  originalPayloadJson: string;
  /** Extra tracing context */
  metadata: { [key: string]: string };
  standardizedActivity?:
    | StandardizedActivity
    | undefined;
  /** Execution tracing */
  pipelineExecutionId?: string | undefined;
}

export interface ActivityPayload_MetadataEntry {
  key: string;
  value: string;
}
