// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.10.0
//   protoc               v6.33.2
// source: activity.proto

/* eslint-disable */
import type { StandardizedActivity } from "./standardized_activity";

export const protobufPackage = "fitglue";

/** ActivitySource enum defines where the data originated. */
export enum ActivitySource {
  SOURCE_UNKNOWN = 0,
  SOURCE_HEVY = 1,
  SOURCE_FITBIT = 3,
  SOURCE_TEST = 99,
  UNRECOGNIZED = -1,
}

/** ActivityPayload is the unified message format published to Pub/Sub. */
export interface ActivityPayload {
  source: ActivitySource;
  /** Internal FitGlue User ID */
  userId: string;
  /** ISO 8601 Timestamp of activity start */
  timestamp: string;
  /** Raw JSON payload stringified (flexible but preserved) */
  originalPayloadJson: string;
  /** Extra tracing context */
  metadata: { [key: string]: string };
  standardizedActivity: StandardizedActivity | undefined;
}

export interface ActivityPayload_MetadataEntry {
  key: string;
  value: string;
}

/**
 * EnrichedActivityEvent is the message format for topic-enriched-activity.
 * EnrichedActivityEvent is the message format for topic-enriched-activity.
 */
export interface EnrichedActivityEvent {
  /** Identity */
  userId: string;
  /** Unique ID for the processed activity */
  activityId: string;
  source: ActivitySource;
  /** Core Metadata (Extracted for easy downstream access) */
  activityType: string;
  /** The final description (original or generated) */
  description: string;
  /** Activity Title */
  name: string;
  /** Full Data */
  activityData:
    | StandardizedActivity
    | undefined;
  /** Generated Artifacts */
  fitFileUri: string;
  /** Enrichment Metadata */
  appliedEnrichments: string[];
  /** Extra stats */
  enrichmentMetadata: { [key: string]: string };
  /** Routing information determined by the pipeline */
  destinations: string[];
  pipelineId: string;
}

export interface EnrichedActivityEvent_EnrichmentMetadataEntry {
  key: string;
  value: string;
}
