// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.10.0
//   protoc               v6.33.4
// source: auth.proto

/* eslint-disable */

export const protobufPackage = "fitglue";

/** Stored in Firestore collection `ingress_api_keys/{hash}` */
export interface ApiKeyRecord {
  userId: string;
  label: string;
  scopes: string[];
  createdAt?: Date | undefined;
  lastUsedAt?: Date | undefined;
}

/** Stored in Firestore collection `integrations/{provider}/ids/{external_id}` */
export interface IntegrationIdentity {
  userId: string;
  createdAt?: Date | undefined;
}
