// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.10.0
//   protoc               v6.33.4
// source: events.proto

/* eslint-disable */
import type { ActivitySource } from "./activity";
import type { ActivityType, StandardizedActivity } from "./standardized_activity";

export const protobufPackage = "fitglue.events";

/** CloudEventType enumerates all valid event types in the system. */
export enum CloudEventType {
  CLOUD_EVENT_TYPE_UNSPECIFIED = 0,
  /** CLOUD_EVENT_TYPE_ACTIVITY_CREATED - Activity Created: Payload is ActivityPayload */
  CLOUD_EVENT_TYPE_ACTIVITY_CREATED = 1,
  /** CLOUD_EVENT_TYPE_ACTIVITY_ENRICHED - Activity Enriched: Payload is ActivityPayload */
  CLOUD_EVENT_TYPE_ACTIVITY_ENRICHED = 2,
  /** CLOUD_EVENT_TYPE_JOB_ROUTED - Job Routed: Payload is ActivityPayload */
  CLOUD_EVENT_TYPE_JOB_ROUTED = 3,
  /** CLOUD_EVENT_TYPE_FITBIT_NOTIFICATION - Fitbit Notification: Payload is FitbitNotification (raw JSON) */
  CLOUD_EVENT_TYPE_FITBIT_NOTIFICATION = 4,
  /** CLOUD_EVENT_TYPE_ENRICHMENT_LAG - Enrichment Lag: Payload is ActivityPayload */
  CLOUD_EVENT_TYPE_ENRICHMENT_LAG = 5,
  /** CLOUD_EVENT_TYPE_INPUT_RESOLVED - Input Resolved: Payload is ActivityPayload (resumed) */
  CLOUD_EVENT_TYPE_INPUT_RESOLVED = 6,
  UNRECOGNIZED = -1,
}

/** CloudEventSource strings are URI references. */
export enum CloudEventSource {
  CLOUD_EVENT_SOURCE_UNSPECIFIED = 0,
  CLOUD_EVENT_SOURCE_HEVY = 1,
  CLOUD_EVENT_SOURCE_FITBIT_WEBHOOK = 2,
  CLOUD_EVENT_SOURCE_FITBIT_INGEST = 3,
  CLOUD_EVENT_SOURCE_ENRICHER = 4,
  CLOUD_EVENT_SOURCE_ROUTER = 5,
  CLOUD_EVENT_SOURCE_INPUTS_HANDLER = 6,
  CLOUD_EVENT_SOURCE_MOCK = 99,
  UNRECOGNIZED = -1,
}

/** Destination defines where enriched activities are routed. */
export enum Destination {
  DESTINATION_UNSPECIFIED = 0,
  DESTINATION_STRAVA = 1,
  DESTINATION_MOCK = 99,
  UNRECOGNIZED = -1,
}

/**
 * Event payload for CLOUD_EVENT_TYPE_ACTIVITY_ENRICHED
 * Also used contextually for Upload Trigger
 */
export interface EnrichedActivityEvent {
  activityId: string;
  userId: string;
  pipelineId: string;
  fitFileUri: string;
  name: string;
  description: string;
  activityType: ActivityType;
  startTime?:
    | Date
    | undefined;
  /** Restored fields from activity.proto consolidation: */
  source: ActivitySource;
  activityData?: StandardizedActivity | undefined;
  appliedEnrichments: string[];
  enrichmentMetadata: { [key: string]: string };
  destinations: Destination[];
  tags: string[];
  /** Execution tracing */
  pipelineExecutionId?: string | undefined;
}

export interface EnrichedActivityEvent_EnrichmentMetadataEntry {
  key: string;
  value: string;
}

export interface MessagePublishedData {
  data: Uint8Array;
  attributes: { [key: string]: string };
  messageId: string;
  publishTime: string;
}

export interface MessagePublishedData_AttributesEntry {
  key: string;
  value: string;
}
