// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.10.0
//   protoc               v6.33.4
// source: execution.proto

/* eslint-disable */

export const protobufPackage = "fitglue";

export enum ExecutionStatus {
  STATUS_UNKNOWN = 0,
  STATUS_STARTED = 1,
  STATUS_SUCCESS = 2,
  STATUS_FAILED = 3,
  STATUS_PENDING = 4,
  STATUS_WAITING = 5,
  STATUS_LAGGED_RETRY = 6,
  /** STATUS_SKIPPED - Pipeline halted (not a failure, e.g., loop prevention) */
  STATUS_SKIPPED = 7,
  UNRECOGNIZED = -1,
}

/** ExecutionRecord represents a function execution in Firestore */
export interface ExecutionRecord {
  /** Required: unique identifier */
  executionId: string;
  /** Required: which function executed */
  service: string;
  /** Required: current status */
  status: ExecutionStatus;
  /** Required: when it started */
  timestamp?:
    | Date
    | undefined;
  /** Required: how it was triggered */
  triggerType: string;
  /** Optional context fields */
  userId?:
    | string
    | undefined;
  /** For test cleanup */
  testRunId?:
    | string
    | undefined;
  /** Optional timing */
  startTime?: Date | undefined;
  endTime?:
    | Date
    | undefined;
  /** Optional results */
  errorMessage?:
    | string
    | undefined;
  /** JSON-encoded inputs */
  inputsJson?:
    | string
    | undefined;
  /** JSON-encoded outputs */
  outputsJson?:
    | string
    | undefined;
  /** When this record should be deleted */
  expireAt?:
    | Date
    | undefined;
  /** Pipeline execution tracking */
  pipelineExecutionId?: string | undefined;
}
