// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.10.0
//   protoc               v6.33.2
// source: execution.proto

/* eslint-disable */

export const protobufPackage = "fitglue";

export enum ExecutionStatus {
  STATUS_UNKNOWN = 0,
  STATUS_STARTED = 1,
  STATUS_SUCCESS = 2,
  STATUS_FAILED = 3,
  UNRECOGNIZED = -1,
}

/** ExecutionRecord represents a function execution in Firestore */
export interface ExecutionRecord {
  executionId: string;
  service: string;
  status: ExecutionStatus;
  timestamp:
    | Date
    | undefined;
  /** Optional context fields */
  userId: string;
  /** For test cleanup */
  testRunId: string;
  /** Trigger information */
  triggerType: string;
  /** Timing */
  startTime: Date | undefined;
  endTime:
    | Date
    | undefined;
  /** Results */
  errorMessage: string;
  /** JSON-encoded inputs */
  inputsJson: string;
  /** JSON-encoded outputs */
  outputsJson: string;
  /** Parent-child execution tracking */
  parentExecutionId: string;
}
