// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.10.0
//   protoc               v6.33.4
// source: fitbit.proto

/* eslint-disable */

export const protobufPackage = "fitglue";

/**
 * FitbitNotification represents the JSON payload sent by Fitbit Webhooks
 * and published to topic-fitbit-updates.
 */
export interface FitbitNotification {
  /** e.g. "activities" */
  collectionType: string;
  /** e.g. "2023-10-27" */
  date: string;
  /** Fitbit User ID (e.g. "7N8X9Y") */
  ownerId: string;
  /** e.g. "user" */
  ownerType: string;
  /** The subscription ID we created */
  subscriptionId: string;
}
