// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.10.0
//   protoc               v6.33.4
// source: pending_input.proto

/* eslint-disable */
import type { ActivityPayload } from "./activity";

export const protobufPackage = "fitglue";

/** PendingInput represents a paused pipeline execution waiting for user interaction. */
export interface PendingInput {
  activityId: string;
  userId: string;
  status: PendingInput_Status;
  /** Fields the user interface should ask for (e.g. "title", "description") */
  requiredFields: string[];
  /** Data provided by the user (filled when status=COMPLETED) */
  inputData: { [key: string]: string };
  /** The original payload to be re-published once input is provided */
  originalPayload?: ActivityPayload | undefined;
  createdAt?: Date | undefined;
  updatedAt?: Date | undefined;
  completedAt?: Date | undefined;
}

export enum PendingInput_Status {
  STATUS_UNSPECIFIED = 0,
  STATUS_WAITING = 1,
  STATUS_COMPLETED = 2,
  UNRECOGNIZED = -1,
}

export interface PendingInput_InputDataEntry {
  key: string;
  value: string;
}
