// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.10.0
//   protoc               v6.33.2
// source: plugin.proto

/* eslint-disable */

export const protobufPackage = "fitglue";

/** PluginType categorizes plugins */
export enum PluginType {
  PLUGIN_TYPE_UNSPECIFIED = 0,
  PLUGIN_TYPE_SOURCE = 1,
  PLUGIN_TYPE_ENRICHER = 2,
  PLUGIN_TYPE_DESTINATION = 3,
  UNRECOGNIZED = -1,
}

export enum ConfigFieldType {
  CONFIG_FIELD_TYPE_UNSPECIFIED = 0,
  CONFIG_FIELD_TYPE_STRING = 1,
  CONFIG_FIELD_TYPE_NUMBER = 2,
  CONFIG_FIELD_TYPE_BOOLEAN = 3,
  /** CONFIG_FIELD_TYPE_SELECT - Dropdown */
  CONFIG_FIELD_TYPE_SELECT = 4,
  /** CONFIG_FIELD_TYPE_MULTI_SELECT - Multiple selection */
  CONFIG_FIELD_TYPE_MULTI_SELECT = 5,
  /** CONFIG_FIELD_TYPE_KEY_VALUE_MAP - Record<string, string> map - stored as JSON */
  CONFIG_FIELD_TYPE_KEY_VALUE_MAP = 6,
  UNRECOGNIZED = -1,
}

/** PluginManifest defines metadata for any plugin */
export interface PluginManifest {
  /** Unique identifier (e.g., "hevy", "fitbit-hr", "strava") */
  id: string;
  /** Source, Enricher, or Destination */
  type: PluginType;
  /** Human-readable name */
  name: string;
  /** Short description */
  description: string;
  /** Emoji or icon name */
  icon: string;
  /** Configuration fields */
  configSchema: ConfigFieldSchema[];
  /** e.g., ["fitbit"] requires Fitbit connected */
  requiredIntegrations: string[];
  /** Whether this plugin is available */
  enabled: boolean;
  /** For enrichers: links to the EnricherProviderType enum value */
  enricherProviderType?:
    | number
    | undefined;
  /** For destinations: links to the Destination enum value */
  destinationType?: number | undefined;
}

/** ConfigFieldSchema defines a single configuration field */
export interface ConfigFieldSchema {
  /** Field key in config map */
  key: string;
  /** Human-readable label */
  label: string;
  /** Help text */
  description: string;
  /** Type of input */
  fieldType: ConfigFieldType;
  /** Whether field is required */
  required: boolean;
  /** Default value (as string) */
  defaultValue: string;
  /** For SELECT/MULTI_SELECT types */
  options: ConfigFieldOption[];
  /** Validation rules */
  validation?: ConfigFieldValidation | undefined;
}

export interface ConfigFieldOption {
  /** Stored value (descriptive string) */
  value: string;
  /** Display label */
  label: string;
}

export interface ConfigFieldValidation {
  minLength?: number | undefined;
  maxLength?:
    | number
    | undefined;
  /** Regex pattern */
  pattern?: string | undefined;
  minValue?: number | undefined;
  maxValue?: number | undefined;
}

/** PluginRegistryResponse for API discovery */
export interface PluginRegistryResponse {
  sources: PluginManifest[];
  enrichers: PluginManifest[];
  destinations: PluginManifest[];
}
