// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.10.0
//   protoc               v6.33.4
// source: standardized_activity.proto

/* eslint-disable */

export const protobufPackage = "fitglue";

/**
 * ActivityType enum based on Strava's accepted activity types.
 * Use the strava_name extension to get the exact Strava API string.
 * Stored as string in Firestore for readability.
 */
export enum ActivityType {
  ACTIVITY_TYPE_UNSPECIFIED = 0,
  ACTIVITY_TYPE_ALPINE_SKI = 1,
  ACTIVITY_TYPE_BACKCOUNTRY_SKI = 2,
  ACTIVITY_TYPE_BADMINTON = 3,
  ACTIVITY_TYPE_CANOEING = 4,
  ACTIVITY_TYPE_CROSSFIT = 5,
  ACTIVITY_TYPE_EBIKE_RIDE = 6,
  ACTIVITY_TYPE_ELLIPTICAL = 7,
  ACTIVITY_TYPE_EMOUNTAIN_BIKE_RIDE = 8,
  ACTIVITY_TYPE_GOLF = 9,
  ACTIVITY_TYPE_GRAVEL_RIDE = 10,
  ACTIVITY_TYPE_HANDCYCLE = 11,
  ACTIVITY_TYPE_HIGH_INTENSITY_INTERVAL_TRAINING = 12,
  ACTIVITY_TYPE_HIKE = 13,
  ACTIVITY_TYPE_ICE_SKATE = 14,
  ACTIVITY_TYPE_INLINE_SKATE = 15,
  ACTIVITY_TYPE_KAYAKING = 16,
  ACTIVITY_TYPE_KITESURF = 17,
  ACTIVITY_TYPE_MOUNTAIN_BIKE_RIDE = 18,
  ACTIVITY_TYPE_NORDIC_SKI = 19,
  ACTIVITY_TYPE_PICKLEBALL = 20,
  ACTIVITY_TYPE_PILATES = 21,
  ACTIVITY_TYPE_RACQUETBALL = 22,
  ACTIVITY_TYPE_RIDE = 23,
  ACTIVITY_TYPE_ROCK_CLIMBING = 24,
  ACTIVITY_TYPE_ROLLER_SKI = 25,
  ACTIVITY_TYPE_ROWING = 26,
  ACTIVITY_TYPE_RUN = 27,
  ACTIVITY_TYPE_SAIL = 28,
  ACTIVITY_TYPE_SKATEBOARD = 29,
  ACTIVITY_TYPE_SNOWBOARD = 30,
  ACTIVITY_TYPE_SNOWSHOE = 31,
  ACTIVITY_TYPE_SOCCER = 32,
  ACTIVITY_TYPE_SQUASH = 33,
  ACTIVITY_TYPE_STAIR_STEPPER = 34,
  ACTIVITY_TYPE_STAND_UP_PADDLING = 35,
  ACTIVITY_TYPE_SURFING = 36,
  ACTIVITY_TYPE_SWIM = 37,
  ACTIVITY_TYPE_TABLE_TENNIS = 38,
  ACTIVITY_TYPE_TENNIS = 39,
  ACTIVITY_TYPE_TRAIL_RUN = 40,
  ACTIVITY_TYPE_VELOMOBILE = 41,
  ACTIVITY_TYPE_VIRTUAL_RIDE = 42,
  ACTIVITY_TYPE_VIRTUAL_ROW = 43,
  ACTIVITY_TYPE_VIRTUAL_RUN = 44,
  ACTIVITY_TYPE_WALK = 45,
  ACTIVITY_TYPE_WEIGHT_TRAINING = 46,
  ACTIVITY_TYPE_WHEELCHAIR = 47,
  ACTIVITY_TYPE_WINDSURF = 48,
  ACTIVITY_TYPE_WORKOUT = 49,
  ACTIVITY_TYPE_YOGA = 50,
  UNRECOGNIZED = -1,
}

export enum MuscleGroup {
  MUSCLE_GROUP_UNSPECIFIED = 0,
  MUSCLE_GROUP_ABDOMINALS = 1,
  MUSCLE_GROUP_SHOULDERS = 2,
  MUSCLE_GROUP_BICEPS = 3,
  MUSCLE_GROUP_TRICEPS = 4,
  MUSCLE_GROUP_FOREARMS = 5,
  MUSCLE_GROUP_QUADRICEPS = 6,
  MUSCLE_GROUP_HAMSTRINGS = 7,
  MUSCLE_GROUP_CALVES = 8,
  MUSCLE_GROUP_GLUTES = 9,
  MUSCLE_GROUP_ABDUCTORS = 10,
  MUSCLE_GROUP_ADDUCTORS = 11,
  MUSCLE_GROUP_LATS = 12,
  MUSCLE_GROUP_UPPER_BACK = 13,
  MUSCLE_GROUP_TRAPS = 14,
  MUSCLE_GROUP_LOWER_BACK = 15,
  MUSCLE_GROUP_CHEST = 16,
  MUSCLE_GROUP_CARDIO = 17,
  MUSCLE_GROUP_NECK = 18,
  MUSCLE_GROUP_FULL_BODY = 19,
  MUSCLE_GROUP_OTHER = 20,
  UNRECOGNIZED = -1,
}

/**
 * StandardizedActivity represents a normalized fitness activity.
 * It is designed to be the canonical input format for the Enricher,
 * decoupling it from specific ingestion sources (Hevy, etc).
 *
 * Structure mimics the FIT SDK hierarchy:
 * Activity -> Sessions -> Laps -> Records
 */
export interface StandardizedActivity {
  /** e.g. "HEVY" */
  source: string;
  /** Source's ID (e.g. Hevy workout ID) */
  externalId: string;
  userId: string;
  /** High-level summary */
  startTime?:
    | Date
    | undefined;
  /** e.g. "Morning Run" */
  name: string;
  /** Strava-compatible activity type */
  type: ActivityType;
  /** Hierarchy */
  sessions: Session[];
  /** Rich metadata (preserved from source) */
  description: string;
  tags: string[];
  notes: string;
}

export interface Session {
  startTime?:
    | Date
    | undefined;
  /** seconds */
  totalElapsedTime: number;
  /** meters */
  totalDistance: number;
  laps: Lap[];
  /** High-fidelity strength data (not just 1Hz streams) */
  strengthSets: StrengthSet[];
}

export interface Lap {
  startTime?:
    | Date
    | undefined;
  /** seconds */
  totalElapsedTime: number;
  /** meters */
  totalDistance: number;
  records: Record[];
}

/** Record represents a single data point in time (1Hz is typical) */
export interface Record {
  timestamp?:
    | Date
    | undefined;
  /** Core Telemetry */
  heartRate: number;
  /** watts */
  power: number;
  /** rpm */
  cadence: number;
  /** m/s */
  speed: number;
  /** meters */
  altitude: number;
  /** Location */
  positionLat: number;
  positionLong: number;
}

/**
 * StrengthSet represents a discrete set of an exercise (common in weightlifting)
 * This is distinct from continuous Record streams.
 */
export interface StrengthSet {
  /** e.g. "Bench Press" */
  exerciseName: string;
  reps: number;
  weightKg: number;
  startTime?: Date | undefined;
  durationSeconds: number;
  notes: string;
  /** Organization */
  supersetId: string;
  /** Muscle Targeting */
  primaryMuscleGroup: MuscleGroup;
  secondaryMuscleGroups: MuscleGroup[];
  /** Distance (for cardio/distance-based exercises) */
  distanceMeters: number;
  /** Set Type (warmup, normal, failure, dropset) */
  setType: string;
}
