// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.10.0
//   protoc               v6.33.2
// source: standardized_activity.proto

/* eslint-disable */

export const protobufPackage = "fitglue";

export enum MuscleGroup {
  MUSCLE_GROUP_UNSPECIFIED = 0,
  MUSCLE_GROUP_ABDOMINALS = 1,
  MUSCLE_GROUP_SHOULDERS = 2,
  MUSCLE_GROUP_BICEPS = 3,
  MUSCLE_GROUP_TRICEPS = 4,
  MUSCLE_GROUP_FOREARMS = 5,
  MUSCLE_GROUP_QUADRICEPS = 6,
  MUSCLE_GROUP_HAMSTRINGS = 7,
  MUSCLE_GROUP_CALVES = 8,
  MUSCLE_GROUP_GLUTES = 9,
  MUSCLE_GROUP_ABDUCTORS = 10,
  MUSCLE_GROUP_ADDUCTORS = 11,
  MUSCLE_GROUP_LATS = 12,
  MUSCLE_GROUP_UPPER_BACK = 13,
  MUSCLE_GROUP_TRAPS = 14,
  MUSCLE_GROUP_LOWER_BACK = 15,
  MUSCLE_GROUP_CHEST = 16,
  MUSCLE_GROUP_CARDIO = 17,
  MUSCLE_GROUP_NECK = 18,
  MUSCLE_GROUP_FULL_BODY = 19,
  MUSCLE_GROUP_OTHER = 20,
  UNRECOGNIZED = -1,
}

/**
 * StandardizedActivity represents a normalized fitness activity.
 * It is designed to be the canonical input format for the Enricher,
 * decoupling it from specific ingestion sources (Hevy, etc).
 *
 * Structure mimics the FIT SDK hierarchy:
 * Activity -> Sessions -> Laps -> Records
 */
export interface StandardizedActivity {
  /** e.g. "HEVY" */
  source: string;
  /** Source's ID (e.g. Hevy workout ID) */
  externalId: string;
  userId: string;
  /** High-level summary */
  startTime: string;
  /** e.g. "Morning Run" */
  name: string;
  /** e.g. "RUNNING", "CYCLING", "WEIGHT_TRAINING" */
  type: string;
  /** Hierarchy */
  sessions: Session[];
  /** Rich metadata (preserved from source) */
  description: string;
  tags: string[];
  notes: string;
}

export interface Session {
  startTime: string;
  /** seconds */
  totalElapsedTime: number;
  /** meters */
  totalDistance: number;
  laps: Lap[];
  /** High-fidelity strength data (not just 1Hz streams) */
  strengthSets: StrengthSet[];
}

export interface Lap {
  startTime: string;
  /** seconds */
  totalElapsedTime: number;
  /** meters */
  totalDistance: number;
  records: Record[];
}

/** Record represents a single data point in time (1Hz is typical) */
export interface Record {
  /** ISO 8601 */
  timestamp: string;
  /** Core Telemetry */
  heartRate: number;
  /** watts */
  power: number;
  /** rpm */
  cadence: number;
  /** m/s */
  speed: number;
  /** meters */
  altitude: number;
  /** Location */
  positionLat: number;
  positionLong: number;
}

/**
 * StrengthSet represents a discrete set of an exercise (common in weightlifting)
 * This is distinct from continuous Record streams.
 */
export interface StrengthSet {
  /** e.g. "Bench Press" */
  exerciseName: string;
  reps: number;
  weightKg: number;
  /** ISO 8601 */
  startTime: string;
  durationSeconds: number;
  notes: string;
  /** Organization */
  supersetId: string;
  /** Muscle Targeting */
  primaryMuscleGroup: MuscleGroup;
  secondaryMuscleGroups: MuscleGroup[];
  /** Distance (for cardio/distance-based exercises) */
  distanceMeters: number;
  /** Set Type (warmup, normal, failure, dropset) */
  setType: string;
}
