// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.10.0
//   protoc               v6.33.2
// source: user.proto

/* eslint-disable */

export const protobufPackage = "fitglue";

export interface UserRecord {
  userId: string;
  createdAt: Date | undefined;
  integrations:
    | UserIntegrations
    | undefined;
  /** Pipelines define the data flow: Source -> Enrichers -> Routing */
  pipelines: PipelineConfig[];
}

export interface PipelineConfig {
  /** Unique ID (uuid) for tracing */
  id: string;
  /** e.g. "SOURCE_HEVY" */
  source: string;
  enrichers: EnricherConfig[];
  /** e.g. ["strava", "gcs"] */
  destinations: string[];
}

export interface UserIntegrations {
  hevy: HevyIntegration | undefined;
  fitbit: FitbitIntegration | undefined;
  strava: StravaIntegration | undefined;
  keiser: KeiserIntegration | undefined;
}

export interface HevyIntegration {
  enabled: boolean;
  apiKey: string;
  userId: string;
}

export interface FitbitIntegration {
  enabled: boolean;
  accessToken: string;
  refreshToken: string;
  expiresAt: Date | undefined;
  fitbitUserId: string;
}

export interface SourceEnrichmentConfig {
  enrichers: EnricherConfig[];
}

export interface EnricherConfig {
  /** e.g. "ai-description", "fitbit-hr" */
  name: string;
  /** e.g. {"prompt_style": "funny", "priority": "high"} */
  inputs: { [key: string]: string };
}

export interface EnricherConfig_InputsEntry {
  key: string;
  value: string;
}

export interface StravaIntegration {
  enabled: boolean;
  accessToken: string;
  refreshToken: string;
  expiresAt: Date | undefined;
  athleteId: number;
}

export interface KeiserIntegration {
  enabled: boolean;
  /** 'email', 'facebook', 'google', 'apple' */
  authProvider: string;
  refreshToken: string;
  refreshTokenExpiresAt:
    | Date
    | undefined;
  /** Only for 'email' provider (AES-256-GCM encrypted JSON) */
  encryptedCredentials: string;
  /** Set to true when OAuth token expires and cannot auto-refresh */
  requiresReauth: boolean;
}
