// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.10.0
//   protoc               v6.33.2
// source: user.proto

/* eslint-disable */

export const protobufPackage = "fitglue";

export enum EnricherProviderType {
  ENRICHER_PROVIDER_UNSPECIFIED = 0,
  ENRICHER_PROVIDER_FITBIT_HEART_RATE = 1,
  ENRICHER_PROVIDER_WORKOUT_SUMMARY = 2,
  ENRICHER_PROVIDER_MUSCLE_HEATMAP = 3,
  ENRICHER_PROVIDER_SOURCE_LINK = 4,
  ENRICHER_PROVIDER_METADATA_PASSTHROUGH = 5,
  ENRICHER_PROVIDER_VIRTUAL_GPS = 6,
  ENRICHER_PROVIDER_MOCK = 99,
  UNRECOGNIZED = -1,
}

export interface UserRecord {
  userId: string;
  createdAt: Date | undefined;
  integrations:
    | UserIntegrations
    | undefined;
  /** Pipelines define the data flow: Source -> Enrichers -> Routing */
  pipelines: PipelineConfig[];
}

export interface PipelineConfig {
  /** Unique ID (uuid) for tracing */
  id: string;
  /** e.g. "SOURCE_HEVY" */
  source: string;
  enrichers: EnricherConfig[];
  /** e.g. ["strava", "gcs"] */
  destinations: string[];
}

export interface UserIntegrations {
  hevy: HevyIntegration | undefined;
  fitbit: FitbitIntegration | undefined;
  strava: StravaIntegration | undefined;
}

export interface HevyIntegration {
  enabled: boolean;
  apiKey: string;
  userId: string;
}

export interface FitbitIntegration {
  enabled: boolean;
  accessToken: string;
  refreshToken: string;
  expiresAt: Date | undefined;
  fitbitUserId: string;
}

export interface SourceEnrichmentConfig {
  enrichers: EnricherConfig[];
}

export interface EnricherConfig {
  /** Use strictly typed provider enum instead of string name */
  providerType: EnricherProviderType;
  inputs: { [key: string]: string };
}

export interface EnricherConfig_InputsEntry {
  key: string;
  value: string;
}

export interface StravaIntegration {
  enabled: boolean;
  accessToken: string;
  refreshToken: string;
  expiresAt: Date | undefined;
  athleteId: number;
}
