// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.10.0
//   protoc               v6.33.2
// source: user.proto

/* eslint-disable */
import type { Destination } from "./events";
import type { ActivityType } from "./standardized_activity";

export const protobufPackage = "fitglue";

export enum EnricherProviderType {
  ENRICHER_PROVIDER_UNSPECIFIED = 0,
  ENRICHER_PROVIDER_FITBIT_HEART_RATE = 1,
  /** ENRICHER_PROVIDER_WORKOUT_SUMMARY - Config inputs: "format" (compact/detailed/verbose), "show_stats" ("true"/"false") */
  ENRICHER_PROVIDER_WORKOUT_SUMMARY = 2,
  ENRICHER_PROVIDER_MUSCLE_HEATMAP = 3,
  ENRICHER_PROVIDER_SOURCE_LINK = 4,
  ENRICHER_PROVIDER_METADATA_PASSTHROUGH = 5,
  ENRICHER_PROVIDER_VIRTUAL_GPS = 6,
  ENRICHER_PROVIDER_TYPE_MAPPER = 7,
  ENRICHER_PROVIDER_PARKRUN = 8,
  ENRICHER_PROVIDER_CONDITION_MATCHER = 9,
  ENRICHER_PROVIDER_AUTO_INCREMENT = 10,
  ENRICHER_PROVIDER_USER_INPUT = 11,
  /** ENRICHER_PROVIDER_ACTIVITY_FILTER - Config inputs: "exclude_activity_types" (comma-separated), "exclude_title_contains" (string) */
  ENRICHER_PROVIDER_ACTIVITY_FILTER = 12,
  ENRICHER_PROVIDER_MOCK = 99,
  UNRECOGNIZED = -1,
}

/** Workout Summary format styles */
export enum WorkoutSummaryFormat {
  WORKOUT_SUMMARY_FORMAT_UNSPECIFIED = 0,
  /** WORKOUT_SUMMARY_FORMAT_COMPACT - "4×8@100kg" */
  WORKOUT_SUMMARY_FORMAT_COMPACT = 1,
  /** WORKOUT_SUMMARY_FORMAT_DETAILED - "4 sets × 8 reps @ 100.0kg" */
  WORKOUT_SUMMARY_FORMAT_DETAILED = 2,
  /** WORKOUT_SUMMARY_FORMAT_VERBOSE - "4 sets of 8 reps at 100.0 kilograms" */
  WORKOUT_SUMMARY_FORMAT_VERBOSE = 3,
  UNRECOGNIZED = -1,
}

/** Muscle Heatmap visualization styles */
export enum MuscleHeatmapStyle {
  MUSCLE_HEATMAP_STYLE_UNSPECIFIED = 0,
  /** MUSCLE_HEATMAP_STYLE_EMOJI_BARS - "🟪🟪🟪⬜⬜" */
  MUSCLE_HEATMAP_STYLE_EMOJI_BARS = 1,
  /** MUSCLE_HEATMAP_STYLE_PERCENTAGE - "Chest: 80%" */
  MUSCLE_HEATMAP_STYLE_PERCENTAGE = 2,
  /** MUSCLE_HEATMAP_STYLE_TEXT_ONLY - "High: Chest, Medium: Legs" */
  MUSCLE_HEATMAP_STYLE_TEXT_ONLY = 3,
  UNRECOGNIZED = -1,
}

/** Muscle Heatmap coefficient presets */
export enum MuscleHeatmapPreset {
  MUSCLE_HEATMAP_PRESET_UNSPECIFIED = 0,
  /** MUSCLE_HEATMAP_PRESET_STANDARD - Balanced coefficients */
  MUSCLE_HEATMAP_PRESET_STANDARD = 1,
  /** MUSCLE_HEATMAP_PRESET_POWERLIFTING - Emphasize compounds */
  MUSCLE_HEATMAP_PRESET_POWERLIFTING = 2,
  /** MUSCLE_HEATMAP_PRESET_BODYBUILDING - Emphasize isolation */
  MUSCLE_HEATMAP_PRESET_BODYBUILDING = 3,
  UNRECOGNIZED = -1,
}

/** Virtual GPS route options */
export enum VirtualGPSRoute {
  VIRTUAL_GPS_ROUTE_UNSPECIFIED = 0,
  /** VIRTUAL_GPS_ROUTE_LONDON - London Hyde Park (~4km) */
  VIRTUAL_GPS_ROUTE_LONDON = 1,
  /** VIRTUAL_GPS_ROUTE_NYC - NYC Central Park (~10km) */
  VIRTUAL_GPS_ROUTE_NYC = 2,
  UNRECOGNIZED = -1,
}

export interface UserRecord {
  userId: string;
  createdAt?: Date | undefined;
  integrations?:
    | UserIntegrations
    | undefined;
  /** Pipelines define the data flow: Source -> Enrichers -> Routing */
  pipelines: PipelineConfig[];
  fcmTokens: string[];
}

export interface PipelineConfig {
  /** Unique ID (uuid) for tracing */
  id: string;
  /** e.g. "SOURCE_HEVY" */
  source: string;
  enrichers: EnricherConfig[];
  destinations: Destination[];
}

export interface UserIntegrations {
  hevy?: HevyIntegration | undefined;
  fitbit?: FitbitIntegration | undefined;
  strava?: StravaIntegration | undefined;
  mock?: MockIntegration | undefined;
}

export interface MockIntegration {
  enabled: boolean;
  createdAt?: Date | undefined;
  lastUsedAt?: Date | undefined;
}

export interface HevyIntegration {
  enabled: boolean;
  apiKey: string;
  userId: string;
  createdAt?: Date | undefined;
  lastUsedAt?: Date | undefined;
}

export interface FitbitIntegration {
  enabled: boolean;
  accessToken: string;
  refreshToken: string;
  expiresAt?: Date | undefined;
  fitbitUserId: string;
  createdAt?: Date | undefined;
  lastUsedAt?: Date | undefined;
}

export interface SourceEnrichmentConfig {
  enrichers: EnricherConfig[];
}

export interface EnricherConfig {
  /** Use strictly typed provider enum instead of string name */
  providerType: EnricherProviderType;
  inputs: { [key: string]: string };
}

export interface EnricherConfig_InputsEntry {
  key: string;
  value: string;
}

export interface StravaIntegration {
  enabled: boolean;
  accessToken: string;
  refreshToken: string;
  expiresAt?: Date | undefined;
  athleteId: number;
  createdAt?: Date | undefined;
  lastUsedAt?: Date | undefined;
}

export interface ProcessedActivityRecord {
  source: string;
  /** Unique ID from provider */
  externalId: string;
  processedAt?: Date | undefined;
}

export interface Counter {
  /** Key, e.g. "parkrun_bushy" */
  id: string;
  count: number;
  lastUpdated?: Date | undefined;
}

export interface SynchronizedActivity {
  activityId: string;
  title: string;
  description: string;
  type: ActivityType;
  /** e.g. "SOURCE_HEVY" */
  source: string;
  startTime?:
    | Date
    | undefined;
  /** destination -> external_id */
  destinations: { [key: string]: string };
  syncedAt?: Date | undefined;
  pipelineId: string;
  pipelineExecutionId: string;
}

export interface SynchronizedActivity_DestinationsEntry {
  key: string;
  value: string;
}
