// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.10.0
//   protoc               v6.33.4
// source: waitlist.proto

/* eslint-disable */

export const protobufPackage = "fitglue";

export interface WaitlistEntry {
  email: string;
  /** e.g. "web" */
  source: string;
  createdAt?: Date | undefined;
  userAgent: string;
  ip: string;
}
