// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.8.3
//   protoc               v4.25.2
// source: proto/activity.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "fitglue";

/** ActivitySource enum defines where the data originated. */
export enum ActivitySource {
  SOURCE_UNKNOWN = 0,
  SOURCE_HEVY = 1,
  SOURCE_KEISER = 2,
  SOURCE_TEST = 3,
  UNRECOGNIZED = -1,
}

export function activitySourceFromJSON(object: any): ActivitySource {
  switch (object) {
    case 0:
    case "SOURCE_UNKNOWN":
      return ActivitySource.SOURCE_UNKNOWN;
    case 1:
    case "SOURCE_HEVY":
      return ActivitySource.SOURCE_HEVY;
    case 2:
    case "SOURCE_KEISER":
      return ActivitySource.SOURCE_KEISER;
    case 3:
    case "SOURCE_TEST":
      return ActivitySource.SOURCE_TEST;
    case -1:
    case "UNRECOGNIZED":
    default:
      return ActivitySource.UNRECOGNIZED;
  }
}

export function activitySourceToJSON(object: ActivitySource): string {
  switch (object) {
    case ActivitySource.SOURCE_UNKNOWN:
      return "SOURCE_UNKNOWN";
    case ActivitySource.SOURCE_HEVY:
      return "SOURCE_HEVY";
    case ActivitySource.SOURCE_KEISER:
      return "SOURCE_KEISER";
    case ActivitySource.SOURCE_TEST:
      return "SOURCE_TEST";
    case ActivitySource.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

/** ActivityPayload is the unified message format published to Pub/Sub. */
export interface ActivityPayload {
  source: ActivitySource;
  /** Internal FitGlue User ID */
  userId: string;
  /** ISO 8601 Timestamp of activity start */
  timestamp: string;
  /** Raw JSON payload stringified (flexible but preserved) */
  originalPayloadJson: string;
  /** Extra tracing context */
  metadata: { [key: string]: string };
}

export interface ActivityPayload_MetadataEntry {
  key: string;
  value: string;
}

/** EnrichedActivityEvent is the message format for topic-enriched-activity. */
export interface EnrichedActivityEvent {
  userId: string;
  /** Unique ID for the processed activity */
  activityId: string;
  /** Path to the generated FIT file */
  gcsUri: string;
  /** Generated description/hashtags */
  description: string;
  /** Extra stats */
  metadataJson: string;
}

function createBaseActivityPayload(): ActivityPayload {
  return { source: 0, userId: "", timestamp: "", originalPayloadJson: "", metadata: {} };
}

export const ActivityPayload: MessageFns<ActivityPayload> = {
  encode(message: ActivityPayload, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.source !== 0) {
      writer.uint32(8).int32(message.source);
    }
    if (message.userId !== "") {
      writer.uint32(18).string(message.userId);
    }
    if (message.timestamp !== "") {
      writer.uint32(26).string(message.timestamp);
    }
    if (message.originalPayloadJson !== "") {
      writer.uint32(34).string(message.originalPayloadJson);
    }
    Object.entries(message.metadata).forEach(([key, value]) => {
      ActivityPayload_MetadataEntry.encode({ key: key as any, value }, writer.uint32(42).fork()).join();
    });
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ActivityPayload {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseActivityPayload();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.source = reader.int32() as any;
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.userId = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.timestamp = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.originalPayloadJson = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          const entry5 = ActivityPayload_MetadataEntry.decode(reader, reader.uint32());
          if (entry5.value !== undefined) {
            message.metadata[entry5.key] = entry5.value;
          }
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ActivityPayload {
    return {
      source: isSet(object.source) ? activitySourceFromJSON(object.source) : 0,
      userId: isSet(object.userId) ? globalThis.String(object.userId) : "",
      timestamp: isSet(object.timestamp) ? globalThis.String(object.timestamp) : "",
      originalPayloadJson: isSet(object.originalPayloadJson) ? globalThis.String(object.originalPayloadJson) : "",
      metadata: isObject(object.metadata)
        ? Object.entries(object.metadata).reduce<{ [key: string]: string }>((acc, [key, value]) => {
          acc[key] = String(value);
          return acc;
        }, {})
        : {},
    };
  },

  toJSON(message: ActivityPayload): unknown {
    const obj: any = {};
    if (message.source !== 0) {
      obj.source = activitySourceToJSON(message.source);
    }
    if (message.userId !== "") {
      obj.userId = message.userId;
    }
    if (message.timestamp !== "") {
      obj.timestamp = message.timestamp;
    }
    if (message.originalPayloadJson !== "") {
      obj.originalPayloadJson = message.originalPayloadJson;
    }
    if (message.metadata) {
      const entries = Object.entries(message.metadata);
      if (entries.length > 0) {
        obj.metadata = {};
        entries.forEach(([k, v]) => {
          obj.metadata[k] = v;
        });
      }
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ActivityPayload>, I>>(base?: I): ActivityPayload {
    return ActivityPayload.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ActivityPayload>, I>>(object: I): ActivityPayload {
    const message = createBaseActivityPayload();
    message.source = object.source ?? 0;
    message.userId = object.userId ?? "";
    message.timestamp = object.timestamp ?? "";
    message.originalPayloadJson = object.originalPayloadJson ?? "";
    message.metadata = Object.entries(object.metadata ?? {}).reduce<{ [key: string]: string }>((acc, [key, value]) => {
      if (value !== undefined) {
        acc[key] = globalThis.String(value);
      }
      return acc;
    }, {});
    return message;
  },
};

function createBaseActivityPayload_MetadataEntry(): ActivityPayload_MetadataEntry {
  return { key: "", value: "" };
}

export const ActivityPayload_MetadataEntry: MessageFns<ActivityPayload_MetadataEntry> = {
  encode(message: ActivityPayload_MetadataEntry, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.key !== "") {
      writer.uint32(10).string(message.key);
    }
    if (message.value !== "") {
      writer.uint32(18).string(message.value);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ActivityPayload_MetadataEntry {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseActivityPayload_MetadataEntry();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.key = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.value = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ActivityPayload_MetadataEntry {
    return {
      key: isSet(object.key) ? globalThis.String(object.key) : "",
      value: isSet(object.value) ? globalThis.String(object.value) : "",
    };
  },

  toJSON(message: ActivityPayload_MetadataEntry): unknown {
    const obj: any = {};
    if (message.key !== "") {
      obj.key = message.key;
    }
    if (message.value !== "") {
      obj.value = message.value;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ActivityPayload_MetadataEntry>, I>>(base?: I): ActivityPayload_MetadataEntry {
    return ActivityPayload_MetadataEntry.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ActivityPayload_MetadataEntry>, I>>(
    object: I,
  ): ActivityPayload_MetadataEntry {
    const message = createBaseActivityPayload_MetadataEntry();
    message.key = object.key ?? "";
    message.value = object.value ?? "";
    return message;
  },
};

function createBaseEnrichedActivityEvent(): EnrichedActivityEvent {
  return { userId: "", activityId: "", gcsUri: "", description: "", metadataJson: "" };
}

export const EnrichedActivityEvent: MessageFns<EnrichedActivityEvent> = {
  encode(message: EnrichedActivityEvent, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.userId !== "") {
      writer.uint32(10).string(message.userId);
    }
    if (message.activityId !== "") {
      writer.uint32(18).string(message.activityId);
    }
    if (message.gcsUri !== "") {
      writer.uint32(26).string(message.gcsUri);
    }
    if (message.description !== "") {
      writer.uint32(34).string(message.description);
    }
    if (message.metadataJson !== "") {
      writer.uint32(42).string(message.metadataJson);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): EnrichedActivityEvent {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseEnrichedActivityEvent();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.userId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.activityId = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.gcsUri = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.description = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.metadataJson = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): EnrichedActivityEvent {
    return {
      userId: isSet(object.userId) ? globalThis.String(object.userId) : "",
      activityId: isSet(object.activityId) ? globalThis.String(object.activityId) : "",
      gcsUri: isSet(object.gcsUri) ? globalThis.String(object.gcsUri) : "",
      description: isSet(object.description) ? globalThis.String(object.description) : "",
      metadataJson: isSet(object.metadataJson) ? globalThis.String(object.metadataJson) : "",
    };
  },

  toJSON(message: EnrichedActivityEvent): unknown {
    const obj: any = {};
    if (message.userId !== "") {
      obj.userId = message.userId;
    }
    if (message.activityId !== "") {
      obj.activityId = message.activityId;
    }
    if (message.gcsUri !== "") {
      obj.gcsUri = message.gcsUri;
    }
    if (message.description !== "") {
      obj.description = message.description;
    }
    if (message.metadataJson !== "") {
      obj.metadataJson = message.metadataJson;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<EnrichedActivityEvent>, I>>(base?: I): EnrichedActivityEvent {
    return EnrichedActivityEvent.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<EnrichedActivityEvent>, I>>(object: I): EnrichedActivityEvent {
    const message = createBaseEnrichedActivityEvent();
    message.userId = object.userId ?? "";
    message.activityId = object.activityId ?? "";
    message.gcsUri = object.gcsUri ?? "";
    message.description = object.description ?? "";
    message.metadataJson = object.metadataJson ?? "";
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isObject(value: any): boolean {
  return typeof value === "object" && value !== null;
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
