"use strict";
// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.8.3
//   protoc               v4.25.2
// source: proto/activity.proto
Object.defineProperty(exports, "__esModule", { value: true });
exports.EnrichedActivityEvent = exports.ActivityPayload_MetadataEntry = exports.ActivityPayload = exports.ActivitySource = exports.protobufPackage = void 0;
exports.activitySourceFromJSON = activitySourceFromJSON;
exports.activitySourceToJSON = activitySourceToJSON;
/* eslint-disable */
const wire_1 = require("@bufbuild/protobuf/wire");
exports.protobufPackage = "fitglue";
/** ActivitySource enum defines where the data originated. */
var ActivitySource;
(function (ActivitySource) {
    ActivitySource[ActivitySource["SOURCE_UNKNOWN"] = 0] = "SOURCE_UNKNOWN";
    ActivitySource[ActivitySource["SOURCE_HEVY"] = 1] = "SOURCE_HEVY";
    ActivitySource[ActivitySource["SOURCE_KEISER"] = 2] = "SOURCE_KEISER";
    ActivitySource[ActivitySource["SOURCE_TEST"] = 3] = "SOURCE_TEST";
    ActivitySource[ActivitySource["UNRECOGNIZED"] = -1] = "UNRECOGNIZED";
})(ActivitySource || (exports.ActivitySource = ActivitySource = {}));
function activitySourceFromJSON(object) {
    switch (object) {
        case 0:
        case "SOURCE_UNKNOWN":
            return ActivitySource.SOURCE_UNKNOWN;
        case 1:
        case "SOURCE_HEVY":
            return ActivitySource.SOURCE_HEVY;
        case 2:
        case "SOURCE_KEISER":
            return ActivitySource.SOURCE_KEISER;
        case 3:
        case "SOURCE_TEST":
            return ActivitySource.SOURCE_TEST;
        case -1:
        case "UNRECOGNIZED":
        default:
            return ActivitySource.UNRECOGNIZED;
    }
}
function activitySourceToJSON(object) {
    switch (object) {
        case ActivitySource.SOURCE_UNKNOWN:
            return "SOURCE_UNKNOWN";
        case ActivitySource.SOURCE_HEVY:
            return "SOURCE_HEVY";
        case ActivitySource.SOURCE_KEISER:
            return "SOURCE_KEISER";
        case ActivitySource.SOURCE_TEST:
            return "SOURCE_TEST";
        case ActivitySource.UNRECOGNIZED:
        default:
            return "UNRECOGNIZED";
    }
}
function createBaseActivityPayload() {
    return { source: 0, userId: "", timestamp: "", originalPayloadJson: "", metadata: {} };
}
exports.ActivityPayload = {
    encode(message, writer = new wire_1.BinaryWriter()) {
        if (message.source !== 0) {
            writer.uint32(8).int32(message.source);
        }
        if (message.userId !== "") {
            writer.uint32(18).string(message.userId);
        }
        if (message.timestamp !== "") {
            writer.uint32(26).string(message.timestamp);
        }
        if (message.originalPayloadJson !== "") {
            writer.uint32(34).string(message.originalPayloadJson);
        }
        Object.entries(message.metadata).forEach(([key, value]) => {
            exports.ActivityPayload_MetadataEntry.encode({ key: key, value }, writer.uint32(42).fork()).join();
        });
        return writer;
    },
    decode(input, length) {
        const reader = input instanceof wire_1.BinaryReader ? input : new wire_1.BinaryReader(input);
        const end = length === undefined ? reader.len : reader.pos + length;
        const message = createBaseActivityPayload();
        while (reader.pos < end) {
            const tag = reader.uint32();
            switch (tag >>> 3) {
                case 1: {
                    if (tag !== 8) {
                        break;
                    }
                    message.source = reader.int32();
                    continue;
                }
                case 2: {
                    if (tag !== 18) {
                        break;
                    }
                    message.userId = reader.string();
                    continue;
                }
                case 3: {
                    if (tag !== 26) {
                        break;
                    }
                    message.timestamp = reader.string();
                    continue;
                }
                case 4: {
                    if (tag !== 34) {
                        break;
                    }
                    message.originalPayloadJson = reader.string();
                    continue;
                }
                case 5: {
                    if (tag !== 42) {
                        break;
                    }
                    const entry5 = exports.ActivityPayload_MetadataEntry.decode(reader, reader.uint32());
                    if (entry5.value !== undefined) {
                        message.metadata[entry5.key] = entry5.value;
                    }
                    continue;
                }
            }
            if ((tag & 7) === 4 || tag === 0) {
                break;
            }
            reader.skip(tag & 7);
        }
        return message;
    },
    fromJSON(object) {
        return {
            source: isSet(object.source) ? activitySourceFromJSON(object.source) : 0,
            userId: isSet(object.userId) ? globalThis.String(object.userId) : "",
            timestamp: isSet(object.timestamp) ? globalThis.String(object.timestamp) : "",
            originalPayloadJson: isSet(object.originalPayloadJson) ? globalThis.String(object.originalPayloadJson) : "",
            metadata: isObject(object.metadata)
                ? Object.entries(object.metadata).reduce((acc, [key, value]) => {
                    acc[key] = String(value);
                    return acc;
                }, {})
                : {},
        };
    },
    toJSON(message) {
        const obj = {};
        if (message.source !== 0) {
            obj.source = activitySourceToJSON(message.source);
        }
        if (message.userId !== "") {
            obj.userId = message.userId;
        }
        if (message.timestamp !== "") {
            obj.timestamp = message.timestamp;
        }
        if (message.originalPayloadJson !== "") {
            obj.originalPayloadJson = message.originalPayloadJson;
        }
        if (message.metadata) {
            const entries = Object.entries(message.metadata);
            if (entries.length > 0) {
                obj.metadata = {};
                entries.forEach(([k, v]) => {
                    obj.metadata[k] = v;
                });
            }
        }
        return obj;
    },
    create(base) {
        return exports.ActivityPayload.fromPartial(base ?? {});
    },
    fromPartial(object) {
        const message = createBaseActivityPayload();
        message.source = object.source ?? 0;
        message.userId = object.userId ?? "";
        message.timestamp = object.timestamp ?? "";
        message.originalPayloadJson = object.originalPayloadJson ?? "";
        message.metadata = Object.entries(object.metadata ?? {}).reduce((acc, [key, value]) => {
            if (value !== undefined) {
                acc[key] = globalThis.String(value);
            }
            return acc;
        }, {});
        return message;
    },
};
function createBaseActivityPayload_MetadataEntry() {
    return { key: "", value: "" };
}
exports.ActivityPayload_MetadataEntry = {
    encode(message, writer = new wire_1.BinaryWriter()) {
        if (message.key !== "") {
            writer.uint32(10).string(message.key);
        }
        if (message.value !== "") {
            writer.uint32(18).string(message.value);
        }
        return writer;
    },
    decode(input, length) {
        const reader = input instanceof wire_1.BinaryReader ? input : new wire_1.BinaryReader(input);
        const end = length === undefined ? reader.len : reader.pos + length;
        const message = createBaseActivityPayload_MetadataEntry();
        while (reader.pos < end) {
            const tag = reader.uint32();
            switch (tag >>> 3) {
                case 1: {
                    if (tag !== 10) {
                        break;
                    }
                    message.key = reader.string();
                    continue;
                }
                case 2: {
                    if (tag !== 18) {
                        break;
                    }
                    message.value = reader.string();
                    continue;
                }
            }
            if ((tag & 7) === 4 || tag === 0) {
                break;
            }
            reader.skip(tag & 7);
        }
        return message;
    },
    fromJSON(object) {
        return {
            key: isSet(object.key) ? globalThis.String(object.key) : "",
            value: isSet(object.value) ? globalThis.String(object.value) : "",
        };
    },
    toJSON(message) {
        const obj = {};
        if (message.key !== "") {
            obj.key = message.key;
        }
        if (message.value !== "") {
            obj.value = message.value;
        }
        return obj;
    },
    create(base) {
        return exports.ActivityPayload_MetadataEntry.fromPartial(base ?? {});
    },
    fromPartial(object) {
        const message = createBaseActivityPayload_MetadataEntry();
        message.key = object.key ?? "";
        message.value = object.value ?? "";
        return message;
    },
};
function createBaseEnrichedActivityEvent() {
    return { userId: "", activityId: "", gcsUri: "", description: "", metadataJson: "" };
}
exports.EnrichedActivityEvent = {
    encode(message, writer = new wire_1.BinaryWriter()) {
        if (message.userId !== "") {
            writer.uint32(10).string(message.userId);
        }
        if (message.activityId !== "") {
            writer.uint32(18).string(message.activityId);
        }
        if (message.gcsUri !== "") {
            writer.uint32(26).string(message.gcsUri);
        }
        if (message.description !== "") {
            writer.uint32(34).string(message.description);
        }
        if (message.metadataJson !== "") {
            writer.uint32(42).string(message.metadataJson);
        }
        return writer;
    },
    decode(input, length) {
        const reader = input instanceof wire_1.BinaryReader ? input : new wire_1.BinaryReader(input);
        const end = length === undefined ? reader.len : reader.pos + length;
        const message = createBaseEnrichedActivityEvent();
        while (reader.pos < end) {
            const tag = reader.uint32();
            switch (tag >>> 3) {
                case 1: {
                    if (tag !== 10) {
                        break;
                    }
                    message.userId = reader.string();
                    continue;
                }
                case 2: {
                    if (tag !== 18) {
                        break;
                    }
                    message.activityId = reader.string();
                    continue;
                }
                case 3: {
                    if (tag !== 26) {
                        break;
                    }
                    message.gcsUri = reader.string();
                    continue;
                }
                case 4: {
                    if (tag !== 34) {
                        break;
                    }
                    message.description = reader.string();
                    continue;
                }
                case 5: {
                    if (tag !== 42) {
                        break;
                    }
                    message.metadataJson = reader.string();
                    continue;
                }
            }
            if ((tag & 7) === 4 || tag === 0) {
                break;
            }
            reader.skip(tag & 7);
        }
        return message;
    },
    fromJSON(object) {
        return {
            userId: isSet(object.userId) ? globalThis.String(object.userId) : "",
            activityId: isSet(object.activityId) ? globalThis.String(object.activityId) : "",
            gcsUri: isSet(object.gcsUri) ? globalThis.String(object.gcsUri) : "",
            description: isSet(object.description) ? globalThis.String(object.description) : "",
            metadataJson: isSet(object.metadataJson) ? globalThis.String(object.metadataJson) : "",
        };
    },
    toJSON(message) {
        const obj = {};
        if (message.userId !== "") {
            obj.userId = message.userId;
        }
        if (message.activityId !== "") {
            obj.activityId = message.activityId;
        }
        if (message.gcsUri !== "") {
            obj.gcsUri = message.gcsUri;
        }
        if (message.description !== "") {
            obj.description = message.description;
        }
        if (message.metadataJson !== "") {
            obj.metadataJson = message.metadataJson;
        }
        return obj;
    },
    create(base) {
        return exports.EnrichedActivityEvent.fromPartial(base ?? {});
    },
    fromPartial(object) {
        const message = createBaseEnrichedActivityEvent();
        message.userId = object.userId ?? "";
        message.activityId = object.activityId ?? "";
        message.gcsUri = object.gcsUri ?? "";
        message.description = object.description ?? "";
        message.metadataJson = object.metadataJson ?? "";
        return message;
    },
};
function isObject(value) {
    return typeof value === "object" && value !== null;
}
function isSet(value) {
    return value !== null && value !== undefined;
}
