// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.2
// source: proto/activity.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ActivitySource enum defines where the data originated.
type ActivitySource int32

const (
	ActivitySource_SOURCE_UNKNOWN ActivitySource = 0
	ActivitySource_SOURCE_HEVY    ActivitySource = 1
	ActivitySource_SOURCE_KEISER  ActivitySource = 2
	ActivitySource_SOURCE_TEST    ActivitySource = 3
)

// Enum value maps for ActivitySource.
var (
	ActivitySource_name = map[int32]string{
		0: "SOURCE_UNKNOWN",
		1: "SOURCE_HEVY",
		2: "SOURCE_KEISER",
		3: "SOURCE_TEST",
	}
	ActivitySource_value = map[string]int32{
		"SOURCE_UNKNOWN": 0,
		"SOURCE_HEVY":    1,
		"SOURCE_KEISER":  2,
		"SOURCE_TEST":    3,
	}
)

func (x ActivitySource) Enum() *ActivitySource {
	p := new(ActivitySource)
	*p = x
	return p
}

func (x ActivitySource) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ActivitySource) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_activity_proto_enumTypes[0].Descriptor()
}

func (ActivitySource) Type() protoreflect.EnumType {
	return &file_proto_activity_proto_enumTypes[0]
}

func (x ActivitySource) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ActivitySource.Descriptor instead.
func (ActivitySource) EnumDescriptor() ([]byte, []int) {
	return file_proto_activity_proto_rawDescGZIP(), []int{0}
}

// ActivityPayload is the unified message format published to Pub/Sub.
type ActivityPayload struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Source              ActivitySource         `protobuf:"varint,1,opt,name=source,proto3,enum=fitglue.ActivitySource" json:"source,omitempty"`
	UserId              string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`                                                                 // Internal FitGlue User ID
	Timestamp           string                 `protobuf:"bytes,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`                                                                         // ISO 8601 Timestamp of activity start
	OriginalPayloadJson string                 `protobuf:"bytes,4,opt,name=original_payload_json,json=originalPayloadJson,proto3" json:"original_payload_json,omitempty"`                        // Raw JSON payload stringified (flexible but preserved)
	Metadata            map[string]string      `protobuf:"bytes,5,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // Extra tracing context
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *ActivityPayload) Reset() {
	*x = ActivityPayload{}
	mi := &file_proto_activity_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActivityPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActivityPayload) ProtoMessage() {}

func (x *ActivityPayload) ProtoReflect() protoreflect.Message {
	mi := &file_proto_activity_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActivityPayload.ProtoReflect.Descriptor instead.
func (*ActivityPayload) Descriptor() ([]byte, []int) {
	return file_proto_activity_proto_rawDescGZIP(), []int{0}
}

func (x *ActivityPayload) GetSource() ActivitySource {
	if x != nil {
		return x.Source
	}
	return ActivitySource_SOURCE_UNKNOWN
}

func (x *ActivityPayload) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ActivityPayload) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

func (x *ActivityPayload) GetOriginalPayloadJson() string {
	if x != nil {
		return x.OriginalPayloadJson
	}
	return ""
}

func (x *ActivityPayload) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// EnrichedActivityEvent is the message format for topic-enriched-activity.
type EnrichedActivityEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ActivityId    string                 `protobuf:"bytes,2,opt,name=activity_id,json=activityId,proto3" json:"activity_id,omitempty"`       // Unique ID for the processed activity
	GcsUri        string                 `protobuf:"bytes,3,opt,name=gcs_uri,json=gcsUri,proto3" json:"gcs_uri,omitempty"`                   // Path to the generated FIT file
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`                       // Generated description/hashtags
	MetadataJson  string                 `protobuf:"bytes,5,opt,name=metadata_json,json=metadataJson,proto3" json:"metadata_json,omitempty"` // Extra stats
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnrichedActivityEvent) Reset() {
	*x = EnrichedActivityEvent{}
	mi := &file_proto_activity_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnrichedActivityEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnrichedActivityEvent) ProtoMessage() {}

func (x *EnrichedActivityEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_activity_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnrichedActivityEvent.ProtoReflect.Descriptor instead.
func (*EnrichedActivityEvent) Descriptor() ([]byte, []int) {
	return file_proto_activity_proto_rawDescGZIP(), []int{1}
}

func (x *EnrichedActivityEvent) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *EnrichedActivityEvent) GetActivityId() string {
	if x != nil {
		return x.ActivityId
	}
	return ""
}

func (x *EnrichedActivityEvent) GetGcsUri() string {
	if x != nil {
		return x.GcsUri
	}
	return ""
}

func (x *EnrichedActivityEvent) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *EnrichedActivityEvent) GetMetadataJson() string {
	if x != nil {
		return x.MetadataJson
	}
	return ""
}

var File_proto_activity_proto protoreflect.FileDescriptor

const file_proto_activity_proto_rawDesc = "" +
	"\n" +
	"\x14proto/activity.proto\x12\afitglue\"\xae\x02\n" +
	"\x0fActivityPayload\x12/\n" +
	"\x06source\x18\x01 \x01(\x0e2\x17.fitglue.ActivitySourceR\x06source\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\tR\ttimestamp\x122\n" +
	"\x15original_payload_json\x18\x04 \x01(\tR\x13originalPayloadJson\x12B\n" +
	"\bmetadata\x18\x05 \x03(\v2&.fitglue.ActivityPayload.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xb1\x01\n" +
	"\x15EnrichedActivityEvent\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1f\n" +
	"\vactivity_id\x18\x02 \x01(\tR\n" +
	"activityId\x12\x17\n" +
	"\agcs_uri\x18\x03 \x01(\tR\x06gcsUri\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12#\n" +
	"\rmetadata_json\x18\x05 \x01(\tR\fmetadataJson*Y\n" +
	"\x0eActivitySource\x12\x12\n" +
	"\x0eSOURCE_UNKNOWN\x10\x00\x12\x0f\n" +
	"\vSOURCE_HEVY\x10\x01\x12\x11\n" +
	"\rSOURCE_KEISER\x10\x02\x12\x0f\n" +
	"\vSOURCE_TEST\x10\x03B\x17Z\x15fitglue/pkg/shared/pbb\x06proto3"

var (
	file_proto_activity_proto_rawDescOnce sync.Once
	file_proto_activity_proto_rawDescData []byte
)

func file_proto_activity_proto_rawDescGZIP() []byte {
	file_proto_activity_proto_rawDescOnce.Do(func() {
		file_proto_activity_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_activity_proto_rawDesc), len(file_proto_activity_proto_rawDesc)))
	})
	return file_proto_activity_proto_rawDescData
}

var file_proto_activity_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_activity_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proto_activity_proto_goTypes = []any{
	(ActivitySource)(0),           // 0: fitglue.ActivitySource
	(*ActivityPayload)(nil),       // 1: fitglue.ActivityPayload
	(*EnrichedActivityEvent)(nil), // 2: fitglue.EnrichedActivityEvent
	nil,                           // 3: fitglue.ActivityPayload.MetadataEntry
}
var file_proto_activity_proto_depIdxs = []int32{
	0, // 0: fitglue.ActivityPayload.source:type_name -> fitglue.ActivitySource
	3, // 1: fitglue.ActivityPayload.metadata:type_name -> fitglue.ActivityPayload.MetadataEntry
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_activity_proto_init() }
func file_proto_activity_proto_init() {
	if File_proto_activity_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_activity_proto_rawDesc), len(file_proto_activity_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_activity_proto_goTypes,
		DependencyIndexes: file_proto_activity_proto_depIdxs,
		EnumInfos:         file_proto_activity_proto_enumTypes,
		MessageInfos:      file_proto_activity_proto_msgTypes,
	}.Build()
	File_proto_activity_proto = out.File
	file_proto_activity_proto_goTypes = nil
	file_proto_activity_proto_depIdxs = nil
}
