// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.12.4
// source: activity.proto

package pb

import (
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ActivitySource enum defines where the data originated.
type ActivitySource int32

const (
	ActivitySource_SOURCE_UNKNOWN ActivitySource = 0
	ActivitySource_SOURCE_HEVY    ActivitySource = 1
	ActivitySource_SOURCE_FITBIT  ActivitySource = 3
	ActivitySource_SOURCE_TEST    ActivitySource = 99
)

// Enum value maps for ActivitySource.
var (
	ActivitySource_name = map[int32]string{
		0:  "SOURCE_UNKNOWN",
		1:  "SOURCE_HEVY",
		3:  "SOURCE_FITBIT",
		99: "SOURCE_TEST",
	}
	ActivitySource_value = map[string]int32{
		"SOURCE_UNKNOWN": 0,
		"SOURCE_HEVY":    1,
		"SOURCE_FITBIT":  3,
		"SOURCE_TEST":    99,
	}
)

func (x ActivitySource) Enum() *ActivitySource {
	p := new(ActivitySource)
	*p = x
	return p
}

func (x ActivitySource) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ActivitySource) Descriptor() protoreflect.EnumDescriptor {
	return file_activity_proto_enumTypes[0].Descriptor()
}

func (ActivitySource) Type() protoreflect.EnumType {
	return &file_activity_proto_enumTypes[0]
}

func (x ActivitySource) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ActivitySource.Descriptor instead.
func (ActivitySource) EnumDescriptor() ([]byte, []int) {
	return file_activity_proto_rawDescGZIP(), []int{0}
}

// ActivityPayload is the unified message format published to Pub/Sub.
type ActivityPayload struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Source               ActivitySource         `protobuf:"varint,1,opt,name=source,proto3,enum=fitglue.ActivitySource" json:"source,omitempty"`
	UserId               string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"` // Internal FitGlue User ID
	Timestamp            *timestamp.Timestamp   `protobuf:"bytes,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	OriginalPayloadJson  string                 `protobuf:"bytes,4,opt,name=original_payload_json,json=originalPayloadJson,proto3" json:"original_payload_json,omitempty"`                        // Raw JSON payload stringified (flexible but preserved)
	Metadata             map[string]string      `protobuf:"bytes,5,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // Extra tracing context
	StandardizedActivity *StandardizedActivity  `protobuf:"bytes,6,opt,name=standardized_activity,json=standardizedActivity,proto3" json:"standardized_activity,omitempty"`
	// Execution tracing
	PipelineExecutionId *string `protobuf:"bytes,7,opt,name=pipeline_execution_id,json=pipelineExecutionId,proto3,oneof" json:"pipeline_execution_id,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *ActivityPayload) Reset() {
	*x = ActivityPayload{}
	mi := &file_activity_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActivityPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActivityPayload) ProtoMessage() {}

func (x *ActivityPayload) ProtoReflect() protoreflect.Message {
	mi := &file_activity_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActivityPayload.ProtoReflect.Descriptor instead.
func (*ActivityPayload) Descriptor() ([]byte, []int) {
	return file_activity_proto_rawDescGZIP(), []int{0}
}

func (x *ActivityPayload) GetSource() ActivitySource {
	if x != nil {
		return x.Source
	}
	return ActivitySource_SOURCE_UNKNOWN
}

func (x *ActivityPayload) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ActivityPayload) GetTimestamp() *timestamp.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *ActivityPayload) GetOriginalPayloadJson() string {
	if x != nil {
		return x.OriginalPayloadJson
	}
	return ""
}

func (x *ActivityPayload) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *ActivityPayload) GetStandardizedActivity() *StandardizedActivity {
	if x != nil {
		return x.StandardizedActivity
	}
	return nil
}

func (x *ActivityPayload) GetPipelineExecutionId() string {
	if x != nil && x.PipelineExecutionId != nil {
		return *x.PipelineExecutionId
	}
	return ""
}

var File_activity_proto protoreflect.FileDescriptor

const file_activity_proto_rawDesc = "" +
	"\n" +
	"\x0eactivity.proto\x12\afitglue\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1bstandardized_activity.proto\"\xf1\x03\n" +
	"\x0fActivityPayload\x12/\n" +
	"\x06source\x18\x01 \x01(\x0e2\x17.fitglue.ActivitySourceR\x06source\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x128\n" +
	"\ttimestamp\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x122\n" +
	"\x15original_payload_json\x18\x04 \x01(\tR\x13originalPayloadJson\x12B\n" +
	"\bmetadata\x18\x05 \x03(\v2&.fitglue.ActivityPayload.MetadataEntryR\bmetadata\x12R\n" +
	"\x15standardized_activity\x18\x06 \x01(\v2\x1d.fitglue.StandardizedActivityR\x14standardizedActivity\x127\n" +
	"\x15pipeline_execution_id\x18\a \x01(\tH\x00R\x13pipelineExecutionId\x88\x01\x01\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\x18\n" +
	"\x16_pipeline_execution_id*Y\n" +
	"\x0eActivitySource\x12\x12\n" +
	"\x0eSOURCE_UNKNOWN\x10\x00\x12\x0f\n" +
	"\vSOURCE_HEVY\x10\x01\x12\x11\n" +
	"\rSOURCE_FITBIT\x10\x03\x12\x0f\n" +
	"\vSOURCE_TEST\x10cB7Z5github.com/ripixel/fitglue-server/src/go/pkg/types/pbb\x06proto3"

var (
	file_activity_proto_rawDescOnce sync.Once
	file_activity_proto_rawDescData []byte
)

func file_activity_proto_rawDescGZIP() []byte {
	file_activity_proto_rawDescOnce.Do(func() {
		file_activity_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_activity_proto_rawDesc), len(file_activity_proto_rawDesc)))
	})
	return file_activity_proto_rawDescData
}

var file_activity_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_activity_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_activity_proto_goTypes = []any{
	(ActivitySource)(0),          // 0: fitglue.ActivitySource
	(*ActivityPayload)(nil),      // 1: fitglue.ActivityPayload
	nil,                          // 2: fitglue.ActivityPayload.MetadataEntry
	(*timestamp.Timestamp)(nil),  // 3: google.protobuf.Timestamp
	(*StandardizedActivity)(nil), // 4: fitglue.StandardizedActivity
}
var file_activity_proto_depIdxs = []int32{
	0, // 0: fitglue.ActivityPayload.source:type_name -> fitglue.ActivitySource
	3, // 1: fitglue.ActivityPayload.timestamp:type_name -> google.protobuf.Timestamp
	2, // 2: fitglue.ActivityPayload.metadata:type_name -> fitglue.ActivityPayload.MetadataEntry
	4, // 3: fitglue.ActivityPayload.standardized_activity:type_name -> fitglue.StandardizedActivity
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_activity_proto_init() }
func file_activity_proto_init() {
	if File_activity_proto != nil {
		return
	}
	file_standardized_activity_proto_init()
	file_activity_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_activity_proto_rawDesc), len(file_activity_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_activity_proto_goTypes,
		DependencyIndexes: file_activity_proto_depIdxs,
		EnumInfos:         file_activity_proto_enumTypes,
		MessageInfos:      file_activity_proto_msgTypes,
	}.Build()
	File_activity_proto = out.File
	file_activity_proto_goTypes = nil
	file_activity_proto_depIdxs = nil
}
