// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.12.4
// source: execution.proto

package pb

import (
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ExecutionStatus int32

const (
	ExecutionStatus_STATUS_UNKNOWN ExecutionStatus = 0
	ExecutionStatus_STATUS_STARTED ExecutionStatus = 1
	ExecutionStatus_STATUS_SUCCESS ExecutionStatus = 2
	ExecutionStatus_STATUS_FAILED  ExecutionStatus = 3
)

// Enum value maps for ExecutionStatus.
var (
	ExecutionStatus_name = map[int32]string{
		0: "STATUS_UNKNOWN",
		1: "STATUS_STARTED",
		2: "STATUS_SUCCESS",
		3: "STATUS_FAILED",
	}
	ExecutionStatus_value = map[string]int32{
		"STATUS_UNKNOWN": 0,
		"STATUS_STARTED": 1,
		"STATUS_SUCCESS": 2,
		"STATUS_FAILED":  3,
	}
)

func (x ExecutionStatus) Enum() *ExecutionStatus {
	p := new(ExecutionStatus)
	*p = x
	return p
}

func (x ExecutionStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ExecutionStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_execution_proto_enumTypes[0].Descriptor()
}

func (ExecutionStatus) Type() protoreflect.EnumType {
	return &file_execution_proto_enumTypes[0]
}

func (x ExecutionStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ExecutionStatus.Descriptor instead.
func (ExecutionStatus) EnumDescriptor() ([]byte, []int) {
	return file_execution_proto_rawDescGZIP(), []int{0}
}

// ExecutionRecord represents a function execution in Firestore
type ExecutionRecord struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	ExecutionId string                 `protobuf:"bytes,1,opt,name=execution_id,json=executionId,proto3" json:"execution_id,omitempty"`
	Service     string                 `protobuf:"bytes,2,opt,name=service,proto3" json:"service,omitempty"`
	Status      ExecutionStatus        `protobuf:"varint,3,opt,name=status,proto3,enum=fitglue.ExecutionStatus" json:"status,omitempty"`
	Timestamp   *timestamp.Timestamp   `protobuf:"bytes,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// Optional context fields
	UserId    string `protobuf:"bytes,5,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	TestRunId string `protobuf:"bytes,6,opt,name=test_run_id,json=testRunId,proto3" json:"test_run_id,omitempty"` // For test cleanup
	// Trigger information
	TriggerType string `protobuf:"bytes,7,opt,name=trigger_type,json=triggerType,proto3" json:"trigger_type,omitempty"` // "http", "pubsub", "scheduler"
	// Timing
	StartTime *timestamp.Timestamp `protobuf:"bytes,8,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime   *timestamp.Timestamp `protobuf:"bytes,9,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	// Results
	ErrorMessage string `protobuf:"bytes,10,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	InputsJson   string `protobuf:"bytes,11,opt,name=inputs_json,json=inputsJson,proto3" json:"inputs_json,omitempty"`    // JSON-encoded inputs
	OutputsJson  string `protobuf:"bytes,12,opt,name=outputs_json,json=outputsJson,proto3" json:"outputs_json,omitempty"` // JSON-encoded outputs
	// Parent-child execution tracking
	ParentExecutionId string `protobuf:"bytes,13,opt,name=parent_execution_id,json=parentExecutionId,proto3" json:"parent_execution_id,omitempty"` // Links child executions to parent
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ExecutionRecord) Reset() {
	*x = ExecutionRecord{}
	mi := &file_execution_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecutionRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecutionRecord) ProtoMessage() {}

func (x *ExecutionRecord) ProtoReflect() protoreflect.Message {
	mi := &file_execution_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecutionRecord.ProtoReflect.Descriptor instead.
func (*ExecutionRecord) Descriptor() ([]byte, []int) {
	return file_execution_proto_rawDescGZIP(), []int{0}
}

func (x *ExecutionRecord) GetExecutionId() string {
	if x != nil {
		return x.ExecutionId
	}
	return ""
}

func (x *ExecutionRecord) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *ExecutionRecord) GetStatus() ExecutionStatus {
	if x != nil {
		return x.Status
	}
	return ExecutionStatus_STATUS_UNKNOWN
}

func (x *ExecutionRecord) GetTimestamp() *timestamp.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *ExecutionRecord) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ExecutionRecord) GetTestRunId() string {
	if x != nil {
		return x.TestRunId
	}
	return ""
}

func (x *ExecutionRecord) GetTriggerType() string {
	if x != nil {
		return x.TriggerType
	}
	return ""
}

func (x *ExecutionRecord) GetStartTime() *timestamp.Timestamp {
	if x != nil {
		return x.StartTime
	}
	return nil
}

func (x *ExecutionRecord) GetEndTime() *timestamp.Timestamp {
	if x != nil {
		return x.EndTime
	}
	return nil
}

func (x *ExecutionRecord) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *ExecutionRecord) GetInputsJson() string {
	if x != nil {
		return x.InputsJson
	}
	return ""
}

func (x *ExecutionRecord) GetOutputsJson() string {
	if x != nil {
		return x.OutputsJson
	}
	return ""
}

func (x *ExecutionRecord) GetParentExecutionId() string {
	if x != nil {
		return x.ParentExecutionId
	}
	return ""
}

var File_execution_proto protoreflect.FileDescriptor

const file_execution_proto_rawDesc = "" +
	"\n" +
	"\x0fexecution.proto\x12\afitglue\x1a\x1fgoogle/protobuf/timestamp.proto\"\xa1\x04\n" +
	"\x0fExecutionRecord\x12!\n" +
	"\fexecution_id\x18\x01 \x01(\tR\vexecutionId\x12\x18\n" +
	"\aservice\x18\x02 \x01(\tR\aservice\x120\n" +
	"\x06status\x18\x03 \x01(\x0e2\x18.fitglue.ExecutionStatusR\x06status\x128\n" +
	"\ttimestamp\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12\x17\n" +
	"\auser_id\x18\x05 \x01(\tR\x06userId\x12\x1e\n" +
	"\vtest_run_id\x18\x06 \x01(\tR\ttestRunId\x12!\n" +
	"\ftrigger_type\x18\a \x01(\tR\vtriggerType\x129\n" +
	"\n" +
	"start_time\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tstartTime\x125\n" +
	"\bend_time\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\aendTime\x12#\n" +
	"\rerror_message\x18\n" +
	" \x01(\tR\ferrorMessage\x12\x1f\n" +
	"\vinputs_json\x18\v \x01(\tR\n" +
	"inputsJson\x12!\n" +
	"\foutputs_json\x18\f \x01(\tR\voutputsJson\x12.\n" +
	"\x13parent_execution_id\x18\r \x01(\tR\x11parentExecutionId*`\n" +
	"\x0fExecutionStatus\x12\x12\n" +
	"\x0eSTATUS_UNKNOWN\x10\x00\x12\x12\n" +
	"\x0eSTATUS_STARTED\x10\x01\x12\x12\n" +
	"\x0eSTATUS_SUCCESS\x10\x02\x12\x11\n" +
	"\rSTATUS_FAILED\x10\x03B\x17Z\x15fitglue/pkg/shared/pbb\x06proto3"

var (
	file_execution_proto_rawDescOnce sync.Once
	file_execution_proto_rawDescData []byte
)

func file_execution_proto_rawDescGZIP() []byte {
	file_execution_proto_rawDescOnce.Do(func() {
		file_execution_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_execution_proto_rawDesc), len(file_execution_proto_rawDesc)))
	})
	return file_execution_proto_rawDescData
}

var file_execution_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_execution_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_execution_proto_goTypes = []any{
	(ExecutionStatus)(0),        // 0: fitglue.ExecutionStatus
	(*ExecutionRecord)(nil),     // 1: fitglue.ExecutionRecord
	(*timestamp.Timestamp)(nil), // 2: google.protobuf.Timestamp
}
var file_execution_proto_depIdxs = []int32{
	0, // 0: fitglue.ExecutionRecord.status:type_name -> fitglue.ExecutionStatus
	2, // 1: fitglue.ExecutionRecord.timestamp:type_name -> google.protobuf.Timestamp
	2, // 2: fitglue.ExecutionRecord.start_time:type_name -> google.protobuf.Timestamp
	2, // 3: fitglue.ExecutionRecord.end_time:type_name -> google.protobuf.Timestamp
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_execution_proto_init() }
func file_execution_proto_init() {
	if File_execution_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_execution_proto_rawDesc), len(file_execution_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_execution_proto_goTypes,
		DependencyIndexes: file_execution_proto_depIdxs,
		EnumInfos:         file_execution_proto_enumTypes,
		MessageInfos:      file_execution_proto_msgTypes,
	}.Build()
	File_execution_proto = out.File
	file_execution_proto_goTypes = nil
	file_execution_proto_depIdxs = nil
}
