// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.12.4
// source: plugin.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// PluginType categorizes plugins
type PluginType int32

const (
	PluginType_PLUGIN_TYPE_UNSPECIFIED PluginType = 0
	PluginType_PLUGIN_TYPE_SOURCE      PluginType = 1
	PluginType_PLUGIN_TYPE_ENRICHER    PluginType = 2
	PluginType_PLUGIN_TYPE_DESTINATION PluginType = 3
)

// Enum value maps for PluginType.
var (
	PluginType_name = map[int32]string{
		0: "PLUGIN_TYPE_UNSPECIFIED",
		1: "PLUGIN_TYPE_SOURCE",
		2: "PLUGIN_TYPE_ENRICHER",
		3: "PLUGIN_TYPE_DESTINATION",
	}
	PluginType_value = map[string]int32{
		"PLUGIN_TYPE_UNSPECIFIED": 0,
		"PLUGIN_TYPE_SOURCE":      1,
		"PLUGIN_TYPE_ENRICHER":    2,
		"PLUGIN_TYPE_DESTINATION": 3,
	}
)

func (x PluginType) Enum() *PluginType {
	p := new(PluginType)
	*p = x
	return p
}

func (x PluginType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PluginType) Descriptor() protoreflect.EnumDescriptor {
	return file_plugin_proto_enumTypes[0].Descriptor()
}

func (PluginType) Type() protoreflect.EnumType {
	return &file_plugin_proto_enumTypes[0]
}

func (x PluginType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PluginType.Descriptor instead.
func (PluginType) EnumDescriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{0}
}

type ConfigFieldType int32

const (
	ConfigFieldType_CONFIG_FIELD_TYPE_UNSPECIFIED   ConfigFieldType = 0
	ConfigFieldType_CONFIG_FIELD_TYPE_STRING        ConfigFieldType = 1
	ConfigFieldType_CONFIG_FIELD_TYPE_NUMBER        ConfigFieldType = 2
	ConfigFieldType_CONFIG_FIELD_TYPE_BOOLEAN       ConfigFieldType = 3
	ConfigFieldType_CONFIG_FIELD_TYPE_SELECT        ConfigFieldType = 4 // Dropdown
	ConfigFieldType_CONFIG_FIELD_TYPE_MULTI_SELECT  ConfigFieldType = 5 // Multiple selection
	ConfigFieldType_CONFIG_FIELD_TYPE_KEY_VALUE_MAP ConfigFieldType = 6 // Record<string, string> map - stored as JSON
)

// Enum value maps for ConfigFieldType.
var (
	ConfigFieldType_name = map[int32]string{
		0: "CONFIG_FIELD_TYPE_UNSPECIFIED",
		1: "CONFIG_FIELD_TYPE_STRING",
		2: "CONFIG_FIELD_TYPE_NUMBER",
		3: "CONFIG_FIELD_TYPE_BOOLEAN",
		4: "CONFIG_FIELD_TYPE_SELECT",
		5: "CONFIG_FIELD_TYPE_MULTI_SELECT",
		6: "CONFIG_FIELD_TYPE_KEY_VALUE_MAP",
	}
	ConfigFieldType_value = map[string]int32{
		"CONFIG_FIELD_TYPE_UNSPECIFIED":   0,
		"CONFIG_FIELD_TYPE_STRING":        1,
		"CONFIG_FIELD_TYPE_NUMBER":        2,
		"CONFIG_FIELD_TYPE_BOOLEAN":       3,
		"CONFIG_FIELD_TYPE_SELECT":        4,
		"CONFIG_FIELD_TYPE_MULTI_SELECT":  5,
		"CONFIG_FIELD_TYPE_KEY_VALUE_MAP": 6,
	}
)

func (x ConfigFieldType) Enum() *ConfigFieldType {
	p := new(ConfigFieldType)
	*p = x
	return p
}

func (x ConfigFieldType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ConfigFieldType) Descriptor() protoreflect.EnumDescriptor {
	return file_plugin_proto_enumTypes[1].Descriptor()
}

func (ConfigFieldType) Type() protoreflect.EnumType {
	return &file_plugin_proto_enumTypes[1]
}

func (x ConfigFieldType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ConfigFieldType.Descriptor instead.
func (ConfigFieldType) EnumDescriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{1}
}

// IntegrationAuthType defines how users authenticate with an integration
type IntegrationAuthType int32

const (
	IntegrationAuthType_INTEGRATION_AUTH_TYPE_UNSPECIFIED IntegrationAuthType = 0
	IntegrationAuthType_INTEGRATION_AUTH_TYPE_OAUTH       IntegrationAuthType = 1
	IntegrationAuthType_INTEGRATION_AUTH_TYPE_API_KEY     IntegrationAuthType = 2
)

// Enum value maps for IntegrationAuthType.
var (
	IntegrationAuthType_name = map[int32]string{
		0: "INTEGRATION_AUTH_TYPE_UNSPECIFIED",
		1: "INTEGRATION_AUTH_TYPE_OAUTH",
		2: "INTEGRATION_AUTH_TYPE_API_KEY",
	}
	IntegrationAuthType_value = map[string]int32{
		"INTEGRATION_AUTH_TYPE_UNSPECIFIED": 0,
		"INTEGRATION_AUTH_TYPE_OAUTH":       1,
		"INTEGRATION_AUTH_TYPE_API_KEY":     2,
	}
)

func (x IntegrationAuthType) Enum() *IntegrationAuthType {
	p := new(IntegrationAuthType)
	*p = x
	return p
}

func (x IntegrationAuthType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (IntegrationAuthType) Descriptor() protoreflect.EnumDescriptor {
	return file_plugin_proto_enumTypes[2].Descriptor()
}

func (IntegrationAuthType) Type() protoreflect.EnumType {
	return &file_plugin_proto_enumTypes[2]
}

func (x IntegrationAuthType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use IntegrationAuthType.Descriptor instead.
func (IntegrationAuthType) EnumDescriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{2}
}

// PluginManifest defines metadata for any plugin
type PluginManifest struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Id                   string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`                                                                 // Unique identifier (e.g., "hevy", "fitbit-hr", "strava")
	Type                 PluginType             `protobuf:"varint,2,opt,name=type,proto3,enum=fitglue.PluginType" json:"type,omitempty"`                                    // Source, Enricher, or Destination
	Name                 string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`                                                             // Human-readable name
	Description          string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`                                               // Short description
	Icon                 string                 `protobuf:"bytes,5,opt,name=icon,proto3" json:"icon,omitempty"`                                                             // Emoji or icon name
	ConfigSchema         []*ConfigFieldSchema   `protobuf:"bytes,6,rep,name=config_schema,json=configSchema,proto3" json:"config_schema,omitempty"`                         // Configuration fields
	RequiredIntegrations []string               `protobuf:"bytes,7,rep,name=required_integrations,json=requiredIntegrations,proto3" json:"required_integrations,omitempty"` // e.g., ["fitbit"] requires Fitbit connected
	Enabled              bool                   `protobuf:"varint,8,opt,name=enabled,proto3" json:"enabled,omitempty"`                                                      // Whether this plugin is available
	// For enrichers: links to the EnricherProviderType enum value
	EnricherProviderType *int32 `protobuf:"varint,9,opt,name=enricher_provider_type,json=enricherProviderType,proto3,oneof" json:"enricher_provider_type,omitempty"`
	// For destinations: links to the Destination enum value
	DestinationType *int32 `protobuf:"varint,10,opt,name=destination_type,json=destinationType,proto3,oneof" json:"destination_type,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *PluginManifest) Reset() {
	*x = PluginManifest{}
	mi := &file_plugin_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PluginManifest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PluginManifest) ProtoMessage() {}

func (x *PluginManifest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PluginManifest.ProtoReflect.Descriptor instead.
func (*PluginManifest) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{0}
}

func (x *PluginManifest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PluginManifest) GetType() PluginType {
	if x != nil {
		return x.Type
	}
	return PluginType_PLUGIN_TYPE_UNSPECIFIED
}

func (x *PluginManifest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PluginManifest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *PluginManifest) GetIcon() string {
	if x != nil {
		return x.Icon
	}
	return ""
}

func (x *PluginManifest) GetConfigSchema() []*ConfigFieldSchema {
	if x != nil {
		return x.ConfigSchema
	}
	return nil
}

func (x *PluginManifest) GetRequiredIntegrations() []string {
	if x != nil {
		return x.RequiredIntegrations
	}
	return nil
}

func (x *PluginManifest) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *PluginManifest) GetEnricherProviderType() int32 {
	if x != nil && x.EnricherProviderType != nil {
		return *x.EnricherProviderType
	}
	return 0
}

func (x *PluginManifest) GetDestinationType() int32 {
	if x != nil && x.DestinationType != nil {
		return *x.DestinationType
	}
	return 0
}

// ConfigFieldSchema defines a single configuration field
type ConfigFieldSchema struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`                                                            // Field key in config map
	Label         string                 `protobuf:"bytes,2,opt,name=label,proto3" json:"label,omitempty"`                                                        // Human-readable label
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`                                            // Help text
	FieldType     ConfigFieldType        `protobuf:"varint,4,opt,name=field_type,json=fieldType,proto3,enum=fitglue.ConfigFieldType" json:"field_type,omitempty"` // Type of input
	Required      bool                   `protobuf:"varint,5,opt,name=required,proto3" json:"required,omitempty"`                                                 // Whether field is required
	DefaultValue  string                 `protobuf:"bytes,6,opt,name=default_value,json=defaultValue,proto3" json:"default_value,omitempty"`                      // Default value (as string)
	Options       []*ConfigFieldOption   `protobuf:"bytes,7,rep,name=options,proto3" json:"options,omitempty"`                                                    // For SELECT/MULTI_SELECT types
	Validation    *ConfigFieldValidation `protobuf:"bytes,8,opt,name=validation,proto3" json:"validation,omitempty"`                                              // Validation rules
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigFieldSchema) Reset() {
	*x = ConfigFieldSchema{}
	mi := &file_plugin_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigFieldSchema) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigFieldSchema) ProtoMessage() {}

func (x *ConfigFieldSchema) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigFieldSchema.ProtoReflect.Descriptor instead.
func (*ConfigFieldSchema) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{1}
}

func (x *ConfigFieldSchema) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *ConfigFieldSchema) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *ConfigFieldSchema) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ConfigFieldSchema) GetFieldType() ConfigFieldType {
	if x != nil {
		return x.FieldType
	}
	return ConfigFieldType_CONFIG_FIELD_TYPE_UNSPECIFIED
}

func (x *ConfigFieldSchema) GetRequired() bool {
	if x != nil {
		return x.Required
	}
	return false
}

func (x *ConfigFieldSchema) GetDefaultValue() string {
	if x != nil {
		return x.DefaultValue
	}
	return ""
}

func (x *ConfigFieldSchema) GetOptions() []*ConfigFieldOption {
	if x != nil {
		return x.Options
	}
	return nil
}

func (x *ConfigFieldSchema) GetValidation() *ConfigFieldValidation {
	if x != nil {
		return x.Validation
	}
	return nil
}

type ConfigFieldOption struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         string                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"` // Stored value (descriptive string)
	Label         string                 `protobuf:"bytes,2,opt,name=label,proto3" json:"label,omitempty"` // Display label
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigFieldOption) Reset() {
	*x = ConfigFieldOption{}
	mi := &file_plugin_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigFieldOption) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigFieldOption) ProtoMessage() {}

func (x *ConfigFieldOption) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigFieldOption.ProtoReflect.Descriptor instead.
func (*ConfigFieldOption) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{2}
}

func (x *ConfigFieldOption) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *ConfigFieldOption) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

type ConfigFieldValidation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MinLength     *int32                 `protobuf:"varint,1,opt,name=min_length,json=minLength,proto3,oneof" json:"min_length,omitempty"`
	MaxLength     *int32                 `protobuf:"varint,2,opt,name=max_length,json=maxLength,proto3,oneof" json:"max_length,omitempty"`
	Pattern       *string                `protobuf:"bytes,3,opt,name=pattern,proto3,oneof" json:"pattern,omitempty"` // Regex pattern
	MinValue      *float64               `protobuf:"fixed64,4,opt,name=min_value,json=minValue,proto3,oneof" json:"min_value,omitempty"`
	MaxValue      *float64               `protobuf:"fixed64,5,opt,name=max_value,json=maxValue,proto3,oneof" json:"max_value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigFieldValidation) Reset() {
	*x = ConfigFieldValidation{}
	mi := &file_plugin_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigFieldValidation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigFieldValidation) ProtoMessage() {}

func (x *ConfigFieldValidation) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigFieldValidation.ProtoReflect.Descriptor instead.
func (*ConfigFieldValidation) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{3}
}

func (x *ConfigFieldValidation) GetMinLength() int32 {
	if x != nil && x.MinLength != nil {
		return *x.MinLength
	}
	return 0
}

func (x *ConfigFieldValidation) GetMaxLength() int32 {
	if x != nil && x.MaxLength != nil {
		return *x.MaxLength
	}
	return 0
}

func (x *ConfigFieldValidation) GetPattern() string {
	if x != nil && x.Pattern != nil {
		return *x.Pattern
	}
	return ""
}

func (x *ConfigFieldValidation) GetMinValue() float64 {
	if x != nil && x.MinValue != nil {
		return *x.MinValue
	}
	return 0
}

func (x *ConfigFieldValidation) GetMaxValue() float64 {
	if x != nil && x.MaxValue != nil {
		return *x.MaxValue
	}
	return 0
}

// IntegrationManifest defines metadata for external service integrations
type IntegrationManifest struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	Id          string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`                                                               // Unique identifier (e.g., "hevy", "fitbit", "strava")
	Name        string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`                                                           // Human-readable name
	Description string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`                                             // Short description
	Icon        string                 `protobuf:"bytes,4,opt,name=icon,proto3" json:"icon,omitempty"`                                                           // Emoji or icon name
	AuthType    IntegrationAuthType    `protobuf:"varint,5,opt,name=auth_type,json=authType,proto3,enum=fitglue.IntegrationAuthType" json:"auth_type,omitempty"` // How users connect
	Enabled     bool                   `protobuf:"varint,6,opt,name=enabled,proto3" json:"enabled,omitempty"`                                                    // Whether this integration is available
	DocsUrl     string                 `protobuf:"bytes,7,opt,name=docs_url,json=docsUrl,proto3" json:"docs_url,omitempty"`                                      // Link to setup guide
	// Setup configuration
	SetupTitle        string `protobuf:"bytes,8,opt,name=setup_title,json=setupTitle,proto3" json:"setup_title,omitempty"`                      // Modal title e.g., "Connect Hevy"
	SetupInstructions string `protobuf:"bytes,9,opt,name=setup_instructions,json=setupInstructions,proto3" json:"setup_instructions,omitempty"` // Markdown-formatted setup steps
	ApiKeyLabel       string `protobuf:"bytes,10,opt,name=api_key_label,json=apiKeyLabel,proto3" json:"api_key_label,omitempty"`                // Label for API key input e.g., "API Key"
	ApiKeyHelpUrl     string `protobuf:"bytes,11,opt,name=api_key_help_url,json=apiKeyHelpUrl,proto3" json:"api_key_help_url,omitempty"`        // URL where user gets the key
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *IntegrationManifest) Reset() {
	*x = IntegrationManifest{}
	mi := &file_plugin_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IntegrationManifest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IntegrationManifest) ProtoMessage() {}

func (x *IntegrationManifest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IntegrationManifest.ProtoReflect.Descriptor instead.
func (*IntegrationManifest) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{4}
}

func (x *IntegrationManifest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *IntegrationManifest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *IntegrationManifest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *IntegrationManifest) GetIcon() string {
	if x != nil {
		return x.Icon
	}
	return ""
}

func (x *IntegrationManifest) GetAuthType() IntegrationAuthType {
	if x != nil {
		return x.AuthType
	}
	return IntegrationAuthType_INTEGRATION_AUTH_TYPE_UNSPECIFIED
}

func (x *IntegrationManifest) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *IntegrationManifest) GetDocsUrl() string {
	if x != nil {
		return x.DocsUrl
	}
	return ""
}

func (x *IntegrationManifest) GetSetupTitle() string {
	if x != nil {
		return x.SetupTitle
	}
	return ""
}

func (x *IntegrationManifest) GetSetupInstructions() string {
	if x != nil {
		return x.SetupInstructions
	}
	return ""
}

func (x *IntegrationManifest) GetApiKeyLabel() string {
	if x != nil {
		return x.ApiKeyLabel
	}
	return ""
}

func (x *IntegrationManifest) GetApiKeyHelpUrl() string {
	if x != nil {
		return x.ApiKeyHelpUrl
	}
	return ""
}

// PluginRegistryResponse for API discovery
type PluginRegistryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sources       []*PluginManifest      `protobuf:"bytes,1,rep,name=sources,proto3" json:"sources,omitempty"`
	Enrichers     []*PluginManifest      `protobuf:"bytes,2,rep,name=enrichers,proto3" json:"enrichers,omitempty"`
	Destinations  []*PluginManifest      `protobuf:"bytes,3,rep,name=destinations,proto3" json:"destinations,omitempty"`
	Integrations  []*IntegrationManifest `protobuf:"bytes,4,rep,name=integrations,proto3" json:"integrations,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PluginRegistryResponse) Reset() {
	*x = PluginRegistryResponse{}
	mi := &file_plugin_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PluginRegistryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PluginRegistryResponse) ProtoMessage() {}

func (x *PluginRegistryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PluginRegistryResponse.ProtoReflect.Descriptor instead.
func (*PluginRegistryResponse) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{5}
}

func (x *PluginRegistryResponse) GetSources() []*PluginManifest {
	if x != nil {
		return x.Sources
	}
	return nil
}

func (x *PluginRegistryResponse) GetEnrichers() []*PluginManifest {
	if x != nil {
		return x.Enrichers
	}
	return nil
}

func (x *PluginRegistryResponse) GetDestinations() []*PluginManifest {
	if x != nil {
		return x.Destinations
	}
	return nil
}

func (x *PluginRegistryResponse) GetIntegrations() []*IntegrationManifest {
	if x != nil {
		return x.Integrations
	}
	return nil
}

var File_plugin_proto protoreflect.FileDescriptor

const file_plugin_proto_rawDesc = "" +
	"\n" +
	"\fplugin.proto\x12\afitglue\"\xbe\x03\n" +
	"\x0ePluginManifest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12'\n" +
	"\x04type\x18\x02 \x01(\x0e2\x13.fitglue.PluginTypeR\x04type\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x12\n" +
	"\x04icon\x18\x05 \x01(\tR\x04icon\x12?\n" +
	"\rconfig_schema\x18\x06 \x03(\v2\x1a.fitglue.ConfigFieldSchemaR\fconfigSchema\x123\n" +
	"\x15required_integrations\x18\a \x03(\tR\x14requiredIntegrations\x12\x18\n" +
	"\aenabled\x18\b \x01(\bR\aenabled\x129\n" +
	"\x16enricher_provider_type\x18\t \x01(\x05H\x00R\x14enricherProviderType\x88\x01\x01\x12.\n" +
	"\x10destination_type\x18\n" +
	" \x01(\x05H\x01R\x0fdestinationType\x88\x01\x01B\x19\n" +
	"\x17_enricher_provider_typeB\x13\n" +
	"\x11_destination_type\"\xcd\x02\n" +
	"\x11ConfigFieldSchema\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05label\x18\x02 \x01(\tR\x05label\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x127\n" +
	"\n" +
	"field_type\x18\x04 \x01(\x0e2\x18.fitglue.ConfigFieldTypeR\tfieldType\x12\x1a\n" +
	"\brequired\x18\x05 \x01(\bR\brequired\x12#\n" +
	"\rdefault_value\x18\x06 \x01(\tR\fdefaultValue\x124\n" +
	"\aoptions\x18\a \x03(\v2\x1a.fitglue.ConfigFieldOptionR\aoptions\x12>\n" +
	"\n" +
	"validation\x18\b \x01(\v2\x1e.fitglue.ConfigFieldValidationR\n" +
	"validation\"?\n" +
	"\x11ConfigFieldOption\x12\x14\n" +
	"\x05value\x18\x01 \x01(\tR\x05value\x12\x14\n" +
	"\x05label\x18\x02 \x01(\tR\x05label\"\x88\x02\n" +
	"\x15ConfigFieldValidation\x12\"\n" +
	"\n" +
	"min_length\x18\x01 \x01(\x05H\x00R\tminLength\x88\x01\x01\x12\"\n" +
	"\n" +
	"max_length\x18\x02 \x01(\x05H\x01R\tmaxLength\x88\x01\x01\x12\x1d\n" +
	"\apattern\x18\x03 \x01(\tH\x02R\apattern\x88\x01\x01\x12 \n" +
	"\tmin_value\x18\x04 \x01(\x01H\x03R\bminValue\x88\x01\x01\x12 \n" +
	"\tmax_value\x18\x05 \x01(\x01H\x04R\bmaxValue\x88\x01\x01B\r\n" +
	"\v_min_lengthB\r\n" +
	"\v_max_lengthB\n" +
	"\n" +
	"\b_patternB\f\n" +
	"\n" +
	"_min_valueB\f\n" +
	"\n" +
	"_max_value\"\xfc\x02\n" +
	"\x13IntegrationManifest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x12\n" +
	"\x04icon\x18\x04 \x01(\tR\x04icon\x129\n" +
	"\tauth_type\x18\x05 \x01(\x0e2\x1c.fitglue.IntegrationAuthTypeR\bauthType\x12\x18\n" +
	"\aenabled\x18\x06 \x01(\bR\aenabled\x12\x19\n" +
	"\bdocs_url\x18\a \x01(\tR\adocsUrl\x12\x1f\n" +
	"\vsetup_title\x18\b \x01(\tR\n" +
	"setupTitle\x12-\n" +
	"\x12setup_instructions\x18\t \x01(\tR\x11setupInstructions\x12\"\n" +
	"\rapi_key_label\x18\n" +
	" \x01(\tR\vapiKeyLabel\x12'\n" +
	"\x10api_key_help_url\x18\v \x01(\tR\rapiKeyHelpUrl\"\x81\x02\n" +
	"\x16PluginRegistryResponse\x121\n" +
	"\asources\x18\x01 \x03(\v2\x17.fitglue.PluginManifestR\asources\x125\n" +
	"\tenrichers\x18\x02 \x03(\v2\x17.fitglue.PluginManifestR\tenrichers\x12;\n" +
	"\fdestinations\x18\x03 \x03(\v2\x17.fitglue.PluginManifestR\fdestinations\x12@\n" +
	"\fintegrations\x18\x04 \x03(\v2\x1c.fitglue.IntegrationManifestR\fintegrations*x\n" +
	"\n" +
	"PluginType\x12\x1b\n" +
	"\x17PLUGIN_TYPE_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12PLUGIN_TYPE_SOURCE\x10\x01\x12\x18\n" +
	"\x14PLUGIN_TYPE_ENRICHER\x10\x02\x12\x1b\n" +
	"\x17PLUGIN_TYPE_DESTINATION\x10\x03*\xf6\x01\n" +
	"\x0fConfigFieldType\x12!\n" +
	"\x1dCONFIG_FIELD_TYPE_UNSPECIFIED\x10\x00\x12\x1c\n" +
	"\x18CONFIG_FIELD_TYPE_STRING\x10\x01\x12\x1c\n" +
	"\x18CONFIG_FIELD_TYPE_NUMBER\x10\x02\x12\x1d\n" +
	"\x19CONFIG_FIELD_TYPE_BOOLEAN\x10\x03\x12\x1c\n" +
	"\x18CONFIG_FIELD_TYPE_SELECT\x10\x04\x12\"\n" +
	"\x1eCONFIG_FIELD_TYPE_MULTI_SELECT\x10\x05\x12#\n" +
	"\x1fCONFIG_FIELD_TYPE_KEY_VALUE_MAP\x10\x06*\x80\x01\n" +
	"\x13IntegrationAuthType\x12%\n" +
	"!INTEGRATION_AUTH_TYPE_UNSPECIFIED\x10\x00\x12\x1f\n" +
	"\x1bINTEGRATION_AUTH_TYPE_OAUTH\x10\x01\x12!\n" +
	"\x1dINTEGRATION_AUTH_TYPE_API_KEY\x10\x02B7Z5github.com/ripixel/fitglue-server/src/go/pkg/types/pbb\x06proto3"

var (
	file_plugin_proto_rawDescOnce sync.Once
	file_plugin_proto_rawDescData []byte
)

func file_plugin_proto_rawDescGZIP() []byte {
	file_plugin_proto_rawDescOnce.Do(func() {
		file_plugin_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_plugin_proto_rawDesc), len(file_plugin_proto_rawDesc)))
	})
	return file_plugin_proto_rawDescData
}

var file_plugin_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_plugin_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_plugin_proto_goTypes = []any{
	(PluginType)(0),                // 0: fitglue.PluginType
	(ConfigFieldType)(0),           // 1: fitglue.ConfigFieldType
	(IntegrationAuthType)(0),       // 2: fitglue.IntegrationAuthType
	(*PluginManifest)(nil),         // 3: fitglue.PluginManifest
	(*ConfigFieldSchema)(nil),      // 4: fitglue.ConfigFieldSchema
	(*ConfigFieldOption)(nil),      // 5: fitglue.ConfigFieldOption
	(*ConfigFieldValidation)(nil),  // 6: fitglue.ConfigFieldValidation
	(*IntegrationManifest)(nil),    // 7: fitglue.IntegrationManifest
	(*PluginRegistryResponse)(nil), // 8: fitglue.PluginRegistryResponse
}
var file_plugin_proto_depIdxs = []int32{
	0,  // 0: fitglue.PluginManifest.type:type_name -> fitglue.PluginType
	4,  // 1: fitglue.PluginManifest.config_schema:type_name -> fitglue.ConfigFieldSchema
	1,  // 2: fitglue.ConfigFieldSchema.field_type:type_name -> fitglue.ConfigFieldType
	5,  // 3: fitglue.ConfigFieldSchema.options:type_name -> fitglue.ConfigFieldOption
	6,  // 4: fitglue.ConfigFieldSchema.validation:type_name -> fitglue.ConfigFieldValidation
	2,  // 5: fitglue.IntegrationManifest.auth_type:type_name -> fitglue.IntegrationAuthType
	3,  // 6: fitglue.PluginRegistryResponse.sources:type_name -> fitglue.PluginManifest
	3,  // 7: fitglue.PluginRegistryResponse.enrichers:type_name -> fitglue.PluginManifest
	3,  // 8: fitglue.PluginRegistryResponse.destinations:type_name -> fitglue.PluginManifest
	7,  // 9: fitglue.PluginRegistryResponse.integrations:type_name -> fitglue.IntegrationManifest
	10, // [10:10] is the sub-list for method output_type
	10, // [10:10] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_plugin_proto_init() }
func file_plugin_proto_init() {
	if File_plugin_proto != nil {
		return
	}
	file_plugin_proto_msgTypes[0].OneofWrappers = []any{}
	file_plugin_proto_msgTypes[3].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_plugin_proto_rawDesc), len(file_plugin_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_plugin_proto_goTypes,
		DependencyIndexes: file_plugin_proto_depIdxs,
		EnumInfos:         file_plugin_proto_enumTypes,
		MessageInfos:      file_plugin_proto_msgTypes,
	}.Build()
	File_plugin_proto = out.File
	file_plugin_proto_goTypes = nil
	file_plugin_proto_depIdxs = nil
}
