// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.12.4
// source: standardized_activity.proto

package pb

import (
	descriptor "github.com/golang/protobuf/protoc-gen-go/descriptor"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ActivityType enum based on Strava's accepted activity types.
// Use the strava_name extension to get the exact Strava API string.
// Stored as string in Firestore for readability.
type ActivityType int32

const (
	ActivityType_ACTIVITY_TYPE_UNSPECIFIED                      ActivityType = 0
	ActivityType_ACTIVITY_TYPE_ALPINE_SKI                       ActivityType = 1
	ActivityType_ACTIVITY_TYPE_BACKCOUNTRY_SKI                  ActivityType = 2
	ActivityType_ACTIVITY_TYPE_BADMINTON                        ActivityType = 3
	ActivityType_ACTIVITY_TYPE_CANOEING                         ActivityType = 4
	ActivityType_ACTIVITY_TYPE_CROSSFIT                         ActivityType = 5
	ActivityType_ACTIVITY_TYPE_EBIKE_RIDE                       ActivityType = 6
	ActivityType_ACTIVITY_TYPE_ELLIPTICAL                       ActivityType = 7
	ActivityType_ACTIVITY_TYPE_EMOUNTAIN_BIKE_RIDE              ActivityType = 8
	ActivityType_ACTIVITY_TYPE_GOLF                             ActivityType = 9
	ActivityType_ACTIVITY_TYPE_GRAVEL_RIDE                      ActivityType = 10
	ActivityType_ACTIVITY_TYPE_HANDCYCLE                        ActivityType = 11
	ActivityType_ACTIVITY_TYPE_HIGH_INTENSITY_INTERVAL_TRAINING ActivityType = 12
	ActivityType_ACTIVITY_TYPE_HIKE                             ActivityType = 13
	ActivityType_ACTIVITY_TYPE_ICE_SKATE                        ActivityType = 14
	ActivityType_ACTIVITY_TYPE_INLINE_SKATE                     ActivityType = 15
	ActivityType_ACTIVITY_TYPE_KAYAKING                         ActivityType = 16
	ActivityType_ACTIVITY_TYPE_KITESURF                         ActivityType = 17
	ActivityType_ACTIVITY_TYPE_MOUNTAIN_BIKE_RIDE               ActivityType = 18
	ActivityType_ACTIVITY_TYPE_NORDIC_SKI                       ActivityType = 19
	ActivityType_ACTIVITY_TYPE_PICKLEBALL                       ActivityType = 20
	ActivityType_ACTIVITY_TYPE_PILATES                          ActivityType = 21
	ActivityType_ACTIVITY_TYPE_RACQUETBALL                      ActivityType = 22
	ActivityType_ACTIVITY_TYPE_RIDE                             ActivityType = 23
	ActivityType_ACTIVITY_TYPE_ROCK_CLIMBING                    ActivityType = 24
	ActivityType_ACTIVITY_TYPE_ROLLER_SKI                       ActivityType = 25
	ActivityType_ACTIVITY_TYPE_ROWING                           ActivityType = 26
	ActivityType_ACTIVITY_TYPE_RUN                              ActivityType = 27
	ActivityType_ACTIVITY_TYPE_SAIL                             ActivityType = 28
	ActivityType_ACTIVITY_TYPE_SKATEBOARD                       ActivityType = 29
	ActivityType_ACTIVITY_TYPE_SNOWBOARD                        ActivityType = 30
	ActivityType_ACTIVITY_TYPE_SNOWSHOE                         ActivityType = 31
	ActivityType_ACTIVITY_TYPE_SOCCER                           ActivityType = 32
	ActivityType_ACTIVITY_TYPE_SQUASH                           ActivityType = 33
	ActivityType_ACTIVITY_TYPE_STAIR_STEPPER                    ActivityType = 34
	ActivityType_ACTIVITY_TYPE_STAND_UP_PADDLING                ActivityType = 35
	ActivityType_ACTIVITY_TYPE_SURFING                          ActivityType = 36
	ActivityType_ACTIVITY_TYPE_SWIM                             ActivityType = 37
	ActivityType_ACTIVITY_TYPE_TABLE_TENNIS                     ActivityType = 38
	ActivityType_ACTIVITY_TYPE_TENNIS                           ActivityType = 39
	ActivityType_ACTIVITY_TYPE_TRAIL_RUN                        ActivityType = 40
	ActivityType_ACTIVITY_TYPE_VELOMOBILE                       ActivityType = 41
	ActivityType_ACTIVITY_TYPE_VIRTUAL_RIDE                     ActivityType = 42
	ActivityType_ACTIVITY_TYPE_VIRTUAL_ROW                      ActivityType = 43
	ActivityType_ACTIVITY_TYPE_VIRTUAL_RUN                      ActivityType = 44
	ActivityType_ACTIVITY_TYPE_WALK                             ActivityType = 45
	ActivityType_ACTIVITY_TYPE_WEIGHT_TRAINING                  ActivityType = 46
	ActivityType_ACTIVITY_TYPE_WHEELCHAIR                       ActivityType = 47
	ActivityType_ACTIVITY_TYPE_WINDSURF                         ActivityType = 48
	ActivityType_ACTIVITY_TYPE_WORKOUT                          ActivityType = 49
	ActivityType_ACTIVITY_TYPE_YOGA                             ActivityType = 50
)

// Enum value maps for ActivityType.
var (
	ActivityType_name = map[int32]string{
		0:  "ACTIVITY_TYPE_UNSPECIFIED",
		1:  "ACTIVITY_TYPE_ALPINE_SKI",
		2:  "ACTIVITY_TYPE_BACKCOUNTRY_SKI",
		3:  "ACTIVITY_TYPE_BADMINTON",
		4:  "ACTIVITY_TYPE_CANOEING",
		5:  "ACTIVITY_TYPE_CROSSFIT",
		6:  "ACTIVITY_TYPE_EBIKE_RIDE",
		7:  "ACTIVITY_TYPE_ELLIPTICAL",
		8:  "ACTIVITY_TYPE_EMOUNTAIN_BIKE_RIDE",
		9:  "ACTIVITY_TYPE_GOLF",
		10: "ACTIVITY_TYPE_GRAVEL_RIDE",
		11: "ACTIVITY_TYPE_HANDCYCLE",
		12: "ACTIVITY_TYPE_HIGH_INTENSITY_INTERVAL_TRAINING",
		13: "ACTIVITY_TYPE_HIKE",
		14: "ACTIVITY_TYPE_ICE_SKATE",
		15: "ACTIVITY_TYPE_INLINE_SKATE",
		16: "ACTIVITY_TYPE_KAYAKING",
		17: "ACTIVITY_TYPE_KITESURF",
		18: "ACTIVITY_TYPE_MOUNTAIN_BIKE_RIDE",
		19: "ACTIVITY_TYPE_NORDIC_SKI",
		20: "ACTIVITY_TYPE_PICKLEBALL",
		21: "ACTIVITY_TYPE_PILATES",
		22: "ACTIVITY_TYPE_RACQUETBALL",
		23: "ACTIVITY_TYPE_RIDE",
		24: "ACTIVITY_TYPE_ROCK_CLIMBING",
		25: "ACTIVITY_TYPE_ROLLER_SKI",
		26: "ACTIVITY_TYPE_ROWING",
		27: "ACTIVITY_TYPE_RUN",
		28: "ACTIVITY_TYPE_SAIL",
		29: "ACTIVITY_TYPE_SKATEBOARD",
		30: "ACTIVITY_TYPE_SNOWBOARD",
		31: "ACTIVITY_TYPE_SNOWSHOE",
		32: "ACTIVITY_TYPE_SOCCER",
		33: "ACTIVITY_TYPE_SQUASH",
		34: "ACTIVITY_TYPE_STAIR_STEPPER",
		35: "ACTIVITY_TYPE_STAND_UP_PADDLING",
		36: "ACTIVITY_TYPE_SURFING",
		37: "ACTIVITY_TYPE_SWIM",
		38: "ACTIVITY_TYPE_TABLE_TENNIS",
		39: "ACTIVITY_TYPE_TENNIS",
		40: "ACTIVITY_TYPE_TRAIL_RUN",
		41: "ACTIVITY_TYPE_VELOMOBILE",
		42: "ACTIVITY_TYPE_VIRTUAL_RIDE",
		43: "ACTIVITY_TYPE_VIRTUAL_ROW",
		44: "ACTIVITY_TYPE_VIRTUAL_RUN",
		45: "ACTIVITY_TYPE_WALK",
		46: "ACTIVITY_TYPE_WEIGHT_TRAINING",
		47: "ACTIVITY_TYPE_WHEELCHAIR",
		48: "ACTIVITY_TYPE_WINDSURF",
		49: "ACTIVITY_TYPE_WORKOUT",
		50: "ACTIVITY_TYPE_YOGA",
	}
	ActivityType_value = map[string]int32{
		"ACTIVITY_TYPE_UNSPECIFIED":                      0,
		"ACTIVITY_TYPE_ALPINE_SKI":                       1,
		"ACTIVITY_TYPE_BACKCOUNTRY_SKI":                  2,
		"ACTIVITY_TYPE_BADMINTON":                        3,
		"ACTIVITY_TYPE_CANOEING":                         4,
		"ACTIVITY_TYPE_CROSSFIT":                         5,
		"ACTIVITY_TYPE_EBIKE_RIDE":                       6,
		"ACTIVITY_TYPE_ELLIPTICAL":                       7,
		"ACTIVITY_TYPE_EMOUNTAIN_BIKE_RIDE":              8,
		"ACTIVITY_TYPE_GOLF":                             9,
		"ACTIVITY_TYPE_GRAVEL_RIDE":                      10,
		"ACTIVITY_TYPE_HANDCYCLE":                        11,
		"ACTIVITY_TYPE_HIGH_INTENSITY_INTERVAL_TRAINING": 12,
		"ACTIVITY_TYPE_HIKE":                             13,
		"ACTIVITY_TYPE_ICE_SKATE":                        14,
		"ACTIVITY_TYPE_INLINE_SKATE":                     15,
		"ACTIVITY_TYPE_KAYAKING":                         16,
		"ACTIVITY_TYPE_KITESURF":                         17,
		"ACTIVITY_TYPE_MOUNTAIN_BIKE_RIDE":               18,
		"ACTIVITY_TYPE_NORDIC_SKI":                       19,
		"ACTIVITY_TYPE_PICKLEBALL":                       20,
		"ACTIVITY_TYPE_PILATES":                          21,
		"ACTIVITY_TYPE_RACQUETBALL":                      22,
		"ACTIVITY_TYPE_RIDE":                             23,
		"ACTIVITY_TYPE_ROCK_CLIMBING":                    24,
		"ACTIVITY_TYPE_ROLLER_SKI":                       25,
		"ACTIVITY_TYPE_ROWING":                           26,
		"ACTIVITY_TYPE_RUN":                              27,
		"ACTIVITY_TYPE_SAIL":                             28,
		"ACTIVITY_TYPE_SKATEBOARD":                       29,
		"ACTIVITY_TYPE_SNOWBOARD":                        30,
		"ACTIVITY_TYPE_SNOWSHOE":                         31,
		"ACTIVITY_TYPE_SOCCER":                           32,
		"ACTIVITY_TYPE_SQUASH":                           33,
		"ACTIVITY_TYPE_STAIR_STEPPER":                    34,
		"ACTIVITY_TYPE_STAND_UP_PADDLING":                35,
		"ACTIVITY_TYPE_SURFING":                          36,
		"ACTIVITY_TYPE_SWIM":                             37,
		"ACTIVITY_TYPE_TABLE_TENNIS":                     38,
		"ACTIVITY_TYPE_TENNIS":                           39,
		"ACTIVITY_TYPE_TRAIL_RUN":                        40,
		"ACTIVITY_TYPE_VELOMOBILE":                       41,
		"ACTIVITY_TYPE_VIRTUAL_RIDE":                     42,
		"ACTIVITY_TYPE_VIRTUAL_ROW":                      43,
		"ACTIVITY_TYPE_VIRTUAL_RUN":                      44,
		"ACTIVITY_TYPE_WALK":                             45,
		"ACTIVITY_TYPE_WEIGHT_TRAINING":                  46,
		"ACTIVITY_TYPE_WHEELCHAIR":                       47,
		"ACTIVITY_TYPE_WINDSURF":                         48,
		"ACTIVITY_TYPE_WORKOUT":                          49,
		"ACTIVITY_TYPE_YOGA":                             50,
	}
)

func (x ActivityType) Enum() *ActivityType {
	p := new(ActivityType)
	*p = x
	return p
}

func (x ActivityType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ActivityType) Descriptor() protoreflect.EnumDescriptor {
	return file_standardized_activity_proto_enumTypes[0].Descriptor()
}

func (ActivityType) Type() protoreflect.EnumType {
	return &file_standardized_activity_proto_enumTypes[0]
}

func (x ActivityType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ActivityType.Descriptor instead.
func (ActivityType) EnumDescriptor() ([]byte, []int) {
	return file_standardized_activity_proto_rawDescGZIP(), []int{0}
}

type MuscleGroup int32

const (
	MuscleGroup_MUSCLE_GROUP_UNSPECIFIED MuscleGroup = 0
	MuscleGroup_MUSCLE_GROUP_ABDOMINALS  MuscleGroup = 1
	MuscleGroup_MUSCLE_GROUP_SHOULDERS   MuscleGroup = 2
	MuscleGroup_MUSCLE_GROUP_BICEPS      MuscleGroup = 3
	MuscleGroup_MUSCLE_GROUP_TRICEPS     MuscleGroup = 4
	MuscleGroup_MUSCLE_GROUP_FOREARMS    MuscleGroup = 5
	MuscleGroup_MUSCLE_GROUP_QUADRICEPS  MuscleGroup = 6
	MuscleGroup_MUSCLE_GROUP_HAMSTRINGS  MuscleGroup = 7
	MuscleGroup_MUSCLE_GROUP_CALVES      MuscleGroup = 8
	MuscleGroup_MUSCLE_GROUP_GLUTES      MuscleGroup = 9
	MuscleGroup_MUSCLE_GROUP_ABDUCTORS   MuscleGroup = 10
	MuscleGroup_MUSCLE_GROUP_ADDUCTORS   MuscleGroup = 11
	MuscleGroup_MUSCLE_GROUP_LATS        MuscleGroup = 12
	MuscleGroup_MUSCLE_GROUP_UPPER_BACK  MuscleGroup = 13
	MuscleGroup_MUSCLE_GROUP_TRAPS       MuscleGroup = 14
	MuscleGroup_MUSCLE_GROUP_LOWER_BACK  MuscleGroup = 15
	MuscleGroup_MUSCLE_GROUP_CHEST       MuscleGroup = 16
	MuscleGroup_MUSCLE_GROUP_CARDIO      MuscleGroup = 17
	MuscleGroup_MUSCLE_GROUP_NECK        MuscleGroup = 18
	MuscleGroup_MUSCLE_GROUP_FULL_BODY   MuscleGroup = 19
	MuscleGroup_MUSCLE_GROUP_OTHER       MuscleGroup = 20
)

// Enum value maps for MuscleGroup.
var (
	MuscleGroup_name = map[int32]string{
		0:  "MUSCLE_GROUP_UNSPECIFIED",
		1:  "MUSCLE_GROUP_ABDOMINALS",
		2:  "MUSCLE_GROUP_SHOULDERS",
		3:  "MUSCLE_GROUP_BICEPS",
		4:  "MUSCLE_GROUP_TRICEPS",
		5:  "MUSCLE_GROUP_FOREARMS",
		6:  "MUSCLE_GROUP_QUADRICEPS",
		7:  "MUSCLE_GROUP_HAMSTRINGS",
		8:  "MUSCLE_GROUP_CALVES",
		9:  "MUSCLE_GROUP_GLUTES",
		10: "MUSCLE_GROUP_ABDUCTORS",
		11: "MUSCLE_GROUP_ADDUCTORS",
		12: "MUSCLE_GROUP_LATS",
		13: "MUSCLE_GROUP_UPPER_BACK",
		14: "MUSCLE_GROUP_TRAPS",
		15: "MUSCLE_GROUP_LOWER_BACK",
		16: "MUSCLE_GROUP_CHEST",
		17: "MUSCLE_GROUP_CARDIO",
		18: "MUSCLE_GROUP_NECK",
		19: "MUSCLE_GROUP_FULL_BODY",
		20: "MUSCLE_GROUP_OTHER",
	}
	MuscleGroup_value = map[string]int32{
		"MUSCLE_GROUP_UNSPECIFIED": 0,
		"MUSCLE_GROUP_ABDOMINALS":  1,
		"MUSCLE_GROUP_SHOULDERS":   2,
		"MUSCLE_GROUP_BICEPS":      3,
		"MUSCLE_GROUP_TRICEPS":     4,
		"MUSCLE_GROUP_FOREARMS":    5,
		"MUSCLE_GROUP_QUADRICEPS":  6,
		"MUSCLE_GROUP_HAMSTRINGS":  7,
		"MUSCLE_GROUP_CALVES":      8,
		"MUSCLE_GROUP_GLUTES":      9,
		"MUSCLE_GROUP_ABDUCTORS":   10,
		"MUSCLE_GROUP_ADDUCTORS":   11,
		"MUSCLE_GROUP_LATS":        12,
		"MUSCLE_GROUP_UPPER_BACK":  13,
		"MUSCLE_GROUP_TRAPS":       14,
		"MUSCLE_GROUP_LOWER_BACK":  15,
		"MUSCLE_GROUP_CHEST":       16,
		"MUSCLE_GROUP_CARDIO":      17,
		"MUSCLE_GROUP_NECK":        18,
		"MUSCLE_GROUP_FULL_BODY":   19,
		"MUSCLE_GROUP_OTHER":       20,
	}
)

func (x MuscleGroup) Enum() *MuscleGroup {
	p := new(MuscleGroup)
	*p = x
	return p
}

func (x MuscleGroup) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MuscleGroup) Descriptor() protoreflect.EnumDescriptor {
	return file_standardized_activity_proto_enumTypes[1].Descriptor()
}

func (MuscleGroup) Type() protoreflect.EnumType {
	return &file_standardized_activity_proto_enumTypes[1]
}

func (x MuscleGroup) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MuscleGroup.Descriptor instead.
func (MuscleGroup) EnumDescriptor() ([]byte, []int) {
	return file_standardized_activity_proto_rawDescGZIP(), []int{1}
}

// StandardizedActivity represents a normalized fitness activity.
// It is designed to be the canonical input format for the Enricher,
// decoupling it from specific ingestion sources (Hevy, etc).
//
// Structure mimics the FIT SDK hierarchy:
// Activity -> Sessions -> Laps -> Records
type StandardizedActivity struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	Source     string                 `protobuf:"bytes,1,opt,name=source,proto3" json:"source,omitempty"`                           // e.g. "HEVY"
	ExternalId string                 `protobuf:"bytes,2,opt,name=external_id,json=externalId,proto3" json:"external_id,omitempty"` // Source's ID (e.g. Hevy workout ID)
	UserId     string                 `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	// High-level summary
	StartTime *timestamp.Timestamp `protobuf:"bytes,4,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	Name      string               `protobuf:"bytes,5,opt,name=name,proto3" json:"name,omitempty"`                            // e.g. "Morning Run"
	Type      ActivityType         `protobuf:"varint,6,opt,name=type,proto3,enum=fitglue.ActivityType" json:"type,omitempty"` // Strava-compatible activity type
	// Hierarchy
	Sessions []*Session `protobuf:"bytes,7,rep,name=sessions,proto3" json:"sessions,omitempty"`
	// Rich metadata (preserved from source)
	Description   string   `protobuf:"bytes,8,opt,name=description,proto3" json:"description,omitempty"` // User notes
	Tags          []string `protobuf:"bytes,9,rep,name=tags,proto3" json:"tags,omitempty"`
	Notes         string   `protobuf:"bytes,10,opt,name=notes,proto3" json:"notes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StandardizedActivity) Reset() {
	*x = StandardizedActivity{}
	mi := &file_standardized_activity_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StandardizedActivity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StandardizedActivity) ProtoMessage() {}

func (x *StandardizedActivity) ProtoReflect() protoreflect.Message {
	mi := &file_standardized_activity_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StandardizedActivity.ProtoReflect.Descriptor instead.
func (*StandardizedActivity) Descriptor() ([]byte, []int) {
	return file_standardized_activity_proto_rawDescGZIP(), []int{0}
}

func (x *StandardizedActivity) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *StandardizedActivity) GetExternalId() string {
	if x != nil {
		return x.ExternalId
	}
	return ""
}

func (x *StandardizedActivity) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *StandardizedActivity) GetStartTime() *timestamp.Timestamp {
	if x != nil {
		return x.StartTime
	}
	return nil
}

func (x *StandardizedActivity) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *StandardizedActivity) GetType() ActivityType {
	if x != nil {
		return x.Type
	}
	return ActivityType_ACTIVITY_TYPE_UNSPECIFIED
}

func (x *StandardizedActivity) GetSessions() []*Session {
	if x != nil {
		return x.Sessions
	}
	return nil
}

func (x *StandardizedActivity) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *StandardizedActivity) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *StandardizedActivity) GetNotes() string {
	if x != nil {
		return x.Notes
	}
	return ""
}

type Session struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	StartTime        *timestamp.Timestamp   `protobuf:"bytes,1,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	TotalElapsedTime float64                `protobuf:"fixed64,2,opt,name=total_elapsed_time,json=totalElapsedTime,proto3" json:"total_elapsed_time,omitempty"` // seconds
	TotalDistance    float64                `protobuf:"fixed64,3,opt,name=total_distance,json=totalDistance,proto3" json:"total_distance,omitempty"`            // meters
	Laps             []*Lap                 `protobuf:"bytes,4,rep,name=laps,proto3" json:"laps,omitempty"`
	// High-fidelity strength data (not just 1Hz streams)
	StrengthSets  []*StrengthSet `protobuf:"bytes,5,rep,name=strength_sets,json=strengthSets,proto3" json:"strength_sets,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Session) Reset() {
	*x = Session{}
	mi := &file_standardized_activity_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Session) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Session) ProtoMessage() {}

func (x *Session) ProtoReflect() protoreflect.Message {
	mi := &file_standardized_activity_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Session.ProtoReflect.Descriptor instead.
func (*Session) Descriptor() ([]byte, []int) {
	return file_standardized_activity_proto_rawDescGZIP(), []int{1}
}

func (x *Session) GetStartTime() *timestamp.Timestamp {
	if x != nil {
		return x.StartTime
	}
	return nil
}

func (x *Session) GetTotalElapsedTime() float64 {
	if x != nil {
		return x.TotalElapsedTime
	}
	return 0
}

func (x *Session) GetTotalDistance() float64 {
	if x != nil {
		return x.TotalDistance
	}
	return 0
}

func (x *Session) GetLaps() []*Lap {
	if x != nil {
		return x.Laps
	}
	return nil
}

func (x *Session) GetStrengthSets() []*StrengthSet {
	if x != nil {
		return x.StrengthSets
	}
	return nil
}

type Lap struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	StartTime        *timestamp.Timestamp   `protobuf:"bytes,1,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	TotalElapsedTime float64                `protobuf:"fixed64,2,opt,name=total_elapsed_time,json=totalElapsedTime,proto3" json:"total_elapsed_time,omitempty"` // seconds
	TotalDistance    float64                `protobuf:"fixed64,3,opt,name=total_distance,json=totalDistance,proto3" json:"total_distance,omitempty"`            // meters
	Records          []*Record              `protobuf:"bytes,4,rep,name=records,proto3" json:"records,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Lap) Reset() {
	*x = Lap{}
	mi := &file_standardized_activity_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Lap) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Lap) ProtoMessage() {}

func (x *Lap) ProtoReflect() protoreflect.Message {
	mi := &file_standardized_activity_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Lap.ProtoReflect.Descriptor instead.
func (*Lap) Descriptor() ([]byte, []int) {
	return file_standardized_activity_proto_rawDescGZIP(), []int{2}
}

func (x *Lap) GetStartTime() *timestamp.Timestamp {
	if x != nil {
		return x.StartTime
	}
	return nil
}

func (x *Lap) GetTotalElapsedTime() float64 {
	if x != nil {
		return x.TotalElapsedTime
	}
	return 0
}

func (x *Lap) GetTotalDistance() float64 {
	if x != nil {
		return x.TotalDistance
	}
	return 0
}

func (x *Lap) GetRecords() []*Record {
	if x != nil {
		return x.Records
	}
	return nil
}

// Record represents a single data point in time (1Hz is typical)
type Record struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Timestamp *timestamp.Timestamp   `protobuf:"bytes,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// Core Telemetry
	HeartRate int32   `protobuf:"varint,2,opt,name=heart_rate,json=heartRate,proto3" json:"heart_rate,omitempty"` // bpm
	Power     int32   `protobuf:"varint,3,opt,name=power,proto3" json:"power,omitempty"`                          // watts
	Cadence   int32   `protobuf:"varint,4,opt,name=cadence,proto3" json:"cadence,omitempty"`                      // rpm
	Speed     float64 `protobuf:"fixed64,5,opt,name=speed,proto3" json:"speed,omitempty"`                         // m/s
	Altitude  float64 `protobuf:"fixed64,6,opt,name=altitude,proto3" json:"altitude,omitempty"`                   // meters
	// Location
	PositionLat   float64 `protobuf:"fixed64,7,opt,name=position_lat,json=positionLat,proto3" json:"position_lat,omitempty"`
	PositionLong  float64 `protobuf:"fixed64,8,opt,name=position_long,json=positionLong,proto3" json:"position_long,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Record) Reset() {
	*x = Record{}
	mi := &file_standardized_activity_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Record) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Record) ProtoMessage() {}

func (x *Record) ProtoReflect() protoreflect.Message {
	mi := &file_standardized_activity_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Record.ProtoReflect.Descriptor instead.
func (*Record) Descriptor() ([]byte, []int) {
	return file_standardized_activity_proto_rawDescGZIP(), []int{3}
}

func (x *Record) GetTimestamp() *timestamp.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *Record) GetHeartRate() int32 {
	if x != nil {
		return x.HeartRate
	}
	return 0
}

func (x *Record) GetPower() int32 {
	if x != nil {
		return x.Power
	}
	return 0
}

func (x *Record) GetCadence() int32 {
	if x != nil {
		return x.Cadence
	}
	return 0
}

func (x *Record) GetSpeed() float64 {
	if x != nil {
		return x.Speed
	}
	return 0
}

func (x *Record) GetAltitude() float64 {
	if x != nil {
		return x.Altitude
	}
	return 0
}

func (x *Record) GetPositionLat() float64 {
	if x != nil {
		return x.PositionLat
	}
	return 0
}

func (x *Record) GetPositionLong() float64 {
	if x != nil {
		return x.PositionLong
	}
	return 0
}

// StrengthSet represents a discrete set of an exercise (common in weightlifting)
// This is distinct from continuous Record streams.
type StrengthSet struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ExerciseName    string                 `protobuf:"bytes,1,opt,name=exercise_name,json=exerciseName,proto3" json:"exercise_name,omitempty"` // e.g. "Bench Press"
	Reps            int32                  `protobuf:"varint,2,opt,name=reps,proto3" json:"reps,omitempty"`
	WeightKg        float64                `protobuf:"fixed64,3,opt,name=weight_kg,json=weightKg,proto3" json:"weight_kg,omitempty"`
	StartTime       *timestamp.Timestamp   `protobuf:"bytes,4,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	DurationSeconds int32                  `protobuf:"varint,5,opt,name=duration_seconds,json=durationSeconds,proto3" json:"duration_seconds,omitempty"`
	Notes           string                 `protobuf:"bytes,6,opt,name=notes,proto3" json:"notes,omitempty"`
	// Organization
	SupersetId string `protobuf:"bytes,7,opt,name=superset_id,json=supersetId,proto3" json:"superset_id,omitempty"` // Group ID for supersets (if applicable)
	// Muscle Targeting
	PrimaryMuscleGroup    MuscleGroup   `protobuf:"varint,8,opt,name=primary_muscle_group,json=primaryMuscleGroup,proto3,enum=fitglue.MuscleGroup" json:"primary_muscle_group,omitempty"`
	SecondaryMuscleGroups []MuscleGroup `protobuf:"varint,9,rep,packed,name=secondary_muscle_groups,json=secondaryMuscleGroups,proto3,enum=fitglue.MuscleGroup" json:"secondary_muscle_groups,omitempty"`
	// Distance (for cardio/distance-based exercises)
	DistanceMeters float64 `protobuf:"fixed64,10,opt,name=distance_meters,json=distanceMeters,proto3" json:"distance_meters,omitempty"`
	// Set Type (warmup, normal, failure, dropset)
	SetType       string `protobuf:"bytes,11,opt,name=set_type,json=setType,proto3" json:"set_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StrengthSet) Reset() {
	*x = StrengthSet{}
	mi := &file_standardized_activity_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StrengthSet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StrengthSet) ProtoMessage() {}

func (x *StrengthSet) ProtoReflect() protoreflect.Message {
	mi := &file_standardized_activity_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StrengthSet.ProtoReflect.Descriptor instead.
func (*StrengthSet) Descriptor() ([]byte, []int) {
	return file_standardized_activity_proto_rawDescGZIP(), []int{4}
}

func (x *StrengthSet) GetExerciseName() string {
	if x != nil {
		return x.ExerciseName
	}
	return ""
}

func (x *StrengthSet) GetReps() int32 {
	if x != nil {
		return x.Reps
	}
	return 0
}

func (x *StrengthSet) GetWeightKg() float64 {
	if x != nil {
		return x.WeightKg
	}
	return 0
}

func (x *StrengthSet) GetStartTime() *timestamp.Timestamp {
	if x != nil {
		return x.StartTime
	}
	return nil
}

func (x *StrengthSet) GetDurationSeconds() int32 {
	if x != nil {
		return x.DurationSeconds
	}
	return 0
}

func (x *StrengthSet) GetNotes() string {
	if x != nil {
		return x.Notes
	}
	return ""
}

func (x *StrengthSet) GetSupersetId() string {
	if x != nil {
		return x.SupersetId
	}
	return ""
}

func (x *StrengthSet) GetPrimaryMuscleGroup() MuscleGroup {
	if x != nil {
		return x.PrimaryMuscleGroup
	}
	return MuscleGroup_MUSCLE_GROUP_UNSPECIFIED
}

func (x *StrengthSet) GetSecondaryMuscleGroups() []MuscleGroup {
	if x != nil {
		return x.SecondaryMuscleGroups
	}
	return nil
}

func (x *StrengthSet) GetDistanceMeters() float64 {
	if x != nil {
		return x.DistanceMeters
	}
	return 0
}

func (x *StrengthSet) GetSetType() string {
	if x != nil {
		return x.SetType
	}
	return ""
}

var file_standardized_activity_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptor.EnumValueOptions)(nil),
		ExtensionType: (*string)(nil),
		Field:         50010,
		Name:          "fitglue.strava_name",
		Tag:           "bytes,50010,opt,name=strava_name",
		Filename:      "standardized_activity.proto",
	},
}

// Extension fields to descriptor.EnumValueOptions.
var (
	// optional string strava_name = 50010;
	E_StravaName = &file_standardized_activity_proto_extTypes[0]
)

var File_standardized_activity_proto protoreflect.FileDescriptor

const file_standardized_activity_proto_rawDesc = "" +
	"\n" +
	"\x1bstandardized_activity.proto\x12\afitglue\x1a\x1fgoogle/protobuf/timestamp.proto\x1a google/protobuf/descriptor.proto\"\xdc\x02\n" +
	"\x14StandardizedActivity\x12\x16\n" +
	"\x06source\x18\x01 \x01(\tR\x06source\x12\x1f\n" +
	"\vexternal_id\x18\x02 \x01(\tR\n" +
	"externalId\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\tR\x06userId\x129\n" +
	"\n" +
	"start_time\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tstartTime\x12\x12\n" +
	"\x04name\x18\x05 \x01(\tR\x04name\x12)\n" +
	"\x04type\x18\x06 \x01(\x0e2\x15.fitglue.ActivityTypeR\x04type\x12,\n" +
	"\bsessions\x18\a \x03(\v2\x10.fitglue.SessionR\bsessions\x12 \n" +
	"\vdescription\x18\b \x01(\tR\vdescription\x12\x12\n" +
	"\x04tags\x18\t \x03(\tR\x04tags\x12\x14\n" +
	"\x05notes\x18\n" +
	" \x01(\tR\x05notes\"\xf6\x01\n" +
	"\aSession\x129\n" +
	"\n" +
	"start_time\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\tstartTime\x12,\n" +
	"\x12total_elapsed_time\x18\x02 \x01(\x01R\x10totalElapsedTime\x12%\n" +
	"\x0etotal_distance\x18\x03 \x01(\x01R\rtotalDistance\x12 \n" +
	"\x04laps\x18\x04 \x03(\v2\f.fitglue.LapR\x04laps\x129\n" +
	"\rstrength_sets\x18\x05 \x03(\v2\x14.fitglue.StrengthSetR\fstrengthSets\"\xc0\x01\n" +
	"\x03Lap\x129\n" +
	"\n" +
	"start_time\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\tstartTime\x12,\n" +
	"\x12total_elapsed_time\x18\x02 \x01(\x01R\x10totalElapsedTime\x12%\n" +
	"\x0etotal_distance\x18\x03 \x01(\x01R\rtotalDistance\x12)\n" +
	"\arecords\x18\x04 \x03(\v2\x0f.fitglue.RecordR\arecords\"\x8b\x02\n" +
	"\x06Record\x128\n" +
	"\ttimestamp\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12\x1d\n" +
	"\n" +
	"heart_rate\x18\x02 \x01(\x05R\theartRate\x12\x14\n" +
	"\x05power\x18\x03 \x01(\x05R\x05power\x12\x18\n" +
	"\acadence\x18\x04 \x01(\x05R\acadence\x12\x14\n" +
	"\x05speed\x18\x05 \x01(\x01R\x05speed\x12\x1a\n" +
	"\baltitude\x18\x06 \x01(\x01R\baltitude\x12!\n" +
	"\fposition_lat\x18\a \x01(\x01R\vpositionLat\x12#\n" +
	"\rposition_long\x18\b \x01(\x01R\fpositionLong\"\xda\x03\n" +
	"\vStrengthSet\x12#\n" +
	"\rexercise_name\x18\x01 \x01(\tR\fexerciseName\x12\x12\n" +
	"\x04reps\x18\x02 \x01(\x05R\x04reps\x12\x1b\n" +
	"\tweight_kg\x18\x03 \x01(\x01R\bweightKg\x129\n" +
	"\n" +
	"start_time\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tstartTime\x12)\n" +
	"\x10duration_seconds\x18\x05 \x01(\x05R\x0fdurationSeconds\x12\x14\n" +
	"\x05notes\x18\x06 \x01(\tR\x05notes\x12\x1f\n" +
	"\vsuperset_id\x18\a \x01(\tR\n" +
	"supersetId\x12F\n" +
	"\x14primary_muscle_group\x18\b \x01(\x0e2\x14.fitglue.MuscleGroupR\x12primaryMuscleGroup\x12L\n" +
	"\x17secondary_muscle_groups\x18\t \x03(\x0e2\x14.fitglue.MuscleGroupR\x15secondaryMuscleGroups\x12'\n" +
	"\x0fdistance_meters\x18\n" +
	" \x01(\x01R\x0edistanceMeters\x12\x19\n" +
	"\bset_type\x18\v \x01(\tR\asetType*\xea\x11\n" +
	"\fActivityType\x12\x1d\n" +
	"\x19ACTIVITY_TYPE_UNSPECIFIED\x10\x00\x12+\n" +
	"\x18ACTIVITY_TYPE_ALPINE_SKI\x10\x01\x1a\rҵ\x18\tAlpineSki\x125\n" +
	"\x1dACTIVITY_TYPE_BACKCOUNTRY_SKI\x10\x02\x1a\x12ҵ\x18\x0eBackcountrySki\x12*\n" +
	"\x17ACTIVITY_TYPE_BADMINTON\x10\x03\x1a\rҵ\x18\tBadminton\x12(\n" +
	"\x16ACTIVITY_TYPE_CANOEING\x10\x04\x1a\fҵ\x18\bCanoeing\x12(\n" +
	"\x16ACTIVITY_TYPE_CROSSFIT\x10\x05\x1a\fҵ\x18\bCrossfit\x12+\n" +
	"\x18ACTIVITY_TYPE_EBIKE_RIDE\x10\x06\x1a\rҵ\x18\tEBikeRide\x12,\n" +
	"\x18ACTIVITY_TYPE_ELLIPTICAL\x10\a\x1a\x0eҵ\x18\n" +
	"Elliptical\x12<\n" +
	"!ACTIVITY_TYPE_EMOUNTAIN_BIKE_RIDE\x10\b\x1a\x15ҵ\x18\x11EMountainBikeRide\x12 \n" +
	"\x12ACTIVITY_TYPE_GOLF\x10\t\x1a\bҵ\x18\x04Golf\x12-\n" +
	"\x19ACTIVITY_TYPE_GRAVEL_RIDE\x10\n" +
	"\x1a\x0eҵ\x18\n" +
	"GravelRide\x12*\n" +
	"\x17ACTIVITY_TYPE_HANDCYCLE\x10\v\x1a\rҵ\x18\tHandcycle\x12U\n" +
	".ACTIVITY_TYPE_HIGH_INTENSITY_INTERVAL_TRAINING\x10\f\x1a!ҵ\x18\x1dHighIntensityIntervalTraining\x12 \n" +
	"\x12ACTIVITY_TYPE_HIKE\x10\r\x1a\bҵ\x18\x04Hike\x12)\n" +
	"\x17ACTIVITY_TYPE_ICE_SKATE\x10\x0e\x1a\fҵ\x18\bIceSkate\x12/\n" +
	"\x1aACTIVITY_TYPE_INLINE_SKATE\x10\x0f\x1a\x0fҵ\x18\vInlineSkate\x12(\n" +
	"\x16ACTIVITY_TYPE_KAYAKING\x10\x10\x1a\fҵ\x18\bKayaking\x12(\n" +
	"\x16ACTIVITY_TYPE_KITESURF\x10\x11\x1a\fҵ\x18\bKitesurf\x12:\n" +
	" ACTIVITY_TYPE_MOUNTAIN_BIKE_RIDE\x10\x12\x1a\x14ҵ\x18\x10MountainBikeRide\x12+\n" +
	"\x18ACTIVITY_TYPE_NORDIC_SKI\x10\x13\x1a\rҵ\x18\tNordicSki\x12,\n" +
	"\x18ACTIVITY_TYPE_PICKLEBALL\x10\x14\x1a\x0eҵ\x18\n" +
	"Pickleball\x12&\n" +
	"\x15ACTIVITY_TYPE_PILATES\x10\x15\x1a\vҵ\x18\aPilates\x12.\n" +
	"\x19ACTIVITY_TYPE_RACQUETBALL\x10\x16\x1a\x0fҵ\x18\vRacquetball\x12 \n" +
	"\x12ACTIVITY_TYPE_RIDE\x10\x17\x1a\bҵ\x18\x04Ride\x121\n" +
	"\x1bACTIVITY_TYPE_ROCK_CLIMBING\x10\x18\x1a\x10ҵ\x18\fRockClimbing\x12+\n" +
	"\x18ACTIVITY_TYPE_ROLLER_SKI\x10\x19\x1a\rҵ\x18\tRollerSki\x12$\n" +
	"\x14ACTIVITY_TYPE_ROWING\x10\x1a\x1a\n" +
	"ҵ\x18\x06Rowing\x12\x1e\n" +
	"\x11ACTIVITY_TYPE_RUN\x10\x1b\x1a\aҵ\x18\x03Run\x12 \n" +
	"\x12ACTIVITY_TYPE_SAIL\x10\x1c\x1a\bҵ\x18\x04Sail\x12,\n" +
	"\x18ACTIVITY_TYPE_SKATEBOARD\x10\x1d\x1a\x0eҵ\x18\n" +
	"Skateboard\x12*\n" +
	"\x17ACTIVITY_TYPE_SNOWBOARD\x10\x1e\x1a\rҵ\x18\tSnowboard\x12(\n" +
	"\x16ACTIVITY_TYPE_SNOWSHOE\x10\x1f\x1a\fҵ\x18\bSnowshoe\x12$\n" +
	"\x14ACTIVITY_TYPE_SOCCER\x10 \x1a\n" +
	"ҵ\x18\x06Soccer\x12$\n" +
	"\x14ACTIVITY_TYPE_SQUASH\x10!\x1a\n" +
	"ҵ\x18\x06Squash\x121\n" +
	"\x1bACTIVITY_TYPE_STAIR_STEPPER\x10\"\x1a\x10ҵ\x18\fStairStepper\x128\n" +
	"\x1fACTIVITY_TYPE_STAND_UP_PADDLING\x10#\x1a\x13ҵ\x18\x0fStandUpPaddling\x12&\n" +
	"\x15ACTIVITY_TYPE_SURFING\x10$\x1a\vҵ\x18\aSurfing\x12 \n" +
	"\x12ACTIVITY_TYPE_SWIM\x10%\x1a\bҵ\x18\x04Swim\x12/\n" +
	"\x1aACTIVITY_TYPE_TABLE_TENNIS\x10&\x1a\x0fҵ\x18\vTableTennis\x12$\n" +
	"\x14ACTIVITY_TYPE_TENNIS\x10'\x1a\n" +
	"ҵ\x18\x06Tennis\x12)\n" +
	"\x17ACTIVITY_TYPE_TRAIL_RUN\x10(\x1a\fҵ\x18\bTrailRun\x12,\n" +
	"\x18ACTIVITY_TYPE_VELOMOBILE\x10)\x1a\x0eҵ\x18\n" +
	"Velomobile\x12/\n" +
	"\x1aACTIVITY_TYPE_VIRTUAL_RIDE\x10*\x1a\x0fҵ\x18\vVirtualRide\x12-\n" +
	"\x19ACTIVITY_TYPE_VIRTUAL_ROW\x10+\x1a\x0eҵ\x18\n" +
	"VirtualRow\x12-\n" +
	"\x19ACTIVITY_TYPE_VIRTUAL_RUN\x10,\x1a\x0eҵ\x18\n" +
	"VirtualRun\x12 \n" +
	"\x12ACTIVITY_TYPE_WALK\x10-\x1a\bҵ\x18\x04Walk\x125\n" +
	"\x1dACTIVITY_TYPE_WEIGHT_TRAINING\x10.\x1a\x12ҵ\x18\x0eWeightTraining\x12,\n" +
	"\x18ACTIVITY_TYPE_WHEELCHAIR\x10/\x1a\x0eҵ\x18\n" +
	"Wheelchair\x12(\n" +
	"\x16ACTIVITY_TYPE_WINDSURF\x100\x1a\fҵ\x18\bWindsurf\x12&\n" +
	"\x15ACTIVITY_TYPE_WORKOUT\x101\x1a\vҵ\x18\aWorkout\x12 \n" +
	"\x12ACTIVITY_TYPE_YOGA\x102\x1a\bҵ\x18\x04Yoga*\xbb\x04\n" +
	"\vMuscleGroup\x12\x1c\n" +
	"\x18MUSCLE_GROUP_UNSPECIFIED\x10\x00\x12\x1b\n" +
	"\x17MUSCLE_GROUP_ABDOMINALS\x10\x01\x12\x1a\n" +
	"\x16MUSCLE_GROUP_SHOULDERS\x10\x02\x12\x17\n" +
	"\x13MUSCLE_GROUP_BICEPS\x10\x03\x12\x18\n" +
	"\x14MUSCLE_GROUP_TRICEPS\x10\x04\x12\x19\n" +
	"\x15MUSCLE_GROUP_FOREARMS\x10\x05\x12\x1b\n" +
	"\x17MUSCLE_GROUP_QUADRICEPS\x10\x06\x12\x1b\n" +
	"\x17MUSCLE_GROUP_HAMSTRINGS\x10\a\x12\x17\n" +
	"\x13MUSCLE_GROUP_CALVES\x10\b\x12\x17\n" +
	"\x13MUSCLE_GROUP_GLUTES\x10\t\x12\x1a\n" +
	"\x16MUSCLE_GROUP_ABDUCTORS\x10\n" +
	"\x12\x1a\n" +
	"\x16MUSCLE_GROUP_ADDUCTORS\x10\v\x12\x15\n" +
	"\x11MUSCLE_GROUP_LATS\x10\f\x12\x1b\n" +
	"\x17MUSCLE_GROUP_UPPER_BACK\x10\r\x12\x16\n" +
	"\x12MUSCLE_GROUP_TRAPS\x10\x0e\x12\x1b\n" +
	"\x17MUSCLE_GROUP_LOWER_BACK\x10\x0f\x12\x16\n" +
	"\x12MUSCLE_GROUP_CHEST\x10\x10\x12\x17\n" +
	"\x13MUSCLE_GROUP_CARDIO\x10\x11\x12\x15\n" +
	"\x11MUSCLE_GROUP_NECK\x10\x12\x12\x1a\n" +
	"\x16MUSCLE_GROUP_FULL_BODY\x10\x13\x12\x16\n" +
	"\x12MUSCLE_GROUP_OTHER\x10\x14:D\n" +
	"\vstrava_name\x12!.google.protobuf.EnumValueOptions\x18چ\x03 \x01(\tR\n" +
	"stravaNameB\x17Z\x15fitglue/pkg/shared/pbb\x06proto3"

var (
	file_standardized_activity_proto_rawDescOnce sync.Once
	file_standardized_activity_proto_rawDescData []byte
)

func file_standardized_activity_proto_rawDescGZIP() []byte {
	file_standardized_activity_proto_rawDescOnce.Do(func() {
		file_standardized_activity_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_standardized_activity_proto_rawDesc), len(file_standardized_activity_proto_rawDesc)))
	})
	return file_standardized_activity_proto_rawDescData
}

var file_standardized_activity_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_standardized_activity_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_standardized_activity_proto_goTypes = []any{
	(ActivityType)(0),                   // 0: fitglue.ActivityType
	(MuscleGroup)(0),                    // 1: fitglue.MuscleGroup
	(*StandardizedActivity)(nil),        // 2: fitglue.StandardizedActivity
	(*Session)(nil),                     // 3: fitglue.Session
	(*Lap)(nil),                         // 4: fitglue.Lap
	(*Record)(nil),                      // 5: fitglue.Record
	(*StrengthSet)(nil),                 // 6: fitglue.StrengthSet
	(*timestamp.Timestamp)(nil),         // 7: google.protobuf.Timestamp
	(*descriptor.EnumValueOptions)(nil), // 8: google.protobuf.EnumValueOptions
}
var file_standardized_activity_proto_depIdxs = []int32{
	7,  // 0: fitglue.StandardizedActivity.start_time:type_name -> google.protobuf.Timestamp
	0,  // 1: fitglue.StandardizedActivity.type:type_name -> fitglue.ActivityType
	3,  // 2: fitglue.StandardizedActivity.sessions:type_name -> fitglue.Session
	7,  // 3: fitglue.Session.start_time:type_name -> google.protobuf.Timestamp
	4,  // 4: fitglue.Session.laps:type_name -> fitglue.Lap
	6,  // 5: fitglue.Session.strength_sets:type_name -> fitglue.StrengthSet
	7,  // 6: fitglue.Lap.start_time:type_name -> google.protobuf.Timestamp
	5,  // 7: fitglue.Lap.records:type_name -> fitglue.Record
	7,  // 8: fitglue.Record.timestamp:type_name -> google.protobuf.Timestamp
	7,  // 9: fitglue.StrengthSet.start_time:type_name -> google.protobuf.Timestamp
	1,  // 10: fitglue.StrengthSet.primary_muscle_group:type_name -> fitglue.MuscleGroup
	1,  // 11: fitglue.StrengthSet.secondary_muscle_groups:type_name -> fitglue.MuscleGroup
	8,  // 12: fitglue.strava_name:extendee -> google.protobuf.EnumValueOptions
	13, // [13:13] is the sub-list for method output_type
	13, // [13:13] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	12, // [12:13] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_standardized_activity_proto_init() }
func file_standardized_activity_proto_init() {
	if File_standardized_activity_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_standardized_activity_proto_rawDesc), len(file_standardized_activity_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   5,
			NumExtensions: 1,
			NumServices:   0,
		},
		GoTypes:           file_standardized_activity_proto_goTypes,
		DependencyIndexes: file_standardized_activity_proto_depIdxs,
		EnumInfos:         file_standardized_activity_proto_enumTypes,
		MessageInfos:      file_standardized_activity_proto_msgTypes,
		ExtensionInfos:    file_standardized_activity_proto_extTypes,
	}.Build()
	File_standardized_activity_proto = out.File
	file_standardized_activity_proto_goTypes = nil
	file_standardized_activity_proto_depIdxs = nil
}
