// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.12.4
// source: standardized_activity.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MuscleGroup int32

const (
	MuscleGroup_MUSCLE_GROUP_UNSPECIFIED MuscleGroup = 0
	MuscleGroup_MUSCLE_GROUP_ABDOMINALS  MuscleGroup = 1
	MuscleGroup_MUSCLE_GROUP_SHOULDERS   MuscleGroup = 2
	MuscleGroup_MUSCLE_GROUP_BICEPS      MuscleGroup = 3
	MuscleGroup_MUSCLE_GROUP_TRICEPS     MuscleGroup = 4
	MuscleGroup_MUSCLE_GROUP_FOREARMS    MuscleGroup = 5
	MuscleGroup_MUSCLE_GROUP_QUADRICEPS  MuscleGroup = 6
	MuscleGroup_MUSCLE_GROUP_HAMSTRINGS  MuscleGroup = 7
	MuscleGroup_MUSCLE_GROUP_CALVES      MuscleGroup = 8
	MuscleGroup_MUSCLE_GROUP_GLUTES      MuscleGroup = 9
	MuscleGroup_MUSCLE_GROUP_ABDUCTORS   MuscleGroup = 10
	MuscleGroup_MUSCLE_GROUP_ADDUCTORS   MuscleGroup = 11
	MuscleGroup_MUSCLE_GROUP_LATS        MuscleGroup = 12
	MuscleGroup_MUSCLE_GROUP_UPPER_BACK  MuscleGroup = 13
	MuscleGroup_MUSCLE_GROUP_TRAPS       MuscleGroup = 14
	MuscleGroup_MUSCLE_GROUP_LOWER_BACK  MuscleGroup = 15
	MuscleGroup_MUSCLE_GROUP_CHEST       MuscleGroup = 16
	MuscleGroup_MUSCLE_GROUP_CARDIO      MuscleGroup = 17
	MuscleGroup_MUSCLE_GROUP_NECK        MuscleGroup = 18
	MuscleGroup_MUSCLE_GROUP_FULL_BODY   MuscleGroup = 19
	MuscleGroup_MUSCLE_GROUP_OTHER       MuscleGroup = 20
)

// Enum value maps for MuscleGroup.
var (
	MuscleGroup_name = map[int32]string{
		0:  "MUSCLE_GROUP_UNSPECIFIED",
		1:  "MUSCLE_GROUP_ABDOMINALS",
		2:  "MUSCLE_GROUP_SHOULDERS",
		3:  "MUSCLE_GROUP_BICEPS",
		4:  "MUSCLE_GROUP_TRICEPS",
		5:  "MUSCLE_GROUP_FOREARMS",
		6:  "MUSCLE_GROUP_QUADRICEPS",
		7:  "MUSCLE_GROUP_HAMSTRINGS",
		8:  "MUSCLE_GROUP_CALVES",
		9:  "MUSCLE_GROUP_GLUTES",
		10: "MUSCLE_GROUP_ABDUCTORS",
		11: "MUSCLE_GROUP_ADDUCTORS",
		12: "MUSCLE_GROUP_LATS",
		13: "MUSCLE_GROUP_UPPER_BACK",
		14: "MUSCLE_GROUP_TRAPS",
		15: "MUSCLE_GROUP_LOWER_BACK",
		16: "MUSCLE_GROUP_CHEST",
		17: "MUSCLE_GROUP_CARDIO",
		18: "MUSCLE_GROUP_NECK",
		19: "MUSCLE_GROUP_FULL_BODY",
		20: "MUSCLE_GROUP_OTHER",
	}
	MuscleGroup_value = map[string]int32{
		"MUSCLE_GROUP_UNSPECIFIED": 0,
		"MUSCLE_GROUP_ABDOMINALS":  1,
		"MUSCLE_GROUP_SHOULDERS":   2,
		"MUSCLE_GROUP_BICEPS":      3,
		"MUSCLE_GROUP_TRICEPS":     4,
		"MUSCLE_GROUP_FOREARMS":    5,
		"MUSCLE_GROUP_QUADRICEPS":  6,
		"MUSCLE_GROUP_HAMSTRINGS":  7,
		"MUSCLE_GROUP_CALVES":      8,
		"MUSCLE_GROUP_GLUTES":      9,
		"MUSCLE_GROUP_ABDUCTORS":   10,
		"MUSCLE_GROUP_ADDUCTORS":   11,
		"MUSCLE_GROUP_LATS":        12,
		"MUSCLE_GROUP_UPPER_BACK":  13,
		"MUSCLE_GROUP_TRAPS":       14,
		"MUSCLE_GROUP_LOWER_BACK":  15,
		"MUSCLE_GROUP_CHEST":       16,
		"MUSCLE_GROUP_CARDIO":      17,
		"MUSCLE_GROUP_NECK":        18,
		"MUSCLE_GROUP_FULL_BODY":   19,
		"MUSCLE_GROUP_OTHER":       20,
	}
)

func (x MuscleGroup) Enum() *MuscleGroup {
	p := new(MuscleGroup)
	*p = x
	return p
}

func (x MuscleGroup) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MuscleGroup) Descriptor() protoreflect.EnumDescriptor {
	return file_standardized_activity_proto_enumTypes[0].Descriptor()
}

func (MuscleGroup) Type() protoreflect.EnumType {
	return &file_standardized_activity_proto_enumTypes[0]
}

func (x MuscleGroup) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MuscleGroup.Descriptor instead.
func (MuscleGroup) EnumDescriptor() ([]byte, []int) {
	return file_standardized_activity_proto_rawDescGZIP(), []int{0}
}

// StandardizedActivity represents a normalized fitness activity.
// It is designed to be the canonical input format for the Enricher,
// decoupling it from specific ingestion sources (Hevy, Keiser, etc).
//
// Structure mimics the FIT SDK hierarchy:
// Activity -> Sessions -> Laps -> Records
type StandardizedActivity struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	Source     string                 `protobuf:"bytes,1,opt,name=source,proto3" json:"source,omitempty"`                           // e.g. "HEVY", "KEISER"
	ExternalId string                 `protobuf:"bytes,2,opt,name=external_id,json=externalId,proto3" json:"external_id,omitempty"` // Source's ID (e.g. Hevy workout ID)
	UserId     string                 `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	// High-level summary
	StartTime string `protobuf:"bytes,4,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"` // ISO 8601 Timestamp
	Name      string `protobuf:"bytes,5,opt,name=name,proto3" json:"name,omitempty"`                            // e.g. "Morning Run"
	Type      string `protobuf:"bytes,6,opt,name=type,proto3" json:"type,omitempty"`                            // e.g. "RUNNING", "CYCLING", "WEIGHT_TRAINING"
	// Hierarchy
	Sessions []*Session `protobuf:"bytes,7,rep,name=sessions,proto3" json:"sessions,omitempty"`
	// Rich metadata (preserved from source)
	Description   string   `protobuf:"bytes,8,opt,name=description,proto3" json:"description,omitempty"` // User notes
	Tags          []string `protobuf:"bytes,9,rep,name=tags,proto3" json:"tags,omitempty"`
	Notes         string   `protobuf:"bytes,10,opt,name=notes,proto3" json:"notes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StandardizedActivity) Reset() {
	*x = StandardizedActivity{}
	mi := &file_standardized_activity_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StandardizedActivity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StandardizedActivity) ProtoMessage() {}

func (x *StandardizedActivity) ProtoReflect() protoreflect.Message {
	mi := &file_standardized_activity_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StandardizedActivity.ProtoReflect.Descriptor instead.
func (*StandardizedActivity) Descriptor() ([]byte, []int) {
	return file_standardized_activity_proto_rawDescGZIP(), []int{0}
}

func (x *StandardizedActivity) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *StandardizedActivity) GetExternalId() string {
	if x != nil {
		return x.ExternalId
	}
	return ""
}

func (x *StandardizedActivity) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *StandardizedActivity) GetStartTime() string {
	if x != nil {
		return x.StartTime
	}
	return ""
}

func (x *StandardizedActivity) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *StandardizedActivity) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *StandardizedActivity) GetSessions() []*Session {
	if x != nil {
		return x.Sessions
	}
	return nil
}

func (x *StandardizedActivity) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *StandardizedActivity) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *StandardizedActivity) GetNotes() string {
	if x != nil {
		return x.Notes
	}
	return ""
}

type Session struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	StartTime        string                 `protobuf:"bytes,1,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	TotalElapsedTime float64                `protobuf:"fixed64,2,opt,name=total_elapsed_time,json=totalElapsedTime,proto3" json:"total_elapsed_time,omitempty"` // seconds
	TotalDistance    float64                `protobuf:"fixed64,3,opt,name=total_distance,json=totalDistance,proto3" json:"total_distance,omitempty"`            // meters
	Laps             []*Lap                 `protobuf:"bytes,4,rep,name=laps,proto3" json:"laps,omitempty"`
	// High-fidelity strength data (not just 1Hz streams)
	StrengthSets  []*StrengthSet `protobuf:"bytes,5,rep,name=strength_sets,json=strengthSets,proto3" json:"strength_sets,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Session) Reset() {
	*x = Session{}
	mi := &file_standardized_activity_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Session) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Session) ProtoMessage() {}

func (x *Session) ProtoReflect() protoreflect.Message {
	mi := &file_standardized_activity_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Session.ProtoReflect.Descriptor instead.
func (*Session) Descriptor() ([]byte, []int) {
	return file_standardized_activity_proto_rawDescGZIP(), []int{1}
}

func (x *Session) GetStartTime() string {
	if x != nil {
		return x.StartTime
	}
	return ""
}

func (x *Session) GetTotalElapsedTime() float64 {
	if x != nil {
		return x.TotalElapsedTime
	}
	return 0
}

func (x *Session) GetTotalDistance() float64 {
	if x != nil {
		return x.TotalDistance
	}
	return 0
}

func (x *Session) GetLaps() []*Lap {
	if x != nil {
		return x.Laps
	}
	return nil
}

func (x *Session) GetStrengthSets() []*StrengthSet {
	if x != nil {
		return x.StrengthSets
	}
	return nil
}

type Lap struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	StartTime        string                 `protobuf:"bytes,1,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	TotalElapsedTime float64                `protobuf:"fixed64,2,opt,name=total_elapsed_time,json=totalElapsedTime,proto3" json:"total_elapsed_time,omitempty"` // seconds
	TotalDistance    float64                `protobuf:"fixed64,3,opt,name=total_distance,json=totalDistance,proto3" json:"total_distance,omitempty"`            // meters
	Records          []*Record              `protobuf:"bytes,4,rep,name=records,proto3" json:"records,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Lap) Reset() {
	*x = Lap{}
	mi := &file_standardized_activity_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Lap) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Lap) ProtoMessage() {}

func (x *Lap) ProtoReflect() protoreflect.Message {
	mi := &file_standardized_activity_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Lap.ProtoReflect.Descriptor instead.
func (*Lap) Descriptor() ([]byte, []int) {
	return file_standardized_activity_proto_rawDescGZIP(), []int{2}
}

func (x *Lap) GetStartTime() string {
	if x != nil {
		return x.StartTime
	}
	return ""
}

func (x *Lap) GetTotalElapsedTime() float64 {
	if x != nil {
		return x.TotalElapsedTime
	}
	return 0
}

func (x *Lap) GetTotalDistance() float64 {
	if x != nil {
		return x.TotalDistance
	}
	return 0
}

func (x *Lap) GetRecords() []*Record {
	if x != nil {
		return x.Records
	}
	return nil
}

// Record represents a single data point in time (1Hz is typical)
type Record struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Timestamp string                 `protobuf:"bytes,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"` // ISO 8601
	// Core Telemetry
	HeartRate int32   `protobuf:"varint,2,opt,name=heart_rate,json=heartRate,proto3" json:"heart_rate,omitempty"` // bpm
	Power     int32   `protobuf:"varint,3,opt,name=power,proto3" json:"power,omitempty"`                          // watts
	Cadence   int32   `protobuf:"varint,4,opt,name=cadence,proto3" json:"cadence,omitempty"`                      // rpm
	Speed     float64 `protobuf:"fixed64,5,opt,name=speed,proto3" json:"speed,omitempty"`                         // m/s
	Altitude  float64 `protobuf:"fixed64,6,opt,name=altitude,proto3" json:"altitude,omitempty"`                   // meters
	// Location
	PositionLat   float64 `protobuf:"fixed64,7,opt,name=position_lat,json=positionLat,proto3" json:"position_lat,omitempty"`
	PositionLong  float64 `protobuf:"fixed64,8,opt,name=position_long,json=positionLong,proto3" json:"position_long,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Record) Reset() {
	*x = Record{}
	mi := &file_standardized_activity_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Record) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Record) ProtoMessage() {}

func (x *Record) ProtoReflect() protoreflect.Message {
	mi := &file_standardized_activity_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Record.ProtoReflect.Descriptor instead.
func (*Record) Descriptor() ([]byte, []int) {
	return file_standardized_activity_proto_rawDescGZIP(), []int{3}
}

func (x *Record) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

func (x *Record) GetHeartRate() int32 {
	if x != nil {
		return x.HeartRate
	}
	return 0
}

func (x *Record) GetPower() int32 {
	if x != nil {
		return x.Power
	}
	return 0
}

func (x *Record) GetCadence() int32 {
	if x != nil {
		return x.Cadence
	}
	return 0
}

func (x *Record) GetSpeed() float64 {
	if x != nil {
		return x.Speed
	}
	return 0
}

func (x *Record) GetAltitude() float64 {
	if x != nil {
		return x.Altitude
	}
	return 0
}

func (x *Record) GetPositionLat() float64 {
	if x != nil {
		return x.PositionLat
	}
	return 0
}

func (x *Record) GetPositionLong() float64 {
	if x != nil {
		return x.PositionLong
	}
	return 0
}

// StrengthSet represents a discrete set of an exercise (common in weightlifting)
// This is distinct from continuous Record streams.
type StrengthSet struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ExerciseName    string                 `protobuf:"bytes,1,opt,name=exercise_name,json=exerciseName,proto3" json:"exercise_name,omitempty"` // e.g. "Bench Press"
	Reps            int32                  `protobuf:"varint,2,opt,name=reps,proto3" json:"reps,omitempty"`
	WeightKg        float64                `protobuf:"fixed64,3,opt,name=weight_kg,json=weightKg,proto3" json:"weight_kg,omitempty"`
	StartTime       string                 `protobuf:"bytes,4,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"` // ISO 8601
	DurationSeconds int32                  `protobuf:"varint,5,opt,name=duration_seconds,json=durationSeconds,proto3" json:"duration_seconds,omitempty"`
	Notes           string                 `protobuf:"bytes,6,opt,name=notes,proto3" json:"notes,omitempty"`
	// Organization
	SupersetId string `protobuf:"bytes,7,opt,name=superset_id,json=supersetId,proto3" json:"superset_id,omitempty"` // Group ID for supersets (if applicable)
	// Muscle Targeting
	PrimaryMuscleGroup    MuscleGroup   `protobuf:"varint,8,opt,name=primary_muscle_group,json=primaryMuscleGroup,proto3,enum=fitglue.MuscleGroup" json:"primary_muscle_group,omitempty"`
	SecondaryMuscleGroups []MuscleGroup `protobuf:"varint,9,rep,packed,name=secondary_muscle_groups,json=secondaryMuscleGroups,proto3,enum=fitglue.MuscleGroup" json:"secondary_muscle_groups,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *StrengthSet) Reset() {
	*x = StrengthSet{}
	mi := &file_standardized_activity_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StrengthSet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StrengthSet) ProtoMessage() {}

func (x *StrengthSet) ProtoReflect() protoreflect.Message {
	mi := &file_standardized_activity_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StrengthSet.ProtoReflect.Descriptor instead.
func (*StrengthSet) Descriptor() ([]byte, []int) {
	return file_standardized_activity_proto_rawDescGZIP(), []int{4}
}

func (x *StrengthSet) GetExerciseName() string {
	if x != nil {
		return x.ExerciseName
	}
	return ""
}

func (x *StrengthSet) GetReps() int32 {
	if x != nil {
		return x.Reps
	}
	return 0
}

func (x *StrengthSet) GetWeightKg() float64 {
	if x != nil {
		return x.WeightKg
	}
	return 0
}

func (x *StrengthSet) GetStartTime() string {
	if x != nil {
		return x.StartTime
	}
	return ""
}

func (x *StrengthSet) GetDurationSeconds() int32 {
	if x != nil {
		return x.DurationSeconds
	}
	return 0
}

func (x *StrengthSet) GetNotes() string {
	if x != nil {
		return x.Notes
	}
	return ""
}

func (x *StrengthSet) GetSupersetId() string {
	if x != nil {
		return x.SupersetId
	}
	return ""
}

func (x *StrengthSet) GetPrimaryMuscleGroup() MuscleGroup {
	if x != nil {
		return x.PrimaryMuscleGroup
	}
	return MuscleGroup_MUSCLE_GROUP_UNSPECIFIED
}

func (x *StrengthSet) GetSecondaryMuscleGroups() []MuscleGroup {
	if x != nil {
		return x.SecondaryMuscleGroups
	}
	return nil
}

var File_standardized_activity_proto protoreflect.FileDescriptor

const file_standardized_activity_proto_rawDesc = "" +
	"\n" +
	"\x1bstandardized_activity.proto\x12\afitglue\"\xa9\x02\n" +
	"\x14StandardizedActivity\x12\x16\n" +
	"\x06source\x18\x01 \x01(\tR\x06source\x12\x1f\n" +
	"\vexternal_id\x18\x02 \x01(\tR\n" +
	"externalId\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\tR\x06userId\x12\x1d\n" +
	"\n" +
	"start_time\x18\x04 \x01(\tR\tstartTime\x12\x12\n" +
	"\x04name\x18\x05 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x06 \x01(\tR\x04type\x12,\n" +
	"\bsessions\x18\a \x03(\v2\x10.fitglue.SessionR\bsessions\x12 \n" +
	"\vdescription\x18\b \x01(\tR\vdescription\x12\x12\n" +
	"\x04tags\x18\t \x03(\tR\x04tags\x12\x14\n" +
	"\x05notes\x18\n" +
	" \x01(\tR\x05notes\"\xda\x01\n" +
	"\aSession\x12\x1d\n" +
	"\n" +
	"start_time\x18\x01 \x01(\tR\tstartTime\x12,\n" +
	"\x12total_elapsed_time\x18\x02 \x01(\x01R\x10totalElapsedTime\x12%\n" +
	"\x0etotal_distance\x18\x03 \x01(\x01R\rtotalDistance\x12 \n" +
	"\x04laps\x18\x04 \x03(\v2\f.fitglue.LapR\x04laps\x129\n" +
	"\rstrength_sets\x18\x05 \x03(\v2\x14.fitglue.StrengthSetR\fstrengthSets\"\xa4\x01\n" +
	"\x03Lap\x12\x1d\n" +
	"\n" +
	"start_time\x18\x01 \x01(\tR\tstartTime\x12,\n" +
	"\x12total_elapsed_time\x18\x02 \x01(\x01R\x10totalElapsedTime\x12%\n" +
	"\x0etotal_distance\x18\x03 \x01(\x01R\rtotalDistance\x12)\n" +
	"\arecords\x18\x04 \x03(\v2\x0f.fitglue.RecordR\arecords\"\xef\x01\n" +
	"\x06Record\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\tR\ttimestamp\x12\x1d\n" +
	"\n" +
	"heart_rate\x18\x02 \x01(\x05R\theartRate\x12\x14\n" +
	"\x05power\x18\x03 \x01(\x05R\x05power\x12\x18\n" +
	"\acadence\x18\x04 \x01(\x05R\acadence\x12\x14\n" +
	"\x05speed\x18\x05 \x01(\x01R\x05speed\x12\x1a\n" +
	"\baltitude\x18\x06 \x01(\x01R\baltitude\x12!\n" +
	"\fposition_lat\x18\a \x01(\x01R\vpositionLat\x12#\n" +
	"\rposition_long\x18\b \x01(\x01R\fpositionLong\"\xfa\x02\n" +
	"\vStrengthSet\x12#\n" +
	"\rexercise_name\x18\x01 \x01(\tR\fexerciseName\x12\x12\n" +
	"\x04reps\x18\x02 \x01(\x05R\x04reps\x12\x1b\n" +
	"\tweight_kg\x18\x03 \x01(\x01R\bweightKg\x12\x1d\n" +
	"\n" +
	"start_time\x18\x04 \x01(\tR\tstartTime\x12)\n" +
	"\x10duration_seconds\x18\x05 \x01(\x05R\x0fdurationSeconds\x12\x14\n" +
	"\x05notes\x18\x06 \x01(\tR\x05notes\x12\x1f\n" +
	"\vsuperset_id\x18\a \x01(\tR\n" +
	"supersetId\x12F\n" +
	"\x14primary_muscle_group\x18\b \x01(\x0e2\x14.fitglue.MuscleGroupR\x12primaryMuscleGroup\x12L\n" +
	"\x17secondary_muscle_groups\x18\t \x03(\x0e2\x14.fitglue.MuscleGroupR\x15secondaryMuscleGroups*\xbb\x04\n" +
	"\vMuscleGroup\x12\x1c\n" +
	"\x18MUSCLE_GROUP_UNSPECIFIED\x10\x00\x12\x1b\n" +
	"\x17MUSCLE_GROUP_ABDOMINALS\x10\x01\x12\x1a\n" +
	"\x16MUSCLE_GROUP_SHOULDERS\x10\x02\x12\x17\n" +
	"\x13MUSCLE_GROUP_BICEPS\x10\x03\x12\x18\n" +
	"\x14MUSCLE_GROUP_TRICEPS\x10\x04\x12\x19\n" +
	"\x15MUSCLE_GROUP_FOREARMS\x10\x05\x12\x1b\n" +
	"\x17MUSCLE_GROUP_QUADRICEPS\x10\x06\x12\x1b\n" +
	"\x17MUSCLE_GROUP_HAMSTRINGS\x10\a\x12\x17\n" +
	"\x13MUSCLE_GROUP_CALVES\x10\b\x12\x17\n" +
	"\x13MUSCLE_GROUP_GLUTES\x10\t\x12\x1a\n" +
	"\x16MUSCLE_GROUP_ABDUCTORS\x10\n" +
	"\x12\x1a\n" +
	"\x16MUSCLE_GROUP_ADDUCTORS\x10\v\x12\x15\n" +
	"\x11MUSCLE_GROUP_LATS\x10\f\x12\x1b\n" +
	"\x17MUSCLE_GROUP_UPPER_BACK\x10\r\x12\x16\n" +
	"\x12MUSCLE_GROUP_TRAPS\x10\x0e\x12\x1b\n" +
	"\x17MUSCLE_GROUP_LOWER_BACK\x10\x0f\x12\x16\n" +
	"\x12MUSCLE_GROUP_CHEST\x10\x10\x12\x17\n" +
	"\x13MUSCLE_GROUP_CARDIO\x10\x11\x12\x15\n" +
	"\x11MUSCLE_GROUP_NECK\x10\x12\x12\x1a\n" +
	"\x16MUSCLE_GROUP_FULL_BODY\x10\x13\x12\x16\n" +
	"\x12MUSCLE_GROUP_OTHER\x10\x14B\x17Z\x15fitglue/pkg/shared/pbb\x06proto3"

var (
	file_standardized_activity_proto_rawDescOnce sync.Once
	file_standardized_activity_proto_rawDescData []byte
)

func file_standardized_activity_proto_rawDescGZIP() []byte {
	file_standardized_activity_proto_rawDescOnce.Do(func() {
		file_standardized_activity_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_standardized_activity_proto_rawDesc), len(file_standardized_activity_proto_rawDesc)))
	})
	return file_standardized_activity_proto_rawDescData
}

var file_standardized_activity_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_standardized_activity_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_standardized_activity_proto_goTypes = []any{
	(MuscleGroup)(0),             // 0: fitglue.MuscleGroup
	(*StandardizedActivity)(nil), // 1: fitglue.StandardizedActivity
	(*Session)(nil),              // 2: fitglue.Session
	(*Lap)(nil),                  // 3: fitglue.Lap
	(*Record)(nil),               // 4: fitglue.Record
	(*StrengthSet)(nil),          // 5: fitglue.StrengthSet
}
var file_standardized_activity_proto_depIdxs = []int32{
	2, // 0: fitglue.StandardizedActivity.sessions:type_name -> fitglue.Session
	3, // 1: fitglue.Session.laps:type_name -> fitglue.Lap
	5, // 2: fitglue.Session.strength_sets:type_name -> fitglue.StrengthSet
	4, // 3: fitglue.Lap.records:type_name -> fitglue.Record
	0, // 4: fitglue.StrengthSet.primary_muscle_group:type_name -> fitglue.MuscleGroup
	0, // 5: fitglue.StrengthSet.secondary_muscle_groups:type_name -> fitglue.MuscleGroup
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_standardized_activity_proto_init() }
func file_standardized_activity_proto_init() {
	if File_standardized_activity_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_standardized_activity_proto_rawDesc), len(file_standardized_activity_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_standardized_activity_proto_goTypes,
		DependencyIndexes: file_standardized_activity_proto_depIdxs,
		EnumInfos:         file_standardized_activity_proto_enumTypes,
		MessageInfos:      file_standardized_activity_proto_msgTypes,
	}.Build()
	File_standardized_activity_proto = out.File
	file_standardized_activity_proto_goTypes = nil
	file_standardized_activity_proto_depIdxs = nil
}
