// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.12.4
// source: user.proto

package pb

import (
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EnricherProviderType int32

const (
	EnricherProviderType_ENRICHER_PROVIDER_UNSPECIFIED          EnricherProviderType = 0
	EnricherProviderType_ENRICHER_PROVIDER_FITBIT_HEART_RATE    EnricherProviderType = 1
	EnricherProviderType_ENRICHER_PROVIDER_WORKOUT_SUMMARY      EnricherProviderType = 2
	EnricherProviderType_ENRICHER_PROVIDER_MUSCLE_HEATMAP       EnricherProviderType = 3
	EnricherProviderType_ENRICHER_PROVIDER_SOURCE_LINK          EnricherProviderType = 4
	EnricherProviderType_ENRICHER_PROVIDER_METADATA_PASSTHROUGH EnricherProviderType = 5
	EnricherProviderType_ENRICHER_PROVIDER_VIRTUAL_GPS          EnricherProviderType = 6
	EnricherProviderType_ENRICHER_PROVIDER_MOCK                 EnricherProviderType = 99
)

// Enum value maps for EnricherProviderType.
var (
	EnricherProviderType_name = map[int32]string{
		0:  "ENRICHER_PROVIDER_UNSPECIFIED",
		1:  "ENRICHER_PROVIDER_FITBIT_HEART_RATE",
		2:  "ENRICHER_PROVIDER_WORKOUT_SUMMARY",
		3:  "ENRICHER_PROVIDER_MUSCLE_HEATMAP",
		4:  "ENRICHER_PROVIDER_SOURCE_LINK",
		5:  "ENRICHER_PROVIDER_METADATA_PASSTHROUGH",
		6:  "ENRICHER_PROVIDER_VIRTUAL_GPS",
		99: "ENRICHER_PROVIDER_MOCK",
	}
	EnricherProviderType_value = map[string]int32{
		"ENRICHER_PROVIDER_UNSPECIFIED":          0,
		"ENRICHER_PROVIDER_FITBIT_HEART_RATE":    1,
		"ENRICHER_PROVIDER_WORKOUT_SUMMARY":      2,
		"ENRICHER_PROVIDER_MUSCLE_HEATMAP":       3,
		"ENRICHER_PROVIDER_SOURCE_LINK":          4,
		"ENRICHER_PROVIDER_METADATA_PASSTHROUGH": 5,
		"ENRICHER_PROVIDER_VIRTUAL_GPS":          6,
		"ENRICHER_PROVIDER_MOCK":                 99,
	}
)

func (x EnricherProviderType) Enum() *EnricherProviderType {
	p := new(EnricherProviderType)
	*p = x
	return p
}

func (x EnricherProviderType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EnricherProviderType) Descriptor() protoreflect.EnumDescriptor {
	return file_user_proto_enumTypes[0].Descriptor()
}

func (EnricherProviderType) Type() protoreflect.EnumType {
	return &file_user_proto_enumTypes[0]
}

func (x EnricherProviderType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EnricherProviderType.Descriptor instead.
func (EnricherProviderType) EnumDescriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{0}
}

type UserRecord struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	UserId       string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	CreatedAt    *timestamp.Timestamp   `protobuf:"bytes,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	Integrations *UserIntegrations      `protobuf:"bytes,3,opt,name=integrations,proto3" json:"integrations,omitempty"`
	// Pipelines define the data flow: Source -> Enrichers -> Routing
	Pipelines     []*PipelineConfig `protobuf:"bytes,4,rep,name=pipelines,proto3" json:"pipelines,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserRecord) Reset() {
	*x = UserRecord{}
	mi := &file_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserRecord) ProtoMessage() {}

func (x *UserRecord) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserRecord.ProtoReflect.Descriptor instead.
func (*UserRecord) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{0}
}

func (x *UserRecord) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UserRecord) GetCreatedAt() *timestamp.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *UserRecord) GetIntegrations() *UserIntegrations {
	if x != nil {
		return x.Integrations
	}
	return nil
}

func (x *UserRecord) GetPipelines() []*PipelineConfig {
	if x != nil {
		return x.Pipelines
	}
	return nil
}

type PipelineConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`         // Unique ID (uuid) for tracing
	Source        string                 `protobuf:"bytes,2,opt,name=source,proto3" json:"source,omitempty"` // e.g. "SOURCE_HEVY"
	Enrichers     []*EnricherConfig      `protobuf:"bytes,3,rep,name=enrichers,proto3" json:"enrichers,omitempty"`
	Destinations  []string               `protobuf:"bytes,4,rep,name=destinations,proto3" json:"destinations,omitempty"` // e.g. ["strava", "gcs"]
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PipelineConfig) Reset() {
	*x = PipelineConfig{}
	mi := &file_user_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PipelineConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PipelineConfig) ProtoMessage() {}

func (x *PipelineConfig) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PipelineConfig.ProtoReflect.Descriptor instead.
func (*PipelineConfig) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{1}
}

func (x *PipelineConfig) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PipelineConfig) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *PipelineConfig) GetEnrichers() []*EnricherConfig {
	if x != nil {
		return x.Enrichers
	}
	return nil
}

func (x *PipelineConfig) GetDestinations() []string {
	if x != nil {
		return x.Destinations
	}
	return nil
}

type UserIntegrations struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hevy          *HevyIntegration       `protobuf:"bytes,1,opt,name=hevy,proto3" json:"hevy,omitempty"`
	Fitbit        *FitbitIntegration     `protobuf:"bytes,2,opt,name=fitbit,proto3" json:"fitbit,omitempty"`
	Strava        *StravaIntegration     `protobuf:"bytes,3,opt,name=strava,proto3" json:"strava,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserIntegrations) Reset() {
	*x = UserIntegrations{}
	mi := &file_user_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserIntegrations) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserIntegrations) ProtoMessage() {}

func (x *UserIntegrations) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserIntegrations.ProtoReflect.Descriptor instead.
func (*UserIntegrations) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{2}
}

func (x *UserIntegrations) GetHevy() *HevyIntegration {
	if x != nil {
		return x.Hevy
	}
	return nil
}

func (x *UserIntegrations) GetFitbit() *FitbitIntegration {
	if x != nil {
		return x.Fitbit
	}
	return nil
}

func (x *UserIntegrations) GetStrava() *StravaIntegration {
	if x != nil {
		return x.Strava
	}
	return nil
}

type HevyIntegration struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Enabled       bool                   `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	ApiKey        string                 `protobuf:"bytes,2,opt,name=api_key,json=apiKey,proto3" json:"api_key,omitempty"`
	UserId        string                 `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HevyIntegration) Reset() {
	*x = HevyIntegration{}
	mi := &file_user_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HevyIntegration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HevyIntegration) ProtoMessage() {}

func (x *HevyIntegration) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HevyIntegration.ProtoReflect.Descriptor instead.
func (*HevyIntegration) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{3}
}

func (x *HevyIntegration) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *HevyIntegration) GetApiKey() string {
	if x != nil {
		return x.ApiKey
	}
	return ""
}

func (x *HevyIntegration) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type FitbitIntegration struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Enabled       bool                   `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	AccessToken   string                 `protobuf:"bytes,2,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	RefreshToken  string                 `protobuf:"bytes,3,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	ExpiresAt     *timestamp.Timestamp   `protobuf:"bytes,4,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	FitbitUserId  string                 `protobuf:"bytes,5,opt,name=fitbit_user_id,json=fitbitUserId,proto3" json:"fitbit_user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FitbitIntegration) Reset() {
	*x = FitbitIntegration{}
	mi := &file_user_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FitbitIntegration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FitbitIntegration) ProtoMessage() {}

func (x *FitbitIntegration) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FitbitIntegration.ProtoReflect.Descriptor instead.
func (*FitbitIntegration) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{4}
}

func (x *FitbitIntegration) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *FitbitIntegration) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *FitbitIntegration) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

func (x *FitbitIntegration) GetExpiresAt() *timestamp.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

func (x *FitbitIntegration) GetFitbitUserId() string {
	if x != nil {
		return x.FitbitUserId
	}
	return ""
}

type SourceEnrichmentConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Enrichers     []*EnricherConfig      `protobuf:"bytes,1,rep,name=enrichers,proto3" json:"enrichers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SourceEnrichmentConfig) Reset() {
	*x = SourceEnrichmentConfig{}
	mi := &file_user_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SourceEnrichmentConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SourceEnrichmentConfig) ProtoMessage() {}

func (x *SourceEnrichmentConfig) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SourceEnrichmentConfig.ProtoReflect.Descriptor instead.
func (*SourceEnrichmentConfig) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{5}
}

func (x *SourceEnrichmentConfig) GetEnrichers() []*EnricherConfig {
	if x != nil {
		return x.Enrichers
	}
	return nil
}

type EnricherConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Use strictly typed provider enum instead of string name
	ProviderType  EnricherProviderType `protobuf:"varint,1,opt,name=provider_type,json=providerType,proto3,enum=fitglue.EnricherProviderType" json:"provider_type,omitempty"`
	Inputs        map[string]string    `protobuf:"bytes,2,rep,name=inputs,proto3" json:"inputs,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnricherConfig) Reset() {
	*x = EnricherConfig{}
	mi := &file_user_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnricherConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnricherConfig) ProtoMessage() {}

func (x *EnricherConfig) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnricherConfig.ProtoReflect.Descriptor instead.
func (*EnricherConfig) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{6}
}

func (x *EnricherConfig) GetProviderType() EnricherProviderType {
	if x != nil {
		return x.ProviderType
	}
	return EnricherProviderType_ENRICHER_PROVIDER_UNSPECIFIED
}

func (x *EnricherConfig) GetInputs() map[string]string {
	if x != nil {
		return x.Inputs
	}
	return nil
}

type StravaIntegration struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Enabled       bool                   `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	AccessToken   string                 `protobuf:"bytes,2,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	RefreshToken  string                 `protobuf:"bytes,3,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	ExpiresAt     *timestamp.Timestamp   `protobuf:"bytes,4,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	AthleteId     int64                  `protobuf:"varint,5,opt,name=athlete_id,json=athleteId,proto3" json:"athlete_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StravaIntegration) Reset() {
	*x = StravaIntegration{}
	mi := &file_user_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StravaIntegration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StravaIntegration) ProtoMessage() {}

func (x *StravaIntegration) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StravaIntegration.ProtoReflect.Descriptor instead.
func (*StravaIntegration) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{7}
}

func (x *StravaIntegration) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *StravaIntegration) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *StravaIntegration) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

func (x *StravaIntegration) GetExpiresAt() *timestamp.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

func (x *StravaIntegration) GetAthleteId() int64 {
	if x != nil {
		return x.AthleteId
	}
	return 0
}

var File_user_proto protoreflect.FileDescriptor

const file_user_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"user.proto\x12\afitglue\x1a\x1fgoogle/protobuf/timestamp.proto\"\xd6\x01\n" +
	"\n" +
	"UserRecord\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x129\n" +
	"\n" +
	"created_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12=\n" +
	"\fintegrations\x18\x03 \x01(\v2\x19.fitglue.UserIntegrationsR\fintegrations\x125\n" +
	"\tpipelines\x18\x04 \x03(\v2\x17.fitglue.PipelineConfigR\tpipelines\"\x93\x01\n" +
	"\x0ePipelineConfig\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06source\x18\x02 \x01(\tR\x06source\x125\n" +
	"\tenrichers\x18\x03 \x03(\v2\x17.fitglue.EnricherConfigR\tenrichers\x12\"\n" +
	"\fdestinations\x18\x04 \x03(\tR\fdestinations\"\xa8\x01\n" +
	"\x10UserIntegrations\x12,\n" +
	"\x04hevy\x18\x01 \x01(\v2\x18.fitglue.HevyIntegrationR\x04hevy\x122\n" +
	"\x06fitbit\x18\x02 \x01(\v2\x1a.fitglue.FitbitIntegrationR\x06fitbit\x122\n" +
	"\x06strava\x18\x03 \x01(\v2\x1a.fitglue.StravaIntegrationR\x06strava\"]\n" +
	"\x0fHevyIntegration\x12\x18\n" +
	"\aenabled\x18\x01 \x01(\bR\aenabled\x12\x17\n" +
	"\aapi_key\x18\x02 \x01(\tR\x06apiKey\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\tR\x06userId\"\xd6\x01\n" +
	"\x11FitbitIntegration\x12\x18\n" +
	"\aenabled\x18\x01 \x01(\bR\aenabled\x12!\n" +
	"\faccess_token\x18\x02 \x01(\tR\vaccessToken\x12#\n" +
	"\rrefresh_token\x18\x03 \x01(\tR\frefreshToken\x129\n" +
	"\n" +
	"expires_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\x12$\n" +
	"\x0efitbit_user_id\x18\x05 \x01(\tR\ffitbitUserId\"O\n" +
	"\x16SourceEnrichmentConfig\x125\n" +
	"\tenrichers\x18\x01 \x03(\v2\x17.fitglue.EnricherConfigR\tenrichers\"\xcc\x01\n" +
	"\x0eEnricherConfig\x12B\n" +
	"\rprovider_type\x18\x01 \x01(\x0e2\x1d.fitglue.EnricherProviderTypeR\fproviderType\x12;\n" +
	"\x06inputs\x18\x02 \x03(\v2#.fitglue.EnricherConfig.InputsEntryR\x06inputs\x1a9\n" +
	"\vInputsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xcf\x01\n" +
	"\x11StravaIntegration\x12\x18\n" +
	"\aenabled\x18\x01 \x01(\bR\aenabled\x12!\n" +
	"\faccess_token\x18\x02 \x01(\tR\vaccessToken\x12#\n" +
	"\rrefresh_token\x18\x03 \x01(\tR\frefreshToken\x129\n" +
	"\n" +
	"expires_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\x12\x1d\n" +
	"\n" +
	"athlete_id\x18\x05 \x01(\x03R\tathleteId*\xbd\x02\n" +
	"\x14EnricherProviderType\x12!\n" +
	"\x1dENRICHER_PROVIDER_UNSPECIFIED\x10\x00\x12'\n" +
	"#ENRICHER_PROVIDER_FITBIT_HEART_RATE\x10\x01\x12%\n" +
	"!ENRICHER_PROVIDER_WORKOUT_SUMMARY\x10\x02\x12$\n" +
	" ENRICHER_PROVIDER_MUSCLE_HEATMAP\x10\x03\x12!\n" +
	"\x1dENRICHER_PROVIDER_SOURCE_LINK\x10\x04\x12*\n" +
	"&ENRICHER_PROVIDER_METADATA_PASSTHROUGH\x10\x05\x12!\n" +
	"\x1dENRICHER_PROVIDER_VIRTUAL_GPS\x10\x06\x12\x1a\n" +
	"\x16ENRICHER_PROVIDER_MOCK\x10cB\x17Z\x15fitglue/pkg/shared/pbb\x06proto3"

var (
	file_user_proto_rawDescOnce sync.Once
	file_user_proto_rawDescData []byte
)

func file_user_proto_rawDescGZIP() []byte {
	file_user_proto_rawDescOnce.Do(func() {
		file_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_user_proto_rawDesc), len(file_user_proto_rawDesc)))
	})
	return file_user_proto_rawDescData
}

var file_user_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_user_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_user_proto_goTypes = []any{
	(EnricherProviderType)(0),      // 0: fitglue.EnricherProviderType
	(*UserRecord)(nil),             // 1: fitglue.UserRecord
	(*PipelineConfig)(nil),         // 2: fitglue.PipelineConfig
	(*UserIntegrations)(nil),       // 3: fitglue.UserIntegrations
	(*HevyIntegration)(nil),        // 4: fitglue.HevyIntegration
	(*FitbitIntegration)(nil),      // 5: fitglue.FitbitIntegration
	(*SourceEnrichmentConfig)(nil), // 6: fitglue.SourceEnrichmentConfig
	(*EnricherConfig)(nil),         // 7: fitglue.EnricherConfig
	(*StravaIntegration)(nil),      // 8: fitglue.StravaIntegration
	nil,                            // 9: fitglue.EnricherConfig.InputsEntry
	(*timestamp.Timestamp)(nil),    // 10: google.protobuf.Timestamp
}
var file_user_proto_depIdxs = []int32{
	10, // 0: fitglue.UserRecord.created_at:type_name -> google.protobuf.Timestamp
	3,  // 1: fitglue.UserRecord.integrations:type_name -> fitglue.UserIntegrations
	2,  // 2: fitglue.UserRecord.pipelines:type_name -> fitglue.PipelineConfig
	7,  // 3: fitglue.PipelineConfig.enrichers:type_name -> fitglue.EnricherConfig
	4,  // 4: fitglue.UserIntegrations.hevy:type_name -> fitglue.HevyIntegration
	5,  // 5: fitglue.UserIntegrations.fitbit:type_name -> fitglue.FitbitIntegration
	8,  // 6: fitglue.UserIntegrations.strava:type_name -> fitglue.StravaIntegration
	10, // 7: fitglue.FitbitIntegration.expires_at:type_name -> google.protobuf.Timestamp
	7,  // 8: fitglue.SourceEnrichmentConfig.enrichers:type_name -> fitglue.EnricherConfig
	0,  // 9: fitglue.EnricherConfig.provider_type:type_name -> fitglue.EnricherProviderType
	9,  // 10: fitglue.EnricherConfig.inputs:type_name -> fitglue.EnricherConfig.InputsEntry
	10, // 11: fitglue.StravaIntegration.expires_at:type_name -> google.protobuf.Timestamp
	12, // [12:12] is the sub-list for method output_type
	12, // [12:12] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_user_proto_init() }
func file_user_proto_init() {
	if File_user_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_user_proto_rawDesc), len(file_user_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_user_proto_goTypes,
		DependencyIndexes: file_user_proto_depIdxs,
		EnumInfos:         file_user_proto_enumTypes,
		MessageInfos:      file_user_proto_msgTypes,
	}.Build()
	File_user_proto = out.File
	file_user_proto_goTypes = nil
	file_user_proto_depIdxs = nil
}
