// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.12.4
// source: user.proto

package pb

import (
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EnricherProviderType int32

const (
	EnricherProviderType_ENRICHER_PROVIDER_UNSPECIFIED       EnricherProviderType = 0
	EnricherProviderType_ENRICHER_PROVIDER_FITBIT_HEART_RATE EnricherProviderType = 1
	// Config inputs: "format" (compact/detailed/verbose), "show_stats" ("true"/"false")
	EnricherProviderType_ENRICHER_PROVIDER_WORKOUT_SUMMARY      EnricherProviderType = 2
	EnricherProviderType_ENRICHER_PROVIDER_MUSCLE_HEATMAP       EnricherProviderType = 3
	EnricherProviderType_ENRICHER_PROVIDER_SOURCE_LINK          EnricherProviderType = 4
	EnricherProviderType_ENRICHER_PROVIDER_METADATA_PASSTHROUGH EnricherProviderType = 5
	EnricherProviderType_ENRICHER_PROVIDER_VIRTUAL_GPS          EnricherProviderType = 6
	EnricherProviderType_ENRICHER_PROVIDER_TYPE_MAPPER          EnricherProviderType = 7
	EnricherProviderType_ENRICHER_PROVIDER_PARKRUN              EnricherProviderType = 8
	EnricherProviderType_ENRICHER_PROVIDER_CONDITION_MATCHER    EnricherProviderType = 9
	EnricherProviderType_ENRICHER_PROVIDER_AUTO_INCREMENT       EnricherProviderType = 10
	EnricherProviderType_ENRICHER_PROVIDER_USER_INPUT           EnricherProviderType = 11
	// Config inputs: "exclude_activity_types" (comma-separated), "exclude_title_contains" (string)
	EnricherProviderType_ENRICHER_PROVIDER_ACTIVITY_FILTER EnricherProviderType = 12
	EnricherProviderType_ENRICHER_PROVIDER_MOCK            EnricherProviderType = 99
)

// Enum value maps for EnricherProviderType.
var (
	EnricherProviderType_name = map[int32]string{
		0:  "ENRICHER_PROVIDER_UNSPECIFIED",
		1:  "ENRICHER_PROVIDER_FITBIT_HEART_RATE",
		2:  "ENRICHER_PROVIDER_WORKOUT_SUMMARY",
		3:  "ENRICHER_PROVIDER_MUSCLE_HEATMAP",
		4:  "ENRICHER_PROVIDER_SOURCE_LINK",
		5:  "ENRICHER_PROVIDER_METADATA_PASSTHROUGH",
		6:  "ENRICHER_PROVIDER_VIRTUAL_GPS",
		7:  "ENRICHER_PROVIDER_TYPE_MAPPER",
		8:  "ENRICHER_PROVIDER_PARKRUN",
		9:  "ENRICHER_PROVIDER_CONDITION_MATCHER",
		10: "ENRICHER_PROVIDER_AUTO_INCREMENT",
		11: "ENRICHER_PROVIDER_USER_INPUT",
		12: "ENRICHER_PROVIDER_ACTIVITY_FILTER",
		99: "ENRICHER_PROVIDER_MOCK",
	}
	EnricherProviderType_value = map[string]int32{
		"ENRICHER_PROVIDER_UNSPECIFIED":          0,
		"ENRICHER_PROVIDER_FITBIT_HEART_RATE":    1,
		"ENRICHER_PROVIDER_WORKOUT_SUMMARY":      2,
		"ENRICHER_PROVIDER_MUSCLE_HEATMAP":       3,
		"ENRICHER_PROVIDER_SOURCE_LINK":          4,
		"ENRICHER_PROVIDER_METADATA_PASSTHROUGH": 5,
		"ENRICHER_PROVIDER_VIRTUAL_GPS":          6,
		"ENRICHER_PROVIDER_TYPE_MAPPER":          7,
		"ENRICHER_PROVIDER_PARKRUN":              8,
		"ENRICHER_PROVIDER_CONDITION_MATCHER":    9,
		"ENRICHER_PROVIDER_AUTO_INCREMENT":       10,
		"ENRICHER_PROVIDER_USER_INPUT":           11,
		"ENRICHER_PROVIDER_ACTIVITY_FILTER":      12,
		"ENRICHER_PROVIDER_MOCK":                 99,
	}
)

func (x EnricherProviderType) Enum() *EnricherProviderType {
	p := new(EnricherProviderType)
	*p = x
	return p
}

func (x EnricherProviderType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EnricherProviderType) Descriptor() protoreflect.EnumDescriptor {
	return file_user_proto_enumTypes[0].Descriptor()
}

func (EnricherProviderType) Type() protoreflect.EnumType {
	return &file_user_proto_enumTypes[0]
}

func (x EnricherProviderType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EnricherProviderType.Descriptor instead.
func (EnricherProviderType) EnumDescriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{0}
}

// Workout Summary format styles
type WorkoutSummaryFormat int32

const (
	WorkoutSummaryFormat_WORKOUT_SUMMARY_FORMAT_UNSPECIFIED WorkoutSummaryFormat = 0
	WorkoutSummaryFormat_WORKOUT_SUMMARY_FORMAT_COMPACT     WorkoutSummaryFormat = 1 // "4×8@100kg"
	WorkoutSummaryFormat_WORKOUT_SUMMARY_FORMAT_DETAILED    WorkoutSummaryFormat = 2 // "4 sets × 8 reps @ 100.0kg"
	WorkoutSummaryFormat_WORKOUT_SUMMARY_FORMAT_VERBOSE     WorkoutSummaryFormat = 3 // "4 sets of 8 reps at 100.0 kilograms"
)

// Enum value maps for WorkoutSummaryFormat.
var (
	WorkoutSummaryFormat_name = map[int32]string{
		0: "WORKOUT_SUMMARY_FORMAT_UNSPECIFIED",
		1: "WORKOUT_SUMMARY_FORMAT_COMPACT",
		2: "WORKOUT_SUMMARY_FORMAT_DETAILED",
		3: "WORKOUT_SUMMARY_FORMAT_VERBOSE",
	}
	WorkoutSummaryFormat_value = map[string]int32{
		"WORKOUT_SUMMARY_FORMAT_UNSPECIFIED": 0,
		"WORKOUT_SUMMARY_FORMAT_COMPACT":     1,
		"WORKOUT_SUMMARY_FORMAT_DETAILED":    2,
		"WORKOUT_SUMMARY_FORMAT_VERBOSE":     3,
	}
)

func (x WorkoutSummaryFormat) Enum() *WorkoutSummaryFormat {
	p := new(WorkoutSummaryFormat)
	*p = x
	return p
}

func (x WorkoutSummaryFormat) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (WorkoutSummaryFormat) Descriptor() protoreflect.EnumDescriptor {
	return file_user_proto_enumTypes[1].Descriptor()
}

func (WorkoutSummaryFormat) Type() protoreflect.EnumType {
	return &file_user_proto_enumTypes[1]
}

func (x WorkoutSummaryFormat) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use WorkoutSummaryFormat.Descriptor instead.
func (WorkoutSummaryFormat) EnumDescriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{1}
}

// Muscle Heatmap visualization styles
type MuscleHeatmapStyle int32

const (
	MuscleHeatmapStyle_MUSCLE_HEATMAP_STYLE_UNSPECIFIED MuscleHeatmapStyle = 0
	MuscleHeatmapStyle_MUSCLE_HEATMAP_STYLE_EMOJI_BARS  MuscleHeatmapStyle = 1 // "🟪🟪🟪⬜⬜"
	MuscleHeatmapStyle_MUSCLE_HEATMAP_STYLE_PERCENTAGE  MuscleHeatmapStyle = 2 // "Chest: 80%"
	MuscleHeatmapStyle_MUSCLE_HEATMAP_STYLE_TEXT_ONLY   MuscleHeatmapStyle = 3 // "High: Chest, Medium: Legs"
)

// Enum value maps for MuscleHeatmapStyle.
var (
	MuscleHeatmapStyle_name = map[int32]string{
		0: "MUSCLE_HEATMAP_STYLE_UNSPECIFIED",
		1: "MUSCLE_HEATMAP_STYLE_EMOJI_BARS",
		2: "MUSCLE_HEATMAP_STYLE_PERCENTAGE",
		3: "MUSCLE_HEATMAP_STYLE_TEXT_ONLY",
	}
	MuscleHeatmapStyle_value = map[string]int32{
		"MUSCLE_HEATMAP_STYLE_UNSPECIFIED": 0,
		"MUSCLE_HEATMAP_STYLE_EMOJI_BARS":  1,
		"MUSCLE_HEATMAP_STYLE_PERCENTAGE":  2,
		"MUSCLE_HEATMAP_STYLE_TEXT_ONLY":   3,
	}
)

func (x MuscleHeatmapStyle) Enum() *MuscleHeatmapStyle {
	p := new(MuscleHeatmapStyle)
	*p = x
	return p
}

func (x MuscleHeatmapStyle) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MuscleHeatmapStyle) Descriptor() protoreflect.EnumDescriptor {
	return file_user_proto_enumTypes[2].Descriptor()
}

func (MuscleHeatmapStyle) Type() protoreflect.EnumType {
	return &file_user_proto_enumTypes[2]
}

func (x MuscleHeatmapStyle) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MuscleHeatmapStyle.Descriptor instead.
func (MuscleHeatmapStyle) EnumDescriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{2}
}

// Muscle Heatmap coefficient presets
type MuscleHeatmapPreset int32

const (
	MuscleHeatmapPreset_MUSCLE_HEATMAP_PRESET_UNSPECIFIED  MuscleHeatmapPreset = 0
	MuscleHeatmapPreset_MUSCLE_HEATMAP_PRESET_STANDARD     MuscleHeatmapPreset = 1 // Balanced coefficients
	MuscleHeatmapPreset_MUSCLE_HEATMAP_PRESET_POWERLIFTING MuscleHeatmapPreset = 2 // Emphasize compounds
	MuscleHeatmapPreset_MUSCLE_HEATMAP_PRESET_BODYBUILDING MuscleHeatmapPreset = 3 // Emphasize isolation
)

// Enum value maps for MuscleHeatmapPreset.
var (
	MuscleHeatmapPreset_name = map[int32]string{
		0: "MUSCLE_HEATMAP_PRESET_UNSPECIFIED",
		1: "MUSCLE_HEATMAP_PRESET_STANDARD",
		2: "MUSCLE_HEATMAP_PRESET_POWERLIFTING",
		3: "MUSCLE_HEATMAP_PRESET_BODYBUILDING",
	}
	MuscleHeatmapPreset_value = map[string]int32{
		"MUSCLE_HEATMAP_PRESET_UNSPECIFIED":  0,
		"MUSCLE_HEATMAP_PRESET_STANDARD":     1,
		"MUSCLE_HEATMAP_PRESET_POWERLIFTING": 2,
		"MUSCLE_HEATMAP_PRESET_BODYBUILDING": 3,
	}
)

func (x MuscleHeatmapPreset) Enum() *MuscleHeatmapPreset {
	p := new(MuscleHeatmapPreset)
	*p = x
	return p
}

func (x MuscleHeatmapPreset) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MuscleHeatmapPreset) Descriptor() protoreflect.EnumDescriptor {
	return file_user_proto_enumTypes[3].Descriptor()
}

func (MuscleHeatmapPreset) Type() protoreflect.EnumType {
	return &file_user_proto_enumTypes[3]
}

func (x MuscleHeatmapPreset) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MuscleHeatmapPreset.Descriptor instead.
func (MuscleHeatmapPreset) EnumDescriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{3}
}

// Virtual GPS route options
type VirtualGPSRoute int32

const (
	VirtualGPSRoute_VIRTUAL_GPS_ROUTE_UNSPECIFIED VirtualGPSRoute = 0
	VirtualGPSRoute_VIRTUAL_GPS_ROUTE_LONDON      VirtualGPSRoute = 1 // London Hyde Park (~4km)
	VirtualGPSRoute_VIRTUAL_GPS_ROUTE_NYC         VirtualGPSRoute = 2 // NYC Central Park (~10km)
)

// Enum value maps for VirtualGPSRoute.
var (
	VirtualGPSRoute_name = map[int32]string{
		0: "VIRTUAL_GPS_ROUTE_UNSPECIFIED",
		1: "VIRTUAL_GPS_ROUTE_LONDON",
		2: "VIRTUAL_GPS_ROUTE_NYC",
	}
	VirtualGPSRoute_value = map[string]int32{
		"VIRTUAL_GPS_ROUTE_UNSPECIFIED": 0,
		"VIRTUAL_GPS_ROUTE_LONDON":      1,
		"VIRTUAL_GPS_ROUTE_NYC":         2,
	}
)

func (x VirtualGPSRoute) Enum() *VirtualGPSRoute {
	p := new(VirtualGPSRoute)
	*p = x
	return p
}

func (x VirtualGPSRoute) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (VirtualGPSRoute) Descriptor() protoreflect.EnumDescriptor {
	return file_user_proto_enumTypes[4].Descriptor()
}

func (VirtualGPSRoute) Type() protoreflect.EnumType {
	return &file_user_proto_enumTypes[4]
}

func (x VirtualGPSRoute) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use VirtualGPSRoute.Descriptor instead.
func (VirtualGPSRoute) EnumDescriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{4}
}

type UserRecord struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	UserId       string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	CreatedAt    *timestamp.Timestamp   `protobuf:"bytes,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	Integrations *UserIntegrations      `protobuf:"bytes,3,opt,name=integrations,proto3" json:"integrations,omitempty"`
	// Pipelines define the data flow: Source -> Enrichers -> Routing
	Pipelines     []*PipelineConfig `protobuf:"bytes,4,rep,name=pipelines,proto3" json:"pipelines,omitempty"`
	FcmTokens     []string          `protobuf:"bytes,5,rep,name=fcm_tokens,json=fcmTokens,proto3" json:"fcm_tokens,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserRecord) Reset() {
	*x = UserRecord{}
	mi := &file_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserRecord) ProtoMessage() {}

func (x *UserRecord) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserRecord.ProtoReflect.Descriptor instead.
func (*UserRecord) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{0}
}

func (x *UserRecord) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UserRecord) GetCreatedAt() *timestamp.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *UserRecord) GetIntegrations() *UserIntegrations {
	if x != nil {
		return x.Integrations
	}
	return nil
}

func (x *UserRecord) GetPipelines() []*PipelineConfig {
	if x != nil {
		return x.Pipelines
	}
	return nil
}

func (x *UserRecord) GetFcmTokens() []string {
	if x != nil {
		return x.FcmTokens
	}
	return nil
}

type PipelineConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`         // Unique ID (uuid) for tracing
	Source        string                 `protobuf:"bytes,2,opt,name=source,proto3" json:"source,omitempty"` // e.g. "SOURCE_HEVY"
	Enrichers     []*EnricherConfig      `protobuf:"bytes,3,rep,name=enrichers,proto3" json:"enrichers,omitempty"`
	Destinations  []Destination          `protobuf:"varint,4,rep,packed,name=destinations,proto3,enum=fitglue.events.Destination" json:"destinations,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PipelineConfig) Reset() {
	*x = PipelineConfig{}
	mi := &file_user_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PipelineConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PipelineConfig) ProtoMessage() {}

func (x *PipelineConfig) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PipelineConfig.ProtoReflect.Descriptor instead.
func (*PipelineConfig) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{1}
}

func (x *PipelineConfig) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PipelineConfig) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *PipelineConfig) GetEnrichers() []*EnricherConfig {
	if x != nil {
		return x.Enrichers
	}
	return nil
}

func (x *PipelineConfig) GetDestinations() []Destination {
	if x != nil {
		return x.Destinations
	}
	return nil
}

type UserIntegrations struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hevy          *HevyIntegration       `protobuf:"bytes,1,opt,name=hevy,proto3" json:"hevy,omitempty"`
	Fitbit        *FitbitIntegration     `protobuf:"bytes,2,opt,name=fitbit,proto3" json:"fitbit,omitempty"`
	Strava        *StravaIntegration     `protobuf:"bytes,3,opt,name=strava,proto3" json:"strava,omitempty"`
	Mock          *MockIntegration       `protobuf:"bytes,4,opt,name=mock,proto3" json:"mock,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserIntegrations) Reset() {
	*x = UserIntegrations{}
	mi := &file_user_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserIntegrations) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserIntegrations) ProtoMessage() {}

func (x *UserIntegrations) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserIntegrations.ProtoReflect.Descriptor instead.
func (*UserIntegrations) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{2}
}

func (x *UserIntegrations) GetHevy() *HevyIntegration {
	if x != nil {
		return x.Hevy
	}
	return nil
}

func (x *UserIntegrations) GetFitbit() *FitbitIntegration {
	if x != nil {
		return x.Fitbit
	}
	return nil
}

func (x *UserIntegrations) GetStrava() *StravaIntegration {
	if x != nil {
		return x.Strava
	}
	return nil
}

func (x *UserIntegrations) GetMock() *MockIntegration {
	if x != nil {
		return x.Mock
	}
	return nil
}

type MockIntegration struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Enabled       bool                   `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	CreatedAt     *timestamp.Timestamp   `protobuf:"bytes,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	LastUsedAt    *timestamp.Timestamp   `protobuf:"bytes,3,opt,name=last_used_at,json=lastUsedAt,proto3" json:"last_used_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MockIntegration) Reset() {
	*x = MockIntegration{}
	mi := &file_user_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MockIntegration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MockIntegration) ProtoMessage() {}

func (x *MockIntegration) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MockIntegration.ProtoReflect.Descriptor instead.
func (*MockIntegration) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{3}
}

func (x *MockIntegration) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *MockIntegration) GetCreatedAt() *timestamp.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *MockIntegration) GetLastUsedAt() *timestamp.Timestamp {
	if x != nil {
		return x.LastUsedAt
	}
	return nil
}

type HevyIntegration struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Enabled       bool                   `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	ApiKey        string                 `protobuf:"bytes,2,opt,name=api_key,json=apiKey,proto3" json:"api_key,omitempty"`
	UserId        string                 `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	CreatedAt     *timestamp.Timestamp   `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	LastUsedAt    *timestamp.Timestamp   `protobuf:"bytes,5,opt,name=last_used_at,json=lastUsedAt,proto3" json:"last_used_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HevyIntegration) Reset() {
	*x = HevyIntegration{}
	mi := &file_user_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HevyIntegration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HevyIntegration) ProtoMessage() {}

func (x *HevyIntegration) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HevyIntegration.ProtoReflect.Descriptor instead.
func (*HevyIntegration) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{4}
}

func (x *HevyIntegration) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *HevyIntegration) GetApiKey() string {
	if x != nil {
		return x.ApiKey
	}
	return ""
}

func (x *HevyIntegration) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *HevyIntegration) GetCreatedAt() *timestamp.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *HevyIntegration) GetLastUsedAt() *timestamp.Timestamp {
	if x != nil {
		return x.LastUsedAt
	}
	return nil
}

type FitbitIntegration struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Enabled       bool                   `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	AccessToken   string                 `protobuf:"bytes,2,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	RefreshToken  string                 `protobuf:"bytes,3,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	ExpiresAt     *timestamp.Timestamp   `protobuf:"bytes,4,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	FitbitUserId  string                 `protobuf:"bytes,5,opt,name=fitbit_user_id,json=fitbitUserId,proto3" json:"fitbit_user_id,omitempty"`
	CreatedAt     *timestamp.Timestamp   `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	LastUsedAt    *timestamp.Timestamp   `protobuf:"bytes,7,opt,name=last_used_at,json=lastUsedAt,proto3" json:"last_used_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FitbitIntegration) Reset() {
	*x = FitbitIntegration{}
	mi := &file_user_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FitbitIntegration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FitbitIntegration) ProtoMessage() {}

func (x *FitbitIntegration) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FitbitIntegration.ProtoReflect.Descriptor instead.
func (*FitbitIntegration) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{5}
}

func (x *FitbitIntegration) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *FitbitIntegration) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *FitbitIntegration) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

func (x *FitbitIntegration) GetExpiresAt() *timestamp.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

func (x *FitbitIntegration) GetFitbitUserId() string {
	if x != nil {
		return x.FitbitUserId
	}
	return ""
}

func (x *FitbitIntegration) GetCreatedAt() *timestamp.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *FitbitIntegration) GetLastUsedAt() *timestamp.Timestamp {
	if x != nil {
		return x.LastUsedAt
	}
	return nil
}

type SourceEnrichmentConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Enrichers     []*EnricherConfig      `protobuf:"bytes,1,rep,name=enrichers,proto3" json:"enrichers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SourceEnrichmentConfig) Reset() {
	*x = SourceEnrichmentConfig{}
	mi := &file_user_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SourceEnrichmentConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SourceEnrichmentConfig) ProtoMessage() {}

func (x *SourceEnrichmentConfig) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SourceEnrichmentConfig.ProtoReflect.Descriptor instead.
func (*SourceEnrichmentConfig) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{6}
}

func (x *SourceEnrichmentConfig) GetEnrichers() []*EnricherConfig {
	if x != nil {
		return x.Enrichers
	}
	return nil
}

type EnricherConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Use strictly typed provider enum instead of string name
	ProviderType EnricherProviderType `protobuf:"varint,1,opt,name=provider_type,json=providerType,proto3,enum=fitglue.EnricherProviderType" json:"provider_type,omitempty"`
	// Type-safe configuration map (validated against PluginManifest.config_schema)
	// Keys and values are descriptive strings, not numeric enum values
	TypedConfig   map[string]string `protobuf:"bytes,2,rep,name=typed_config,json=typedConfig,proto3" json:"typed_config,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnricherConfig) Reset() {
	*x = EnricherConfig{}
	mi := &file_user_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnricherConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnricherConfig) ProtoMessage() {}

func (x *EnricherConfig) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnricherConfig.ProtoReflect.Descriptor instead.
func (*EnricherConfig) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{7}
}

func (x *EnricherConfig) GetProviderType() EnricherProviderType {
	if x != nil {
		return x.ProviderType
	}
	return EnricherProviderType_ENRICHER_PROVIDER_UNSPECIFIED
}

func (x *EnricherConfig) GetTypedConfig() map[string]string {
	if x != nil {
		return x.TypedConfig
	}
	return nil
}

type StravaIntegration struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Enabled       bool                   `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	AccessToken   string                 `protobuf:"bytes,2,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	RefreshToken  string                 `protobuf:"bytes,3,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	ExpiresAt     *timestamp.Timestamp   `protobuf:"bytes,4,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	AthleteId     int64                  `protobuf:"varint,5,opt,name=athlete_id,json=athleteId,proto3" json:"athlete_id,omitempty"`
	CreatedAt     *timestamp.Timestamp   `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	LastUsedAt    *timestamp.Timestamp   `protobuf:"bytes,7,opt,name=last_used_at,json=lastUsedAt,proto3" json:"last_used_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StravaIntegration) Reset() {
	*x = StravaIntegration{}
	mi := &file_user_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StravaIntegration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StravaIntegration) ProtoMessage() {}

func (x *StravaIntegration) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StravaIntegration.ProtoReflect.Descriptor instead.
func (*StravaIntegration) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{8}
}

func (x *StravaIntegration) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *StravaIntegration) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *StravaIntegration) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

func (x *StravaIntegration) GetExpiresAt() *timestamp.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

func (x *StravaIntegration) GetAthleteId() int64 {
	if x != nil {
		return x.AthleteId
	}
	return 0
}

func (x *StravaIntegration) GetCreatedAt() *timestamp.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *StravaIntegration) GetLastUsedAt() *timestamp.Timestamp {
	if x != nil {
		return x.LastUsedAt
	}
	return nil
}

type ProcessedActivityRecord struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Source        string                 `protobuf:"bytes,1,opt,name=source,proto3" json:"source,omitempty"`
	ExternalId    string                 `protobuf:"bytes,2,opt,name=external_id,json=externalId,proto3" json:"external_id,omitempty"` // Unique ID from provider
	ProcessedAt   *timestamp.Timestamp   `protobuf:"bytes,3,opt,name=processed_at,json=processedAt,proto3" json:"processed_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessedActivityRecord) Reset() {
	*x = ProcessedActivityRecord{}
	mi := &file_user_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessedActivityRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessedActivityRecord) ProtoMessage() {}

func (x *ProcessedActivityRecord) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessedActivityRecord.ProtoReflect.Descriptor instead.
func (*ProcessedActivityRecord) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{9}
}

func (x *ProcessedActivityRecord) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *ProcessedActivityRecord) GetExternalId() string {
	if x != nil {
		return x.ExternalId
	}
	return ""
}

func (x *ProcessedActivityRecord) GetProcessedAt() *timestamp.Timestamp {
	if x != nil {
		return x.ProcessedAt
	}
	return nil
}

type Counter struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"` // Key, e.g. "parkrun_bushy"
	Count         int64                  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	LastUpdated   *timestamp.Timestamp   `protobuf:"bytes,3,opt,name=last_updated,json=lastUpdated,proto3" json:"last_updated,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Counter) Reset() {
	*x = Counter{}
	mi := &file_user_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Counter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Counter) ProtoMessage() {}

func (x *Counter) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Counter.ProtoReflect.Descriptor instead.
func (*Counter) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{10}
}

func (x *Counter) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Counter) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *Counter) GetLastUpdated() *timestamp.Timestamp {
	if x != nil {
		return x.LastUpdated
	}
	return nil
}

type SynchronizedActivity struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	ActivityId          string                 `protobuf:"bytes,1,opt,name=activity_id,json=activityId,proto3" json:"activity_id,omitempty"`
	Title               string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description         string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Type                ActivityType           `protobuf:"varint,4,opt,name=type,proto3,enum=fitglue.ActivityType" json:"type,omitempty"`
	Source              string                 `protobuf:"bytes,5,opt,name=source,proto3" json:"source,omitempty"` // e.g. "SOURCE_HEVY"
	StartTime           *timestamp.Timestamp   `protobuf:"bytes,6,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	Destinations        map[string]string      `protobuf:"bytes,7,rep,name=destinations,proto3" json:"destinations,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // destination -> external_id
	SyncedAt            *timestamp.Timestamp   `protobuf:"bytes,8,opt,name=synced_at,json=syncedAt,proto3" json:"synced_at,omitempty"`
	PipelineId          string                 `protobuf:"bytes,9,opt,name=pipeline_id,json=pipelineId,proto3" json:"pipeline_id,omitempty"`
	PipelineExecutionId string                 `protobuf:"bytes,10,opt,name=pipeline_execution_id,json=pipelineExecutionId,proto3" json:"pipeline_execution_id,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *SynchronizedActivity) Reset() {
	*x = SynchronizedActivity{}
	mi := &file_user_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SynchronizedActivity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SynchronizedActivity) ProtoMessage() {}

func (x *SynchronizedActivity) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SynchronizedActivity.ProtoReflect.Descriptor instead.
func (*SynchronizedActivity) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{11}
}

func (x *SynchronizedActivity) GetActivityId() string {
	if x != nil {
		return x.ActivityId
	}
	return ""
}

func (x *SynchronizedActivity) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *SynchronizedActivity) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *SynchronizedActivity) GetType() ActivityType {
	if x != nil {
		return x.Type
	}
	return ActivityType_ACTIVITY_TYPE_UNSPECIFIED
}

func (x *SynchronizedActivity) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *SynchronizedActivity) GetStartTime() *timestamp.Timestamp {
	if x != nil {
		return x.StartTime
	}
	return nil
}

func (x *SynchronizedActivity) GetDestinations() map[string]string {
	if x != nil {
		return x.Destinations
	}
	return nil
}

func (x *SynchronizedActivity) GetSyncedAt() *timestamp.Timestamp {
	if x != nil {
		return x.SyncedAt
	}
	return nil
}

func (x *SynchronizedActivity) GetPipelineId() string {
	if x != nil {
		return x.PipelineId
	}
	return ""
}

func (x *SynchronizedActivity) GetPipelineExecutionId() string {
	if x != nil {
		return x.PipelineExecutionId
	}
	return ""
}

var File_user_proto protoreflect.FileDescriptor

const file_user_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"user.proto\x12\afitglue\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1bstandardized_activity.proto\x1a\fevents.proto\"\xf5\x01\n" +
	"\n" +
	"UserRecord\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x129\n" +
	"\n" +
	"created_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12=\n" +
	"\fintegrations\x18\x03 \x01(\v2\x19.fitglue.UserIntegrationsR\fintegrations\x125\n" +
	"\tpipelines\x18\x04 \x03(\v2\x17.fitglue.PipelineConfigR\tpipelines\x12\x1d\n" +
	"\n" +
	"fcm_tokens\x18\x05 \x03(\tR\tfcmTokens\"\xb0\x01\n" +
	"\x0ePipelineConfig\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06source\x18\x02 \x01(\tR\x06source\x125\n" +
	"\tenrichers\x18\x03 \x03(\v2\x17.fitglue.EnricherConfigR\tenrichers\x12?\n" +
	"\fdestinations\x18\x04 \x03(\x0e2\x1b.fitglue.events.DestinationR\fdestinations\"\xd6\x01\n" +
	"\x10UserIntegrations\x12,\n" +
	"\x04hevy\x18\x01 \x01(\v2\x18.fitglue.HevyIntegrationR\x04hevy\x122\n" +
	"\x06fitbit\x18\x02 \x01(\v2\x1a.fitglue.FitbitIntegrationR\x06fitbit\x122\n" +
	"\x06strava\x18\x03 \x01(\v2\x1a.fitglue.StravaIntegrationR\x06strava\x12,\n" +
	"\x04mock\x18\x04 \x01(\v2\x18.fitglue.MockIntegrationR\x04mock\"\xa4\x01\n" +
	"\x0fMockIntegration\x12\x18\n" +
	"\aenabled\x18\x01 \x01(\bR\aenabled\x129\n" +
	"\n" +
	"created_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12<\n" +
	"\flast_used_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"lastUsedAt\"\xd6\x01\n" +
	"\x0fHevyIntegration\x12\x18\n" +
	"\aenabled\x18\x01 \x01(\bR\aenabled\x12\x17\n" +
	"\aapi_key\x18\x02 \x01(\tR\x06apiKey\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\tR\x06userId\x129\n" +
	"\n" +
	"created_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12<\n" +
	"\flast_used_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"lastUsedAt\"\xcf\x02\n" +
	"\x11FitbitIntegration\x12\x18\n" +
	"\aenabled\x18\x01 \x01(\bR\aenabled\x12!\n" +
	"\faccess_token\x18\x02 \x01(\tR\vaccessToken\x12#\n" +
	"\rrefresh_token\x18\x03 \x01(\tR\frefreshToken\x129\n" +
	"\n" +
	"expires_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\x12$\n" +
	"\x0efitbit_user_id\x18\x05 \x01(\tR\ffitbitUserId\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12<\n" +
	"\flast_used_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"lastUsedAt\"O\n" +
	"\x16SourceEnrichmentConfig\x125\n" +
	"\tenrichers\x18\x01 \x03(\v2\x17.fitglue.EnricherConfigR\tenrichers\"\xe1\x01\n" +
	"\x0eEnricherConfig\x12B\n" +
	"\rprovider_type\x18\x01 \x01(\x0e2\x1d.fitglue.EnricherProviderTypeR\fproviderType\x12K\n" +
	"\ftyped_config\x18\x02 \x03(\v2(.fitglue.EnricherConfig.TypedConfigEntryR\vtypedConfig\x1a>\n" +
	"\x10TypedConfigEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xc8\x02\n" +
	"\x11StravaIntegration\x12\x18\n" +
	"\aenabled\x18\x01 \x01(\bR\aenabled\x12!\n" +
	"\faccess_token\x18\x02 \x01(\tR\vaccessToken\x12#\n" +
	"\rrefresh_token\x18\x03 \x01(\tR\frefreshToken\x129\n" +
	"\n" +
	"expires_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\x12\x1d\n" +
	"\n" +
	"athlete_id\x18\x05 \x01(\x03R\tathleteId\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12<\n" +
	"\flast_used_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"lastUsedAt\"\x91\x01\n" +
	"\x17ProcessedActivityRecord\x12\x16\n" +
	"\x06source\x18\x01 \x01(\tR\x06source\x12\x1f\n" +
	"\vexternal_id\x18\x02 \x01(\tR\n" +
	"externalId\x12=\n" +
	"\fprocessed_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\vprocessedAt\"n\n" +
	"\aCounter\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x03R\x05count\x12=\n" +
	"\flast_updated\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\vlastUpdated\"\x91\x04\n" +
	"\x14SynchronizedActivity\x12\x1f\n" +
	"\vactivity_id\x18\x01 \x01(\tR\n" +
	"activityId\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12)\n" +
	"\x04type\x18\x04 \x01(\x0e2\x15.fitglue.ActivityTypeR\x04type\x12\x16\n" +
	"\x06source\x18\x05 \x01(\tR\x06source\x129\n" +
	"\n" +
	"start_time\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tstartTime\x12S\n" +
	"\fdestinations\x18\a \x03(\v2/.fitglue.SynchronizedActivity.DestinationsEntryR\fdestinations\x127\n" +
	"\tsynced_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\bsyncedAt\x12\x1f\n" +
	"\vpipeline_id\x18\t \x01(\tR\n" +
	"pipelineId\x122\n" +
	"\x15pipeline_execution_id\x18\n" +
	" \x01(\tR\x13pipelineExecutionId\x1a?\n" +
	"\x11DestinationsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01*\x97\x04\n" +
	"\x14EnricherProviderType\x12!\n" +
	"\x1dENRICHER_PROVIDER_UNSPECIFIED\x10\x00\x12'\n" +
	"#ENRICHER_PROVIDER_FITBIT_HEART_RATE\x10\x01\x12%\n" +
	"!ENRICHER_PROVIDER_WORKOUT_SUMMARY\x10\x02\x12$\n" +
	" ENRICHER_PROVIDER_MUSCLE_HEATMAP\x10\x03\x12!\n" +
	"\x1dENRICHER_PROVIDER_SOURCE_LINK\x10\x04\x12*\n" +
	"&ENRICHER_PROVIDER_METADATA_PASSTHROUGH\x10\x05\x12!\n" +
	"\x1dENRICHER_PROVIDER_VIRTUAL_GPS\x10\x06\x12!\n" +
	"\x1dENRICHER_PROVIDER_TYPE_MAPPER\x10\a\x12\x1d\n" +
	"\x19ENRICHER_PROVIDER_PARKRUN\x10\b\x12'\n" +
	"#ENRICHER_PROVIDER_CONDITION_MATCHER\x10\t\x12$\n" +
	" ENRICHER_PROVIDER_AUTO_INCREMENT\x10\n" +
	"\x12 \n" +
	"\x1cENRICHER_PROVIDER_USER_INPUT\x10\v\x12%\n" +
	"!ENRICHER_PROVIDER_ACTIVITY_FILTER\x10\f\x12\x1a\n" +
	"\x16ENRICHER_PROVIDER_MOCK\x10c*\xab\x01\n" +
	"\x14WorkoutSummaryFormat\x12&\n" +
	"\"WORKOUT_SUMMARY_FORMAT_UNSPECIFIED\x10\x00\x12\"\n" +
	"\x1eWORKOUT_SUMMARY_FORMAT_COMPACT\x10\x01\x12#\n" +
	"\x1fWORKOUT_SUMMARY_FORMAT_DETAILED\x10\x02\x12\"\n" +
	"\x1eWORKOUT_SUMMARY_FORMAT_VERBOSE\x10\x03*\xa8\x01\n" +
	"\x12MuscleHeatmapStyle\x12$\n" +
	" MUSCLE_HEATMAP_STYLE_UNSPECIFIED\x10\x00\x12#\n" +
	"\x1fMUSCLE_HEATMAP_STYLE_EMOJI_BARS\x10\x01\x12#\n" +
	"\x1fMUSCLE_HEATMAP_STYLE_PERCENTAGE\x10\x02\x12\"\n" +
	"\x1eMUSCLE_HEATMAP_STYLE_TEXT_ONLY\x10\x03*\xb0\x01\n" +
	"\x13MuscleHeatmapPreset\x12%\n" +
	"!MUSCLE_HEATMAP_PRESET_UNSPECIFIED\x10\x00\x12\"\n" +
	"\x1eMUSCLE_HEATMAP_PRESET_STANDARD\x10\x01\x12&\n" +
	"\"MUSCLE_HEATMAP_PRESET_POWERLIFTING\x10\x02\x12&\n" +
	"\"MUSCLE_HEATMAP_PRESET_BODYBUILDING\x10\x03*m\n" +
	"\x0fVirtualGPSRoute\x12!\n" +
	"\x1dVIRTUAL_GPS_ROUTE_UNSPECIFIED\x10\x00\x12\x1c\n" +
	"\x18VIRTUAL_GPS_ROUTE_LONDON\x10\x01\x12\x19\n" +
	"\x15VIRTUAL_GPS_ROUTE_NYC\x10\x02B7Z5github.com/ripixel/fitglue-server/src/go/pkg/types/pbb\x06proto3"

var (
	file_user_proto_rawDescOnce sync.Once
	file_user_proto_rawDescData []byte
)

func file_user_proto_rawDescGZIP() []byte {
	file_user_proto_rawDescOnce.Do(func() {
		file_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_user_proto_rawDesc), len(file_user_proto_rawDesc)))
	})
	return file_user_proto_rawDescData
}

var file_user_proto_enumTypes = make([]protoimpl.EnumInfo, 5)
var file_user_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_user_proto_goTypes = []any{
	(EnricherProviderType)(0),       // 0: fitglue.EnricherProviderType
	(WorkoutSummaryFormat)(0),       // 1: fitglue.WorkoutSummaryFormat
	(MuscleHeatmapStyle)(0),         // 2: fitglue.MuscleHeatmapStyle
	(MuscleHeatmapPreset)(0),        // 3: fitglue.MuscleHeatmapPreset
	(VirtualGPSRoute)(0),            // 4: fitglue.VirtualGPSRoute
	(*UserRecord)(nil),              // 5: fitglue.UserRecord
	(*PipelineConfig)(nil),          // 6: fitglue.PipelineConfig
	(*UserIntegrations)(nil),        // 7: fitglue.UserIntegrations
	(*MockIntegration)(nil),         // 8: fitglue.MockIntegration
	(*HevyIntegration)(nil),         // 9: fitglue.HevyIntegration
	(*FitbitIntegration)(nil),       // 10: fitglue.FitbitIntegration
	(*SourceEnrichmentConfig)(nil),  // 11: fitglue.SourceEnrichmentConfig
	(*EnricherConfig)(nil),          // 12: fitglue.EnricherConfig
	(*StravaIntegration)(nil),       // 13: fitglue.StravaIntegration
	(*ProcessedActivityRecord)(nil), // 14: fitglue.ProcessedActivityRecord
	(*Counter)(nil),                 // 15: fitglue.Counter
	(*SynchronizedActivity)(nil),    // 16: fitglue.SynchronizedActivity
	nil,                             // 17: fitglue.EnricherConfig.TypedConfigEntry
	nil,                             // 18: fitglue.SynchronizedActivity.DestinationsEntry
	(*timestamp.Timestamp)(nil),     // 19: google.protobuf.Timestamp
	(Destination)(0),                // 20: fitglue.events.Destination
	(ActivityType)(0),               // 21: fitglue.ActivityType
}
var file_user_proto_depIdxs = []int32{
	19, // 0: fitglue.UserRecord.created_at:type_name -> google.protobuf.Timestamp
	7,  // 1: fitglue.UserRecord.integrations:type_name -> fitglue.UserIntegrations
	6,  // 2: fitglue.UserRecord.pipelines:type_name -> fitglue.PipelineConfig
	12, // 3: fitglue.PipelineConfig.enrichers:type_name -> fitglue.EnricherConfig
	20, // 4: fitglue.PipelineConfig.destinations:type_name -> fitglue.events.Destination
	9,  // 5: fitglue.UserIntegrations.hevy:type_name -> fitglue.HevyIntegration
	10, // 6: fitglue.UserIntegrations.fitbit:type_name -> fitglue.FitbitIntegration
	13, // 7: fitglue.UserIntegrations.strava:type_name -> fitglue.StravaIntegration
	8,  // 8: fitglue.UserIntegrations.mock:type_name -> fitglue.MockIntegration
	19, // 9: fitglue.MockIntegration.created_at:type_name -> google.protobuf.Timestamp
	19, // 10: fitglue.MockIntegration.last_used_at:type_name -> google.protobuf.Timestamp
	19, // 11: fitglue.HevyIntegration.created_at:type_name -> google.protobuf.Timestamp
	19, // 12: fitglue.HevyIntegration.last_used_at:type_name -> google.protobuf.Timestamp
	19, // 13: fitglue.FitbitIntegration.expires_at:type_name -> google.protobuf.Timestamp
	19, // 14: fitglue.FitbitIntegration.created_at:type_name -> google.protobuf.Timestamp
	19, // 15: fitglue.FitbitIntegration.last_used_at:type_name -> google.protobuf.Timestamp
	12, // 16: fitglue.SourceEnrichmentConfig.enrichers:type_name -> fitglue.EnricherConfig
	0,  // 17: fitglue.EnricherConfig.provider_type:type_name -> fitglue.EnricherProviderType
	17, // 18: fitglue.EnricherConfig.typed_config:type_name -> fitglue.EnricherConfig.TypedConfigEntry
	19, // 19: fitglue.StravaIntegration.expires_at:type_name -> google.protobuf.Timestamp
	19, // 20: fitglue.StravaIntegration.created_at:type_name -> google.protobuf.Timestamp
	19, // 21: fitglue.StravaIntegration.last_used_at:type_name -> google.protobuf.Timestamp
	19, // 22: fitglue.ProcessedActivityRecord.processed_at:type_name -> google.protobuf.Timestamp
	19, // 23: fitglue.Counter.last_updated:type_name -> google.protobuf.Timestamp
	21, // 24: fitglue.SynchronizedActivity.type:type_name -> fitglue.ActivityType
	19, // 25: fitglue.SynchronizedActivity.start_time:type_name -> google.protobuf.Timestamp
	18, // 26: fitglue.SynchronizedActivity.destinations:type_name -> fitglue.SynchronizedActivity.DestinationsEntry
	19, // 27: fitglue.SynchronizedActivity.synced_at:type_name -> google.protobuf.Timestamp
	28, // [28:28] is the sub-list for method output_type
	28, // [28:28] is the sub-list for method input_type
	28, // [28:28] is the sub-list for extension type_name
	28, // [28:28] is the sub-list for extension extendee
	0,  // [0:28] is the sub-list for field type_name
}

func init() { file_user_proto_init() }
func file_user_proto_init() {
	if File_user_proto != nil {
		return
	}
	file_standardized_activity_proto_init()
	file_events_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_user_proto_rawDesc), len(file_user_proto_rawDesc)),
			NumEnums:      5,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_user_proto_goTypes,
		DependencyIndexes: file_user_proto_depIdxs,
		EnumInfos:         file_user_proto_enumTypes,
		MessageInfos:      file_user_proto_msgTypes,
	}.Build()
	File_user_proto = out.File
	file_user_proto_goTypes = nil
	file_user_proto_depIdxs = nil
}
